"""
This type stub file was generated by pyright.
"""

class BaseRenderer:
	# Set in __init__ at runtime (self.path = path / self.http_status_code = ...);
	# declared here so subclass attribute access resolves under pyright.
	path: str
	http_status_code: int | None
	def __init__(self, path=..., http_status_code=...) -> None:
		...
	
	def can_render(self):
		...
	
	def render(self):
		...
	
	def build_response(self, data, http_status_code=..., headers=...): # -> Response:
		...
	


