"""
This type stub file was generated by pyright.
"""

from frappe.website.page_renderers.base_renderer import BaseRenderer

class BaseTemplatePage(BaseRenderer):
	def __init__(self, path, http_status_code=...) -> None:
		...
	
	def init_context(self): # -> None:
		...
	
	def add_csrf_token(self, html):
		...
	
	def post_process_context(self): # -> None:
		...
	
	def set_base_template_if_missing(self): # -> None:
		...
	
	def set_title_with_prefix(self): # -> None:
		...
	
	def set_missing_values(self): # -> None:
		...
	
	def update_website_context(self): # -> None:
		...
	


