"""
This type stub file was generated by pyright.
"""

from frappe.website.page_renderers.template_page import TemplatePage

class ListPage(TemplatePage):
	def can_render(self): # -> bool:
		...
	
	def render(self): # -> Response:
		...
	


