"""
This type stub file was generated by pyright.
"""

from frappe.website.page_renderers.template_page import TemplatePage

HOMEPAGE_PATHS = ...
class NotFoundPage(TemplatePage):
	def __init__(self, path, http_status_code=...) -> None:
		...
	
	def can_render(self): # -> Literal[True]:
		...
	
	def render(self): # -> Response:
		...
	
	def can_cache_404(self): # -> Any | bool | Literal['']:
		...
	
	def is_custom_home_page(self): # -> bool:
		...
	
	def has_website_permission_check(self): # -> bool:
		...
	


