"""
This type stub file was generated by pyright.
"""

from frappe.website.page_renderers.template_page import TemplatePage

class NotPermittedPage(TemplatePage):
	def __init__(self, path=..., http_status_code=..., exception=...) -> None:
		...
	
	def can_render(self): # -> Literal[True]:
		...
	
	def render(self): # -> Response:
		...
	


