"""
This type stub file was generated by pyright.
"""

class RedirectPage:
	def __init__(self, path, http_status_code=...) -> None:
		...
	
	def can_render(self): # -> Literal[True]:
		...
	
	def render(self): # -> Response:
		...
	


