"""
This type stub file was generated by pyright.
"""

from frappe.website.page_renderers.base_renderer import BaseRenderer

UNSUPPORTED_STATIC_PAGE_TYPES = ...
class StaticPage(BaseRenderer):
	__slots__ = ...
	def __init__(self, path, http_status_code=...) -> None:
		...
	
	def set_file_path(self): # -> None:
		...
	
	def can_render(self): # -> str | Path | Literal[False]:
		...
	
	def is_valid_file_path(self): # -> bool:
		...
	
	def render(self): # -> Response:
		...
	


