"""
This type stub file was generated by pyright.
"""

from frappe.website.page_renderers.document_page import DocumentPage

class WebFormPage(DocumentPage):
	def can_render(self): # -> bool:
		...
	
	def set_headers(self): # -> None:
		...
	


