"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class DocPerm(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		amend: DF.Check
		cancel: DF.Check
		create: DF.Check
		delete: DF.Check
		email: DF.Check
		export: DF.Check
		if_owner: DF.Check
		mask: DF.Check
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		permlevel: DF.Int
		print: DF.Check
		read: DF.Check
		report: DF.Check
		role: DF.Link
		select: DF.Check
		share: DF.Check
		submit: DF.Check
		write: DF.Check
		...


