"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class WebhookData(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		fieldname: DF.Literal[None]
		key: DF.Data
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		...


