"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class RecorderSuggestedIndex(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		column: DF.Data | None
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		table: DF.Data | None
		...
	def db_insert(self, *args, **kwargs):
		...
	
	def load_from_db(self):
		...
	
	def db_update(self):
		...
	
	def delete(self):
		...
	
	@staticmethod
	def get_list(filters=..., page_length=..., **kwargs): # -> None:
		...
	
	@staticmethod
	def get_count(filters=..., **kwargs): # -> None:
		...
	
	@staticmethod
	def get_stats(**kwargs): # -> None:
		...
	


