"""
This type stub file was generated by pyright.
"""

import frappe
from typing import TYPE_CHECKING
from frappe.utils.caching import site_cache
from types import ModuleType
from frappe.model.document import Document

"""
Utilities for using modules
"""
if TYPE_CHECKING:
	...
doctype_python_modules = ...
def export_module_json(doc: Document, is_standard: bool, module: str, *, create_init: bool | None = ...) -> str | None:
	"""Make a folder for the given doc and add its json file (make it a standard object that will be synced).

	Return the absolute file_path without the extension.
	Eg: For exporting a Print Format "_Test Print Format 1", the return value will be
	`/home/gavin/frappe-bench/apps/frappe/frappe/core/print_format/_test_print_format_1/_test_print_format_1`
	"""
	...

def get_doc_module(module: str, doctype: str, name: str) -> ModuleType:
	"""Get custom module for given document"""
	...

@frappe.whitelist()
def export_customizations(module: str, doctype: str, sync_on_migrate: bool = ..., with_permissions: bool = ..., apply_module_export_filter: bool = ...): # -> str | None:
	"""Export Custom Field and Property Setter for the current document to the app folder.
	This will be synced with bench migrate"""
	...

def sync_customizations(app=...): # -> None:
	"""Sync custom fields and property setters from custom folder in each app module"""
	...

def sync_customizations_for_doctype(data: dict, folder: str, filename: str = ...): # -> None:
	"""Sync doctype customzations for a particular data set"""
	...

def scrub_dt_dn(dt: str, dn: str) -> tuple[str, str]:
	"""Return in lowercase and code friendly names of doctype and name for certain types."""
	...

def get_doc_path(module: str, doctype: str, name: str) -> str:
	"""Return path of a doc in a module."""
	...

def reload_doc(module: str, dt: str | None = ..., dn: str | None = ..., force: bool = ..., reset_permissions: bool = ...): # -> list[bool] | bool:
	"""Reload Document from model (`[module]/<doctype>/[name]/[name].json`) files"""
	...

def export_doc(doctype, name, module=...): # -> None:
	"""Write a doc to standard path."""
	...

def get_doctype_module(doctype: str) -> str:
	"""Return **Module Def** name of given doctype."""
	...

def load_doctype_module(doctype, module=..., prefix=..., suffix=...):
	"""Return the module object for given doctype.

	Note: This will return the standard defined module object for the doctype irrespective
	of the `override_doctype_class` hook.
	"""
	...

def get_module_name(doctype: str, module: str, prefix: str = ..., suffix: str = ..., app: str | None = ...): # -> str:
	...

def get_module_app(module: str) -> str:
	...

@site_cache
def get_doctype_app_map(): # -> dict[Any, Any]:
	...

def get_app_publisher(module: str) -> str:
	...

def make_boilerplate(template: str, doc: Document | frappe._dict, opts: dict | frappe._dict = ...): # -> None:
	...

def create_directory_on_app_path(folder_name, app_name): # -> str:
	...

def get_app_level_directory_path(folder_name, app_name): # -> str:
	...

def delete_app_level_folder(folder_name, app_name): # -> None:
	...

def get_module_path(module, *joins): # -> str:
	"""Get the path of the given module name."""
	...

def get_app_path(app_name, *joins): # -> str:
	"""Return path of given app."""
	...

def get_app_source_path(app_name, *joins): # -> str:
	"""Return source path of given app."""
	...

def get_site_path(*joins):
	"""Return path of current site."""
	...

def get_pymodule_path(modulename, *joins): # -> str:
	"""Return path of given Python module name."""
	...

def get_module_list(app_name): # -> list[str] | list[Any]:
	"""Get list of modules for given app via `app/modules.txt`."""
	...

