"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class WorkflowTransition(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		action: DF.Link
		allow_self_approval: DF.Check
		allowed: DF.Link
		condition: DF.Code | None
		next_state: DF.Link
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		send_email_to_creator: DF.Check
		state: DF.Link
		transition_tasks: DF.Link | None
		workflow_builder_id: DF.Data | None
		...


