"""
This type stub file was generated by pyright.
"""

import frappe

supported_events = ...
def get_all_webhooks(): # -> dict[Any, Any]:
	...

def run_webhooks(doc, method): # -> None:
	"""Run webhooks for this method"""
	...

def flush_webhook_execution_queue(): # -> None:
	"""Enqueue all pending webhook executions.

	Each webhook can trigger multiple times on same document or even different instance of same
	document. We assume that last enqueued version of document is the final document for this DB
	transaction.
	"""
	...

