"""
This type stub file was generated by pyright.
"""

class CommunicationEmailMixin:
	"""Mixin class to handle communication mails."""
	def is_email_communication(self):
		...
	
	def get_owner(self): # -> Link | None:
		"""Get owner of the communication docs parent."""
		...
	
	def get_notification_recipient(self): # -> Link | None:
		"""Get notification recipient of the communication docs parent.

		Calls `get_notification_email` on the parent if available; otherwise returns the owner.
		This uses `run_method` so hooks can customize recipients per app/site.
		"""
		...
	
	def get_all_email_addresses(self, exclude_displayname=...):
		"""Get all Email addresses mentioned in the doc along with display name."""
		...
	
	def get_email_with_displayname(self, email_address):
		"""Return email address after adding displayname."""
		...
	
	def mail_recipients(self, is_inbound_mail_communcation=...): # -> list[Any]:
		"""Build to(recipient) list to send an email."""
		...
	
	def get_mail_recipients_with_displayname(self, is_inbound_mail_communcation=...): # -> list[Any]:
		"""Build to(recipient) list to send an email including displayname in email."""
		...
	
	def mail_cc(self, is_inbound_mail_communcation=..., include_sender=...): # -> list[Any]:
		"""Build cc list to send an email.

		* if email copy is requested by sender, then add sender to CC.
		* If this doc is created through inbound mail, then add the notification recipient to CC
		* remove all the thread_notify disabled users.
		* Remove standard users from email list
		"""
		...
	
	def get_mail_cc_with_displayname(self, is_inbound_mail_communcation=..., include_sender=...): # -> list[Any]:
		...
	
	def mail_bcc(self, is_inbound_mail_communcation=...): # -> list[Any]:
		"""
		* Thread_notify check
		* Email unsubscribe list
		* remove standard users.
		"""
		...
	
	def get_mail_bcc_with_displayname(self, is_inbound_mail_communcation=...): # -> list[Any]:
		...
	
	def mail_sender(self):
		...
	
	def mail_sender_fullname(self): # -> dict[str | Any, EmailAccount] | str | dict[Any, EmailAccount] | dict[str, EmailAccount]:
		...
	
	def get_mail_sender_with_displayname(self): # -> str:
		...
	
	def get_content(self, print_format=...): # -> str | Any:
		...
	
	def get_attach_link(self, print_format): # -> str | Any:
		"""Return public link for the attachment via `templates/emails/print_link.html`."""
		...
	
	def get_outgoing_email_account(self): # -> Document | dict[str | Any, EmailAccount] | dict[Any, EmailAccount] | dict[str, EmailAccount] | None:
		...
	
	def get_incoming_email_account(self): # -> EmailAccount | None:
		...
	
	def mail_attachments(self, print_format=..., print_html=..., print_language=...): # -> list[Any]:
		...
	
	def get_unsubscribe_message(self): # -> str:
		...
	
	def exclude_emails_list(self, is_inbound_mail_communcation=..., include_sender=...) -> list:
		"""List of mail id's excluded while sending mail."""
		...
	
	def get_assignees(self): # -> list[str | Any] | list[Any]:
		"""Get owners of the reference document."""
		...
	
	@staticmethod
	def filter_thread_notification_disbled_users(emails): # -> list[Any]:
		"""Filter users based on notifications for email threads setting is disabled."""
		...
	
	@staticmethod
	def filter_disabled_users(emails): # -> list[Any]:
		""" """
		...
	
	def sendmail_input_dict(self, print_html=..., print_format=..., send_me_a_copy=..., print_letterhead=..., is_inbound_mail_communcation=..., print_language=..., raw_html=..., add_css=...) -> dict:
		...
	
	def send_email(self, print_html=..., print_format=..., send_me_a_copy=..., print_letterhead=..., is_inbound_mail_communcation=..., print_language=..., now=..., raw_html=..., add_css=...): # -> None:
		...
	


