"""
This type stub file was generated by pyright.
"""

import frappe
from collections.abc import Iterable
from functools import cached_property
from typing import Any
from frappe.model.document import Document
from frappe.rate_limiter import rate_limit
from frappe.utils.password import get_password_reset_limit

desk_properties = ...
class User(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		active_sessions: DF.Table[UserSessionDisplay]
		allowed_in_mentions: DF.Check
		api_key: DF.Data | None
		api_secret: DF.Password | None
		bio: DF.SmallText | None
		birth_date: DF.Date | None
		block_modules: DF.Table[BlockModule]
		bulk_actions: DF.Check
		bypass_restrict_ip_check_if_2fa_enabled: DF.Check
		code_editor_type: DF.Literal[vscode, vim, emacs]
		dashboard: DF.Check
		default_app: DF.Literal[None]
		default_workspace: DF.Link | None
		defaults: DF.Table[DefaultValue]
		desk_theme: DF.Literal[Light, Dark, Automatic]
		document_follow_frequency: DF.Literal[Hourly, Daily, Weekly]
		document_follow_notify: DF.Check
		email: DF.Data
		email_signature: DF.TextEditor | None
		enabled: DF.Check
		first_name: DF.Data
		follow_assigned_documents: DF.Check
		follow_commented_documents: DF.Check
		follow_created_documents: DF.Check
		follow_liked_documents: DF.Check
		follow_shared_documents: DF.Check
		form_navigation_buttons: DF.Check
		form_sidebar: DF.Check
		full_name: DF.Data | None
		gender: DF.Link | None
		home_settings: DF.Code | None
		interest: DF.SmallText | None
		language: DF.Link | None
		last_active: DF.Datetime | None
		last_ip: DF.ReadOnly | None
		last_known_versions: DF.Text | None
		last_login: DF.ReadOnly | None
		last_name: DF.Data | None
		last_password_reset_date: DF.Date | None
		last_reset_password_key_generated_on: DF.Datetime | None
		list_sidebar: DF.Check
		location: DF.Data | None
		login_after: DF.Int
		login_before: DF.Int
		logout_all_sessions: DF.Check
		middle_name: DF.Data | None
		mobile_no: DF.Data | None
		module_profile: DF.Link | None
		mute_sounds: DF.Check
		new_password: DF.Password | None
		notifications: DF.Check
		onboarding_status: DF.SmallText | None
		phone: DF.Data | None
		redirect_url: DF.SmallText | None
		reset_password_key: DF.Data | None
		restrict_ip: DF.SmallText | None
		role_profile_name: DF.Link | None
		role_profiles: DF.TableMultiSelect[UserRoleProfile]
		roles: DF.Table[HasRole]
		search_bar: DF.Check
		send_me_a_copy: DF.Check
		send_welcome_email: DF.Check
		show_absolute_datetime_in_timeline: DF.Check
		simultaneous_sessions: DF.Int
		social_logins: DF.Table[UserSocialLogin]
		thread_notify: DF.Check
		time_zone: DF.Autocomplete | None
		timeline: DF.Check
		unsubscribed: DF.Check
		user_emails: DF.Table[UserEmail]
		user_image: DF.AttachImage | None
		user_type: DF.Link | None
		username: DF.Data | None
		view_switcher: DF.Check
		...
	__new_password = ...
	@cached_property
	def active_sessions(self): # -> list[Any]:
		...
	
	def __setup__(self): # -> None:
		...
	
	def autoname(self): # -> None:
		"""set name as Email Address"""
		...
	
	def onload(self): # -> None:
		...
	
	def before_insert(self): # -> None:
		...
	
	def after_insert(self): # -> None:
		...
	
	def validate(self): # -> None:
		...
	
	def disable_email_fields_if_user_disabled(self): # -> None:
		...
	
	@frappe.whitelist()
	def populate_role_profile_roles(self): # -> None:
		...
	
	def move_role_profile_name_to_role_profiles(self): # -> None:
		"""This handles old role_profile_name field if programatically set.

		This behaviour will be removed in future versions."""
		...
	
	def sync_role_profile_name(self): # -> None:
		"""Keep deprecated role_profile_name in sync for list view display."""
		...
	
	def validate_allowed_modules(self): # -> None:
		...
	
	def validate_user_image(self): # -> None:
		...
	
	def on_update(self): # -> None:
		...
	
	def has_website_permission(self, ptype, user, verbose=...):
		"""Return True if current user is the session user."""
		...
	
	def clean_name(self): # -> None:
		...
	
	def set_full_name(self): # -> None:
		...
	
	def check_enable_disable(self): # -> None:
		...
	
	def set_new_password(self, new_password=...): # -> None:
		"""Set New Password for user"""
		...
	
	def set_system_user(self): # -> None:
		"""For the standard users like admin and guest, the user type is fixed."""
		...
	
	def set_roles_and_modules_based_on_user_type(self): # -> None:
		...
	
	def has_desk_access(self): # -> Literal[False]:
		"""Return true if any of the set roles has desk access"""
		...
	
	def share_with_self(self): # -> None:
		...
	
	def send_password_notification(self, new_password): # -> None:
		...
	
	@Document.hook
	def validate_reset_password(self): # -> None:
		...
	
	def get_fullname(self): # -> str:
		"""get first_name space last_name"""
		...
	
	def password_reset_mail(self, link): # -> None:
		...
	
	def send_welcome_mail_to_user(self): # -> None:
		...
	
	def send_login_mail(self, subject, template, add_args, now=..., custom_template=...): # -> EmailQueue | None:
		"""send mail with login details"""
		...
	
	def on_trash(self): # -> None:
		...
	
	def before_rename(self, old_name, new_name, merge=...): # -> None:
		...
	
	def validate_rename(self, old_name, new_name): # -> None:
		...
	
	def validate_email_type(self, email): # -> None:
		...
	
	def after_rename(self, old_name, new_name, merge=...): # -> None:
		...
	
	def append_roles(self, *roles): # -> None:
		"""Add roles to user"""
		...
	
	def add_roles(self, *roles): # -> None:
		"""Add roles to user and save"""
		...
	
	def remove_roles(self, *roles): # -> None:
		...
	
	def remove_all_roles_for_guest(self): # -> None:
		...
	
	def remove_disabled_roles(self): # -> None:
		...
	
	def ensure_unique_roles(self): # -> None:
		...
	
	def ensure_unique_role_profiles(self): # -> None:
		...
	
	def validate_username(self): # -> None:
		...
	
	def password_strength_test(self): # -> None:
		"""test password strength"""
		...
	
	def suggest_username(self): # -> str | None:
		...
	
	def username_exists(self, username=...): # -> list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | _dict[Any, Any] | list[Any | None] | None:
		...
	
	def get_blocked_modules(self): # -> list[Data]:
		"""Return list of modules blocked for that user."""
		...
	
	def validate_user_email_inbox(self): # -> None:
		"""check if same email account added in User Emails twice"""
		...
	
	def get_social_login_userid(self, provider: str): # -> Data | None:
		...
	
	def set_social_login_userid(self, provider, userid, username=...): # -> None:
		...
	
	def get_restricted_ip_list(self): # -> list[str] | None:
		...
	
	@classmethod
	def find_by_credentials(cls, user_name: str, password: str, validate_password: bool = ...): # -> None:
		"""Find the user by credentials.

		This is a login utility that needs to check login related system settings while finding the user.
		1. Find user by email ID by default
		2. If allow_login_using_mobile_number is set, you can use mobile number while finding the user.
		3. If allow_login_using_user_name is set, you can use username while finding the user.
		"""
		...
	
	def set_time_zone(self): # -> None:
		...
	
	def get_permission_log_options(self, event=...): # -> dict[str, tuple[str, str, str, str]]:
		...
	
	def check_roles_added(self): # -> None:
		...
	
	def validate_ip_addr(self): # -> None:
		...
	


@frappe.whitelist()
def get_timezones(): # -> dict[str, list[str]]:
	...

@frappe.whitelist()
def get_all_roles(): # -> list[Any]:
	"""return all roles"""
	...

@frappe.whitelist()
def get_perm_info(role: str): # -> list[Any]:
	"""get permission info"""
	...

@frappe.whitelist(allow_guest=True, methods=["POST"])
def update_password(new_password: str, logout_all_sessions: int = ..., key: str | None = ..., old_password: str | None = ...): # -> Any | str | None:
	"""Update password for the current user.

	Args:
	    new_password (str): New password.
	    logout_all_sessions (int, optional): If set to 1, all other sessions will be logged out. Defaults to 0.
	    key (str, optional): Password reset key. Defaults to None.
	    old_password (str, optional): Old password. Defaults to None.
	"""
	...

@frappe.whitelist(allow_guest=True)
def test_password_strength(new_password: str, key: str | None = ..., old_password: str | None = ..., user_data: tuple | None = ...): # -> dict[Any, Any] | _Result | None:
	...

@frappe.whitelist()
def has_email_account(email: str): # -> list[Any]:
	...

@frappe.whitelist(allow_guest=False)
def get_email_awaiting(user: str): # -> list[Any]:
	...

def ask_pass_update(): # -> None:
	...

def reset_user_data(user): # -> tuple[Document, Any]:
	...

@frappe.whitelist(methods=["POST"])
def verify_password(password: str): # -> None:
	...

@frappe.whitelist(allow_guest=True)
def sign_up(email: str, full_name: str, redirect_to: str) -> tuple[int, str]:
	...

@frappe.whitelist(allow_guest=True, methods=["POST"])
@rate_limit(limit=get_password_reset_limit, seconds=60 * 60)
def reset_password(user: str) -> None:
	...

@frappe.whitelist(methods=["POST"])
def change_password(user: str, new_password: str, logout_all_sessions: int = ...) -> None:
	...

@frappe.whitelist()
@frappe.validate_and_sanitize_search_inputs
def user_query(doctype: str, txt: str, searchfield: str, start: int, page_len: int, filters: dict[str, Any]): # -> list[Any]:
	...

def get_total_users(): # -> float:
	"""Return total number of system users."""
	...

def get_system_users(exclude_users: Iterable[str] | str | None = ..., limit: int | None = ...): # -> list[Any]:
	...

def get_active_users(): # -> str:
	"""Return number of system users who logged in, in the last 3 days."""
	...

def get_website_users():
	"""Return total number of website users."""
	...

def get_active_website_users(): # -> str:
	"""Return number of website users who logged in, in the last 3 days."""
	...

def get_permission_query_conditions(user): # -> str:
	...

def has_permission(doc, user): # -> bool:
	...

def notify_admin_access_to_system_manager(login_manager=...): # -> None:
	...

def handle_password_test_fail(feedback: dict): # -> None:
	...

def throttle_user_creation(): # -> None:
	...

@frappe.whitelist()
def get_module_profile(module_profile: str):
	...

def create_contact(user, ignore_links=..., ignore_mandatory=...):
	...

def get_restricted_ip_list(user): # -> list[Any] | None:
	...

@frappe.whitelist(methods=["POST"])
def generate_keys(user: str): # -> dict[str, Data]:
	"""
	generate api key and api secret

	:param user: str
	"""
	...

@frappe.whitelist()
def switch_theme(theme: str): # -> None:
	...

def get_enabled_users(): # -> Any | None:
	...

@frappe.whitelist(methods=["POST"])
def impersonate(user: str, reason: str): # -> None:
	...

@frappe.whitelist()
@rate_limit(limit=10, seconds=60 * 60, methods="POST")
def clear_session(sid_hash: str): # -> None:
	...

