"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

class UserType(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		apply_user_permission_on: DF.Link | None
		custom_select_doctypes: DF.Table[UserSelectDocumentType]
		is_standard: DF.Check
		role: DF.Link | None
		select_doctypes: DF.Table[UserSelectDocumentType]
		user_doctypes: DF.Table[UserDocumentType]
		user_id_field: DF.Literal[None]
		user_type_modules: DF.Table[UserTypeModule]
		...
	def validate(self): # -> None:
		...
	
	def clear_cache(self): # -> None:
		...
	
	def on_update(self): # -> None:
		...
	
	def on_trash(self): # -> None:
		...
	
	def set_modules(self): # -> None:
		...
	
	def validate_role(self): # -> None:
		...
	
	def update_users(self): # -> None:
		...
	
	def update_roles_in_user(self, user): # -> None:
		...
	
	def update_modules_in_user(self, user): # -> None:
		...
	
	def add_role_permissions_for_user_doctypes(self): # -> None:
		...
	
	def add_select_perm_doctypes(self): # -> None:
		...
	
	def prepare_select_perm_doctypes(self, doc, user_doctypes, select_doctypes): # -> None:
		...
	
	def add_role_permissions_for_select_doctypes(self): # -> None:
		...
	
	def add_role_permissions_for_file(self): # -> None:
		...
	
	def remove_permission_for_deleted_doctypes(self): # -> None:
		...
	


def add_role_permissions(doctype, role): # -> Data | Any | None:
	...

def get_non_standard_user_types(): # -> dict[Any, list[Any]]:
	...

@frappe.whitelist()
@frappe.validate_and_sanitize_search_inputs
def get_user_linked_doctypes(doctype: str, txt: str, searchfield: str, start: int, page_len: int, filters: dict | list | str): # -> list[Any]:
	...

@frappe.whitelist()
def get_user_id(parent: str): # -> list[Any]:
	...

def user_linked_with_permission_on_doctype(doc, user): # -> bool:
	...

def apply_permissions_for_non_standard_user_type(doc, method=...): # -> None:
	"""Create user permission for the non standard user type"""
	...

