"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class DocTypeState(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		color: DF.Literal[Blue, Cyan, Gray, Green, "Light Blue", Orange, Pink, Purple, Red, Yellow]
		custom: DF.Check
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		title: DF.Data
		...


