"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class TagLink(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		document_name: DF.DynamicLink | None
		document_type: DF.Link | None
		tag: DF.Link | None
		title: DF.Data | None
		...
	def clear_cache(self): # -> None:
		...
	


def on_doctype_update(): # -> None:
	...

def has_tags(doctype: str): # -> Any | None:
	"""Short circuit checks for tags by first checking if users even uses tags"""
	...

