"""
This type stub file was generated by pyright.
"""

import datetime
from typing import TYPE_CHECKING, TypeVar
from frappe import _dict
from frappe.model.docstatus import DocStatus
from frappe.utils import cached_property
from frappe.model.document import Document

if TYPE_CHECKING:
	...
D = TypeVar("D", bound="Document")
DatetimeTypes = datetime.date | datetime.datetime | datetime.time | datetime.timedelta
max_positive_value = ...
_NOT_IN_CACHE = ...
DOCTYPE_TABLE_FIELDS = ...
TABLE_DOCTYPES_FOR_DOCTYPE = ...
TABLE_DOCTYPES_FOR_CHILD_TABLES = ...
DOCTYPES_FOR_DOCTYPE = ...
def get_controller(doctype):
	"""Return the locally cached **class** object of the given DocType.

	For `custom` type, return `frappe.model.document.Document`.

	:param doctype: DocType name as string.
	"""
	...

def import_controller(doctype): # -> type[NestedSet] | type[Document] | type[BaseDocument] | Any:
	...

class BaseDocument:
	def __init__(self, d) -> None:
		...
	
	def __json__(self): # -> dict[Any, Any]:
		...
	
	@cached_property
	def meta(self): # -> _Meta:
		...
	
	@cached_property
	def permitted_fieldnames(self) -> set[str]:
		...
	
	def __getstate__(self): # -> dict[str, Any]:
		"""Return a copy of `__dict__` excluding unpicklable values like `meta`.

		Called when pickling.
		More info: https://docs.python.org/3/library/pickle.html#handling-stateful-objects
		"""
		...
	
	def remove_unpicklable_values(self, state): # -> None:
		"""Remove unpicklable values before pickling"""
		...
	
	def update(self, d): # -> Self:
		"""Update multiple fields of a doctype using a dictionary of key-value pairs.

		Example:
		        doc.update({
		                "user": "admin",
		                "balance": 42000
		        })

		Developer Note: Logic in the set method is re-implemented here for perf
		"""
		...
	
	def update_if_missing(self, d): # -> None:
		"""Set default values for fields without existing values"""
		...
	
	def get_db_value(self, key): # -> list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | _dict[Any, Any] | list[Any | None] | None:
		...
	
	def get(self, key, filters=..., limit=..., default=...): # -> list[Any] | tuple[Any, ...] | Any | None:
		...
	
	def getone(self, key, filters=...): # -> Any:
		...
	
	def set(self, key, value, as_value=...): # -> None:
		...
	
	def delete_key(self, key): # -> None:
		...
	
	def append(self, key: str, value: D | dict | None = ..., position: int = ...) -> D:
		"""Append an item to a child table.

		Example:
		        doc.append("childtable", {
		                "child_table_field": "value",
		                "child_table_int_field": 0,
		                ...
		        })
		"""
		...
	
	@property
	def parent_doc(self): # -> BaseDocument | None:
		...
	
	@parent_doc.setter
	def parent_doc(self, value): # -> None:
		...
	
	@parent_doc.deleter
	def parent_doc(self): # -> None:
		...
	
	def extend(self, key, value): # -> None:
		...
	
	def remove(self, doc): # -> None:
		"""Usage: from the parent doc, pass the child table doc to remove that child doc from the
		child table, thus removing it from the parent doc
		"""
		...
	
	def get_virtual_field_value(self, df): # -> Any | None:
		...
	
	def get_valid_dict(self, sanitize=..., convert_dates_to_str=..., ignore_nulls=..., ignore_virtual=...) -> _dict:
		...
	
	def init_child_tables(self): # -> None:
		"""
		This is needed so that one can loop over child table properties
		without worrying about whether or not they have values
		"""
		...
	
	def init_valid_columns(self): # -> None:
		...
	
	def get_valid_columns(self) -> list[str]:
		...
	
	def is_new(self) -> bool:
		...
	
	@property
	def docstatus(self) -> DocStatus:
		...
	
	@docstatus.setter
	def docstatus(self, value) -> None:
		...
	
	def as_dict(self, no_nulls=..., no_default_fields=..., convert_dates_to_str=..., no_child_table_fields=..., no_private_properties=..., *, ignore_computed_child_tables=...) -> dict:
		...
	
	def as_json(self): # -> str:
		...
	
	def get_table_field_doctype(self, fieldname): # -> None:
		...
	
	def get_parentfield_of_doctype(self, doctype): # -> None:
		...
	
	def db_insert(self, ignore_if_duplicate=...): # -> None:
		"""INSERT the document (with valid columns) in the database.

		args:
		        ignore_if_duplicate: ignore primary key collision
		                                        at database level (postgres)
		                                        in python (mariadb)
		"""
		...
	
	def db_update(self): # -> None:
		...
	
	def db_update_all(self): # -> None:
		"""Raw update parent + children
		DOES NOT VALIDATE AND CALL TRIGGERS"""
		...
	
	def show_unique_validation_message(self, e):
		...
	
	def get_field_name_by_key_name(self, key_name): # -> None:
		"""MariaDB stores a mapping between `key_name` and `column_name`.
		Return the `column_name` associated with the `key_name` passed.

		Args:
		        key_name (str): The name of the database index.

		Raises:
		        IndexError: If the key is not found in the table.

		Return:
		        str: The column name associated with the key.
		"""
		...
	
	def get_label_from_fieldname(self, fieldname): # -> str | None:
		"""Return the associated label for fieldname.

		Args:
		        fieldname (str): The fieldname in the DocType to use to pull the label.

		Return:
		        str: The label associated with the fieldname, if found, otherwise `None`.
		"""
		...
	
	def update_modified(self): # -> None:
		"""Update modified timestamp"""
		...
	
	def get_invalid_links(self, is_submittable=..., link_value_cache=...):
		"""Return list of invalid links and also update fetch values if not set.

		Args:
			is_submittable: Whether the parent document is submittable
			link_value_cache: Cache of prefetched link values for bulk optimization
		"""
		...
	
	def set_fetch_from_value(self, doctype, df, values): # -> None:
		...
	
	def throw_length_exceeded_error(self, df, max_length, value): # -> None:
		...
	
	def get_password(self, fieldname=..., raise_exception=...): # -> list[Any] | tuple[Any, ...] | Any | str | None:
		...
	
	def is_dummy_password(self, pwd): # -> bool:
		...
	
	def precision(self, fieldname, parentfield=...) -> int | None:
		"""Return float precision for a particular field (or get global default).

		:param fieldname: Fieldname for which precision is required.
		:param parentfield: If fieldname is in child table."""
		...
	
	def get_formatted(self, fieldname, doc=..., currency=..., absolute_value=..., translated=..., format=...):
		...
	
	def is_print_hide(self, fieldname, df=..., for_print=...): # -> Literal[True, 0] | None:
		"""Return True if fieldname is to be hidden for print.

		Print Hide can be set via the Print Format Builder or in the controller as a list
		of hidden fields. Example

		        class MyDoc(Document):
		                def __setup__(self):
		                        self.print_hide = ["field1", "field2"]

		:param fieldname: Fieldname to be checked if hidden.
		"""
		...
	
	def in_format_data(self, fieldname): # -> bool:
		"""Return True if shown via Print Format::`format_data` property.

		Called from within standard print format."""
		...
	
	def reset_values_if_no_permlevel_access(self, has_access_to, high_permlevel_fields, mask_fields=...): # -> None:
		"""If the user does not have permissions at permlevel > 0, then reset the values to original / default"""
		...
	
	def get_value(self, fieldname): # -> float | int | str | date | datetime | timedelta | None:
		...
	
	def cast(self, value, df): # -> float | int | str | date | datetime | timedelta | None:
		...
	


CACHED_PROPERTIES = ...
UNPICKLABLE_KEYS = ...
RESERVED_KEYWORDS = ...
