"""
This type stub file was generated by pyright.
"""

"""
Create a new document with defaults set
"""
def get_new_doc(doctype, parent_doc=..., parentfield=..., as_dict=...): # -> Any | Document:
	...

def make_new_doc(doctype): # -> _dict[Any, Any]:
	...

def set_user_and_static_default_values(doc): # -> None:
	...

def get_user_default_value(df, defaults, doctype_user_permissions, allowed_records, default_doc): # -> None:
	...

def get_static_default_value(df, doctype_user_permissions, allowed_records): # -> str | None:
	...

def validate_value_via_user_permissions(df, doctype_user_permissions, allowed_records, user_default=...): # -> bool:
	...

def set_dynamic_default_values(doc, parent_doc, parentfield): # -> None:
	...

def user_permissions_exist(df, doctype_user_permissions): # -> Literal[False]:
	...

def get_default_based_on_another_field(df, user_permissions, parent_doc): # -> list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | _dict[Any, Any] | list[Any | None] | None:
	...

