"""
This type stub file was generated by pyright.
"""

from functools import cached_property
from frappe.types import FilterSignature, FilterTuple, Filters

"""build query for doclistview and return results"""
LOCATE_PATTERN = ...
LOCATE_CAST_PATTERN = ...
FUNC_IFNULL_PATTERN = ...
CAST_VARCHAR_PATTERN = ...
ORDER_BY_PATTERN = ...
SUB_QUERY_PATTERN = ...
IS_QUERY_PATTERN = ...
IS_QUERY_PREDICATE_PATTERN = ...
FIELD_QUOTE_PATTERN = ...
FIELD_COMMA_PATTERN = ...
STRICT_FIELD_PATTERN = ...
STRICT_UNION_PATTERN = ...
ORDER_GROUP_PATTERN = ...
SPECIAL_FIELD_CHARS = ...
class DatabaseQuery:
	def __init__(self, doctype, user=...) -> None:
		...
	
	@cached_property
	def doctype_meta(self):
		...
	
	def get_meta(self, doctype: str):
		...
	
	@property
	def query_tables(self): # -> list[str]:
		...
	
	def execute(self, fields=..., filters: FilterSignature | str | None = ..., or_filters: FilterSignature | None = ..., docstatus=..., group_by=..., order_by=..., limit_start=..., limit_page_length=..., as_list=..., with_childnames=..., debug=..., ignore_permissions=..., user=..., with_comment_count=..., join=..., distinct=..., start=..., page_length=..., limit=..., ignore_ifnull=..., save_user_settings=..., save_user_settings_fields=..., update=..., user_settings=..., reference_doctype=..., run=..., strict=..., pluck=..., ignore_ddl=..., *, parent_doctype=...) -> list:
		...
	
	def mask_fields(self, result): # -> list[Any]:
		"""Mask fields in the result based on the doctype's masked fields"""
		...
	
	def get_masked_fields(self):
		"""Get masked fields for the doctype"""
		...
	
	def build_and_run(self): # -> list[Any] | str | tuple[()] | Generator[Any | _dict[Incomplete | str | Any, Any] | list[Any], Any, None] | list[_dict[Any, Any]] | list[list[Any]] | tuple[tuple[Any, ...]] | None:
		...
	
	def prepare_args(self): # -> _dict[Any, Any]:
		...
	
	def prepare_select_args(self, args):
		...
	
	def parse_args(self): # -> None:
		"""Convert fields and filters from strings to list, dicts."""
		...
	
	def sanitize_fields(self): # -> None:
		"""
		regex : ^.*[,();].*
		purpose : The regex will look for malicious patterns like `,`, '(', ')', '@', ;' in each
		                field which may leads to sql injection.
		example :
		        field = "`DocType`.`issingle`, version()"
		As field contains `,` and mysql function `version()`, with the help of regex
		the system will filter out this field.
		"""
		...
	
	def extract_tables(self): # -> None:
		"""extract tables from fields"""
		...
	
	def append_table(self, table_name): # -> None:
		...
	
	def append_link_table(self, doctype, fieldname): # -> _dict[Any, str]:
		...
	
	def check_read_permission(self, doctype: str, parent_doctype: str | None = ...): # -> None:
		...
	
	def set_field_tables(self): # -> None:
		"""If there are more than one table, the fieldname must not be ambiguous.
		If the fieldname is not explicitly mentioned, set the default table"""
		...
	
	def cast_name_fields(self): # -> None:
		...
	
	def get_table_columns(self): # -> list[str] | None:
		...
	
	def set_optional_columns(self): # -> None:
		"""Removes optional columns like `_user_tags`, `_comments` etc. if not in table"""
		...
	
	def build_conditions(self): # -> None:
		...
	
	def build_filter_conditions(self, filters: Filters, conditions: list, ignore_permissions=...): # -> None:
		"""build conditions from user filters"""
		...
	
	def remove_field(self, idx: int): # -> None:
		...
	
	def apply_fieldlevel_read_permissions(self): # -> None:
		"""Apply fieldlevel read permissions to the query

		Note: Does not apply to `frappe.model.core_doctype_list`

		Remove fields that user is not allowed to read. If `fields=["*"]` is passed, only permitted fields will
		be returned.

		Example:
		        - User has read permission only on `title` for DocType `Note`
		        - Query: fields=["*"]
		        - Result: fields=["title", ...] // will also include Frappe's meta field like `name`, `owner`, etc.
		"""
		...
	
	def prepare_filter_condition(self, ft: FilterTuple) -> str:
		"""Return a filter condition in the format:

		ifnull(`tabDocType`.`fieldname`, fallback) operator "value"
		"""
		...
	
	def build_match_conditions(self, as_condition=...) -> str | list:
		"""add match conditions if applicable"""
		...
	
	def get_share_condition(self): # -> str:
		...
	
	def add_user_permissions(self, user_permissions): # -> None:
		...
	
	def get_permission_query_conditions(self) -> str:
		...
	
	def set_order_by(self, args): # -> None:
		...
	
	def validate_order_by_and_group_by(self, parameters: str): # -> None:
		"""Check order by, group by so that atleast one column is selected and does not have subquery"""
		...
	
	def add_limit(self): # -> str:
		...
	
	def add_comment_count(self, result): # -> None:
		...
	
	def update_user_settings(self): # -> None:
		...
	


def cast_name(column: str) -> str:
	"""Casts name field to varchar for postgres

	Handles majorly 4 cases:
	1. locate
	2. strpos
	3. ifnull
	4. coalesce

	Uses regex substitution.

	Example:
	input - "ifnull(`tabBlog Post`.`name`, '')=''"
	output - "ifnull(cast(`tabBlog Post`.`name` as varchar), '')=''" """
	...

def get_order_by(doctype, meta): # -> str:
	...

def has_any_user_permission_for_doctype(doctype, user, applicable_for): # -> bool:
	...

def get_between_date_filter(value, df=...): # -> str:
	"""Handle datetime filter bounds for between filter values.

	If date is passed but fieldtype is datetime then
	        from part is converted to start of day and to part is converted to end of day.
	If any of filter part (to or from) are missing then:
	        start or end of current day is assumed as fallback.
	If fieldtypes match with filter values then:
	        no change is applied.
	"""
	...

def get_additional_filter_field(additional_filters_config, f, value): # -> _dict[Any, Any]:
	...

def get_date_range(operator: str, value: str): # -> tuple[datetime, datetime] | None:
	...

def requires_owner_constraint(role_permissions): # -> Literal[True] | None:
	"""Return True if "select" or "read" isn't available without being creator."""
	...

def wrap_grave_quotes(table: str) -> str:
	...

def is_plain_field(field: str) -> bool:
	...

def in_function(substr: str, field: str) -> bool:
	...

def strip_alias(field: str) -> str:
	...

