"""
This type stub file was generated by pyright.
"""

from typing import Any

def delete_doc(doctype: str | None = ..., name: str | int | list[str | int] | None = ..., force: int | bool = ..., ignore_doctypes: list[str] | None = ..., for_reload: bool = ..., ignore_permissions: bool = ..., flags: dict[str, Any] | None = ..., ignore_on_trash: bool = ..., ignore_missing: bool = ..., delete_permanently: bool = ...) -> bool | None:
	"""
	Deletes a document and validates if it is not submitted and not linked in a live record.

	Args:
		doctype (str, optional): The document type to delete. If not provided,
			retrieved from frappe.form_dict.get("dt"). Defaults to None.
		name (str | int | list, optional): The name/ID of the document(s) to delete.
			Can be a single name or a list of names. If not provided,
			retrieved from frappe.form_dict.get("dn"). Defaults to None.
		force (bool, optional): When True, bypasses link existence checks and allows
			deletion of documents that are linked to other records. Also allows
			deletion of standard DocTypes. Defaults to 0 (False).
		ignore_doctypes (list, optional): A list of child doctypes to ignore when
			deleting child table records associated with the document. Defaults to None.
		for_reload (bool, optional): When True, indicates the deletion is for reloading
			purposes (like during doctype updates). Skips certain validations like
			permissions and on_trash methods, and automatically sets delete_permanently=True.
			Defaults to False.
		ignore_permissions (bool, optional): When True, bypasses permission checks
			during deletion. Useful for system operations. Defaults to False.
		flags (dict, optional): Additional flags to set on the document during the
			deletion process. These flags affect document behavior during deletion.
			Defaults to None.
		ignore_on_trash (bool, optional): When True, skips calling the document's
			on_trash method, which typically contains cleanup logic. Defaults to False.
		ignore_missing (bool, optional): When True, doesn't raise an error if the
			document doesn't exist and returns False. When False, raises
			frappe.DoesNotExistError if document is missing. Defaults to True.
		delete_permanently (bool, optional): When True, permanently deletes the document
			without adding it to the "Deleted Document" table for recovery purposes.
			When False, the document is soft-deleted and can be recovered. Defaults to False.

	Raises:
		frappe.DoesNotExistError: When document doesn't exist and ignore_missing=False.
		frappe.LinkExistsError: When document is linked to other records and force=False.
		frappe.PermissionError: When user doesn't have delete permissions and ignore_permissions=False.
		frappe.ValidationError: When trying to delete a submitted document.
		frappe.QueryTimeoutError: When document is locked by another user.

	Returns:
		bool: False if document doesn't exist and ignore_missing=True, otherwise None.
	"""
	...

def add_to_deleted_document(doc): # -> None:
	"""Add this document to Deleted Document table. Called after delete"""
	...

def update_naming_series(doc): # -> None:
	...

def delete_from_table(doctype: str, name: str, ignore_doctypes: list[str], doc): # -> None:
	...

def update_flags(doc, flags=..., ignore_permissions=...): # -> None:
	...

def check_permission_and_not_submitted(doc): # -> None:
	...

def get_linked_docs(doc, method=...) -> list[dict]:
	"""
	Return a list of documents that are statically linked to the given document.
	"""
	...

def check_if_doc_is_linked(doc, method=...): # -> None:
	"""
	Raises exception if the given document is linked in another record.
	"""
	...

def get_dynamic_linked_docs(doc, method=...) -> list[dict]:
	"""
	Return a list of documents that are dynamically linked to the given document.
	"""
	...

def check_if_doc_is_dynamically_linked(doc, method=...): # -> None:
	"""Raise `frappe.LinkExistsError` if the document is dynamically linked"""
	...

def raise_link_exists_exception(doc, reference_doctype, reference_docname, row=...): # -> None:
	...

def delete_dynamic_links(doctype, name): # -> None:
	...

def delete_references(doctype, reference_doctype, reference_name, reference_doctype_field=..., reference_name_field=...): # -> None:
	...

def clear_references(doctype, reference_doctype, reference_name, reference_doctype_field=..., reference_name_field=...): # -> None:
	...

def clear_timeline_references(link_doctype, link_name): # -> None:
	...

def insert_feed(doc): # -> None:
	...

def delete_controllers(doctype, module): # -> None:
	"""
	Delete controller code in the doctype folder
	"""
	...

