"""
This type stub file was generated by pyright.
"""

import frappe
from collections.abc import Generator, Iterable
from types import MappingProxyType
from typing import Any, ClassVar, Self, TYPE_CHECKING, overload, override
from frappe.model.base_document import BaseDocument, D
from frappe.model.utils import simple_singledispatch
from frappe.types import DF
from frappe.types.filter import FilterSignature
from frappe.core.doctype.docfield.docfield import DocField

if TYPE_CHECKING:
	...
DOCUMENT_LOCK_EXPIRY = ...
DOCUMENT_LOCK_SOFT_EXPIRY = ...
_POSITIONAL_PARAM_KINDS = ...
_SingleDocument = "Document"
_NewDocument = "Document"
@overload
def get_doc(document: Document, /) -> Document:
	...

@overload
def get_doc(doctype: str, /) -> _SingleDocument:
	"""Retrieve Single DocType from DB, doctype must be positional argument."""
	...

@overload
def get_doc(doctype: str, name: str, /, *, for_update: bool | None = ..., check_permission: str | bool | None = ...) -> Document:
	"""Retrieve DocType from DB, doctype and name must be positional argument."""
	...

@overload
def get_doc(**kwargs: dict) -> _NewDocument:
	"""Initialize document from kwargs.
	Not recommended. Use `frappe.new_doc` instead."""
	...

@overload
def get_doc(documentdict: dict) -> _NewDocument:
	"""Create document from dict.
	Not recommended. Use `frappe.new_doc` instead."""
	...

@simple_singledispatch
def get_doc(*args, **kwargs) -> Document:
	"""Return a `frappe.model.Document` object.

	:param arg1: Document dict or DocType name.
	:param arg2: [optional] document name.
	:param for_update: [optional] select document for update.

	There are multiple ways to call `get_doc`

	        # will fetch the latest user object (with child table) from the database
	        user = get_doc("User", "test@example.com")

	        # create a new object
	        user = get_doc({
	                "doctype":"User"
	                "email_id": "test@example.com",
	                "roles: [
	                        {"role": "System Manager"}
	                ]
	        })

	        # create new object with keyword arguments
	        user = get_doc(doctype='User', email_id='test@example.com')

	        # select a document for update
	        user = get_doc("User", "test@example.com", for_update=True)
	"""
	...

@get_doc.register(str)
def get_doc_str(doctype: str, name: str | None = ..., **kwargs) -> Document:
	...

@get_doc.register(MappingProxyType)
def get_doc_from_mapping_proxy(data: MappingProxyType, **kwargs) -> Document:
	...

@get_doc.register(dict)
def get_doc_from_dict(data: dict[str, Any], **kwargs) -> Document:
	...

def get_lazy_doc(doctype: str, name: str, *, for_update=..., check_permission: str | bool | None = ...) -> Document:
	...

def get_docs(doctype: str, filters: dict | None = ..., *, chunk_size: int = ..., limit: int | None = ..., limit_start: int = ..., order_by: str = ..., as_iterator: bool = ..., for_update: bool = ..., distinct: bool = ...) -> list[Document] | Generator[Document]:
	"""Fetch fully instantiated Document objects from the database.

	Returns a list of Documents by default. Pass `as_iterator=True` to get
	a chunked generator that yields a list of Documents per chunk to reduce memory usage.

	:param doctype: DocType of the records to fetch.
	:param filters: Dict or list of filters to apply.
	:param chunk_size: Number of records to fetch in each chunk if using `as_iterator`.
	:param limit: Maximum total number of records to fetch.
	:param limit_start: Start results at record #. Default 0.
	:param order_by: Order By string, e.g. `creation desc`.
	:param as_iterator: If True, returns a iterator yielding Documents.
	:param for_update: If True, locks the fetched rows for update.
	:param distinct: If True, return distinct rows.


	Note: Chunk size controls memory usage vs # of queries tradeoff. Using chunk size larger than
	10,000 is not advisable.
	"""
	...

def get_doc_permission_check(doc: Document, check_permission: str | bool | None = ...) -> Document:
	"""
	Checks permissions for the given document, if specified.

	:param doc: The document to check permissions for.
	:param check_permission: The permission to check for, default is "read" if truthy.
	:return: The document with permissions checked.
	"""
	...

class DocsCollection[T]:
	"""APIs to manage collections of documents."""
	__slots__ = ...
	def __set_name__(self, owner: type, name: str) -> None:
		...
	
	def __get__(self, instance, owner: type | None = ...) -> DocsCollection[T]:
		...
	
	def get(self, name: str | int | None = ..., *, cached: bool = ..., lazy: bool = ..., for_update: bool = ..., check_permission: str | bool | None = ...) -> T:
		"""Fetch a single document of this DocType by name (or filter dict)."""
		...
	
	def last(self, filters: FilterSignature | None = ..., order_by: str = ..., *, for_update: bool = ...) -> T:
		"""Return the most recently created document, optionally filtered."""
		...
	
	def filter(self, filters: dict | None = ..., *, chunk_size: int = ..., limit: int | None = ..., limit_start: int = ..., order_by: str = ..., as_iterator: bool = ..., for_update: bool = ..., distinct: bool = ...) -> list[T] | Generator[T]:
		"""Return all documents matching `filters`."""
		...
	
	def new(self, **kwargs) -> T:
		"""Create a new (unsaved) document with the given field values."""
		...
	


class Document(BaseDocument):
	"""All controllers inherit from `Document`."""
	_DOCTYPE_NAME: ClassVar[str | None] = ...
	docs: DocsCollection[Self] = ...
	doctype: DF.Data
	name: DF.Data | None
	flags: frappe._dict[str, Any]
	owner: DF.Link
	creation: DF.Datetime
	modified: DF.Datetime
	modified_by: DF.Link
	idx: DF.Int
	def __init__(self, *args, **kwargs) -> None:
		"""Constructor.

		:param arg1: DocType name as string, document **dict**, or DocRef object
		:param arg2: Document name, if `arg1` is DocType name.

		If DocType name and document name are passed, the object will load
		all values (including child documents) from the database.
		"""
		...
	
	@property
	def is_locked(self): # -> bool:
		...
	
	def load_from_db(self) -> Self:
		"""Load document and children from database and create properties
		from fields"""
		...
	
	def mask_fields(self): # -> None:
		...
	
	def load_children_from_db(self): # -> Self:
		...
	
	def reload(self) -> Self:
		"""Reload document from database"""
		...
	
	def get_latest(self): # -> Document | None:
		...
	
	def check_permission(self, permtype=..., permlevel=...): # -> None:
		"""Raise `frappe.PermissionError` if not permitted"""
		...
	
	def has_permission(self, permtype=..., *, debug=..., user=...) -> bool:
		"""
		Call `frappe.permissions.has_permission` if `ignore_permissions` flag isn't truthy

		:param permtype: `read`, `write`, `submit`, `cancel`, `delete`, etc.
		"""
		...
	
	def raise_no_permission_to(self, perm_type):
		"""Raise `frappe.PermissionError`."""
		...
	
	def insert(self, ignore_permissions=..., ignore_links=..., ignore_if_duplicate=..., ignore_mandatory=..., set_name=..., set_child_names=...) -> Self:
		"""Insert the document in the database (as a new document).
		This will check for user permissions and execute `before_insert`,
		`validate`, `on_update`, `after_insert` methods if they are written.

		:param ignore_permissions: Do not check permissions if True.
		:param ignore_links: Do not check validity of links if True.
		:param ignore_if_duplicate: Do not raise error if a duplicate entry exists.
		:param ignore_mandatory: Do not check missing mandatory fields if True.
		:param set_name: Name to set for the document, if valid.
		:param set_child_names: Whether to set names for the child documents.
		"""
		...
	
	def check_if_locked(self): # -> None:
		...
	
	def save(self, *args, **kwargs) -> Self:
		"""Wrapper for _save"""
		...
	
	def validate_amended_from(self): # -> None:
		...
	
	def copy_attachments_from_amended_from(self): # -> None:
		"""Copy attachments from `amended_from`"""
		...
	
	def update_children(self): # -> None:
		"""update child tables"""
		...
	
	def update_child_table(self, fieldname: str, df: DocField | None = ...): # -> None:
		"""sync child table for given fieldname"""
		...
	
	def reset_computed_child_tables(self): # -> None:
		"""Reset computed child tables so that they are reloaded next time"""
		...
	
	def get_doc_before_save(self) -> Self:
		...
	
	def has_value_changed(self, fieldname): # -> bool | Any:
		"""Return True if value has changed before and after saving."""
		...
	
	def get_value_before_save(self, fieldname): # -> list[Any] | tuple[Any, ...] | Any | None:
		"""Returns value of a field before saving

		Note: This function only works in save context like doc.save, doc.submit.
		"""
		...
	
	def set_new_name(self, force=..., set_name=..., set_child_names=...): # -> None:
		"""Calls `frappe.naming.set_new_name` for parent and child docs."""
		...
	
	def get_title(self): # -> list[Any] | tuple[Any, ...] | Any | Literal['']:
		"""Get the document title based on title_field or `title` or `name`"""
		...
	
	def set_title_field(self): # -> None:
		"""Set title field based on template"""
		...
	
	def update_single(self, d): # -> None:
		"""Updates values for Single type Document in `tabSingles`."""
		...
	
	def set_user_and_timestamp(self): # -> None:
		...
	
	def set_docstatus(self): # -> None:
		...
	
	def validate_workflow(self): # -> None:
		"""Validate if the workflow transition is valid"""
		...
	
	def validate_set_only_once(self): # -> Literal[False]:
		"""Validate that fields are not changed if not in insert"""
		...
	
	def is_child_table_same(self, fieldname): # -> bool:
		"""Validate child table is same as original table before saving"""
		...
	
	def apply_fieldlevel_read_permissions(self): # -> None:
		"""Remove values the user is not allowed to read, and mask fields per mask permissions."""
		...
	
	def validate_higher_perm_levels(self): # -> None:
		"""If the user does not have permissions at permlevel > 0, then reset the values to original / default"""
		...
	
	def get_permlevel_access(self, permission_type=...): # -> list[Any]:
		...
	
	def has_permlevel_access_to(self, fieldname, df=..., permission_type=...): # -> bool:
		...
	
	def get_permissions(self): # -> Table:
		...
	
	def check_if_latest(self): # -> None:
		"""Checks if `modified` timestamp provided by document being updated is same as the
		`modified` timestamp in the database. If there is a different, the document has been
		updated in the database after the current copy was read. Will throw an error if
		timestamps don't match.

		Will also validate document transitions (Save > Submit > Cancel) calling
		`self.check_docstatus_transition`."""
		...
	
	def check_docstatus_transition(self, from_docstatus): # -> None:
		"""Ensures valid `docstatus` transition.
		Valid transitions are (number in brackets is `docstatus`):

		- Save (0) > Save (0)
		- Save (0) > Submit (1)
		- Submit (1) > Submit (1)
		- Submit (1) > Cancel (2)

		"""
		...
	
	def set_parent_in_children(self): # -> None:
		"""Updates `parent` and `parenttype` property in all children."""
		...
	
	def set_name_in_children(self): # -> None:
		...
	
	def validate_update_after_submit(self): # -> None:
		...
	
	def get_all_children(self, parenttype=..., *, include_computed=...) -> list[Document]:
		"""
		Return all child documents from **Table** type fields in a list.
		Excludes computed tables by default, unless `include_computed` is set to True.
		"""
		...
	
	def run_method(self, method: str, *args, **kwargs):
		"""run standard triggers, plus those in hooks"""
		...
	
	def run_trigger(self, method, *args, **kwargs):
		...
	
	def run_notifications(self, method): # -> None:
		"""Run notifications for this method"""
		...
	
	@frappe.whitelist()
	def submit(self): # -> Self:
		"""Submit the document. Sets `docstatus` = 1, then saves."""
		...
	
	@frappe.whitelist()
	def cancel(self): # -> Self:
		"""Cancel the document. Sets `docstatus` = 2, then saves."""
		...
	
	@frappe.whitelist()
	def discard(self): # -> None:
		"""Discard the draft document. Sets `docstatus` = 2 with db_set."""
		...
	
	@frappe.whitelist()
	def rename(self, name: str | int, merge: bool = ..., force: bool = ..., validate_rename: bool = ...): # -> None:
		"""Rename the document to `name`. This transforms the current object."""
		...
	
	def delete(self, ignore_permissions=..., force=..., *, delete_permanently=...): # -> bool | None:
		"""Delete document."""
		...
	
	def run_before_save_methods(self): # -> None:
		"""Run standard methods before	`INSERT` or `UPDATE`. Standard Methods are:

		- `validate`, `before_save` for **Save**.
		- `validate`, `before_submit` for **Submit**.
		- `before_cancel` for **Cancel**
		- `before_update_after_submit` for **Update after Submit**

		Will also update title_field if set"""
		...
	
	def load_doc_before_save(self, *, raise_exception: bool = ...): # -> None:
		"""load existing document from db before saving"""
		...
	
	def run_post_save_methods(self): # -> None:
		"""Run standard methods after `INSERT` or `UPDATE`. Standard Methods are:

		- `on_update` for **Save**.
		- `on_update`, `on_submit` for **Submit**.
		- `on_cancel` for **Cancel**
		- `update_after_submit` for **Update after Submit**"""
		...
	
	def clear_cache(self): # -> None:
		...
	
	def reset_seen(self): # -> None:
		"""Clear _seen property and set current user as seen"""
		...
	
	def notify_update(self): # -> None:
		"""Publish realtime that the current document is modified"""
		...
	
	def db_set(self, fieldname, value=..., update_modified=..., notify=..., commit=...): # -> None:
		"""Set a value in the document object, update the timestamp and update the database.

		WARNING: This method does not trigger controller validations and should
		be used very carefully.

		:param fieldname: fieldname of the property to be updated, or a {"field":"value"} dictionary
		:param value: value of the property to be updated
		:param update_modified: default True. updates the `modified` and `modified_by` properties
		:param notify: default False. run doc.notify_update() to send updates via socketio
		:param commit: default False. run frappe.db.commit()
		"""
		...
	
	def db_get(self, fieldname): # -> list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | _dict[Any, Any] | list[Any | None] | None:
		"""get database value for this fieldname"""
		...
	
	def check_no_back_links_exist(self): # -> None:
		"""Check if document links to any active document before Cancel."""
		...
	
	def save_version(self): # -> None:
		"""Save version info"""
		...
	
	@staticmethod
	def hook(f): # -> Callable[..., Any]:
		"""Decorator: Make method `hookable` (i.e. extensible by another app).

		Note: If each hooked method returns a value (dict), then all returns are
		collated in one dict and returned. Ideally, don't return values in hookable
		methods, set properties in the document."""
		...
	
	def is_whitelisted(self, method_name): # -> None:
		...
	
	def validate_value(self, fieldname, condition, val2, doc=..., raise_exception=...): # -> None:
		"""Check that value of fieldname should be 'condition' val2
		else throw Exception."""
		...
	
	def validate_table_has_rows(self, parentfield, raise_exception=...): # -> None:
		"""Raise exception if Table field is empty."""
		...
	
	def round_floats_in(self, doc, fieldnames=..., do_not_round_fields=...): # -> None:
		"""Round floats for all `Currency`, `Float`, `Percent` fields for the given doc.

		:param doc: Document whose numeric properties are to be rounded.
		:param fieldnames: [Optional] List of fields to be rounded."""
		...
	
	def get_url(self): # -> str:
		"""Return Desk URL for this document."""
		...
	
	@frappe.whitelist()
	def add_comment(self, comment_type: str = ..., text: str | None = ..., comment_email: str | None = ..., comment_by: str | None = ...): # -> _NewDocument:
		"""Add a comment to this document.

		:param comment_type: e.g. `Comment`. See Communication for more info."""
		...
	
	def add_seen(self, user=...): # -> None:
		"""add the given/current user to list of users who have seen this document (_seen)"""
		...
	
	def add_viewed(self, user=..., force=..., unique_views=...): # -> _NewDocument | None:
		"""Add a view log for the current document"""
		...
	
	def log_error(self, title=..., message=..., *, defer_insert=...): # -> _NewDocument | None:
		"""Helper function to create an Error Log"""
		...
	
	def get_signature(self): # -> str:
		"""Return signature (hash) for private URL."""
		...
	
	def get_document_share_key(self, expires_on=..., no_expiry=...):
		...
	
	def get_liked_by(self): # -> Any | list[Any]:
		...
	
	def set_onload(self, key, value): # -> None:
		...
	
	def get_onload(self, key=...): # -> Any | _dict[Any, Any] | list[Any] | tuple[Any, ...]:
		...
	
	def queue_action(self, action, **kwargs): # -> Job | Any:
		"""Run an action in background. If the action has an inner function,
		like _submit for submit, it will call that instead"""
		...
	
	def lock(self, timeout=...): # -> None:
		"""Creates a lock file for the given document. If timeout is set,
		it will retry every 1 second for acquiring the lock again

		:param timeout: Timeout in seconds, default 0"""
		...
	
	def unlock(self): # -> None:
		"""Delete the lock file for this document"""
		...
	
	def validate_from_to_dates(self, from_date_field: str, to_date_field: str) -> None:
		"""Validate that the value of `from_date_field` is not later than the value of `to_date_field`."""
		...
	
	def get_assigned_users(self): # -> set[Any]:
		...
	
	def add_tag(self, tag): # -> None:
		"""Add a Tag to this document"""
		...
	
	def remove_tag(self, tag): # -> None:
		"""Remove a Tag to this document"""
		...
	
	def get_tags(self): # -> list[LiteralString]:
		"""Return a list of Tags attached to this document"""
		...
	
	def deferred_insert(self) -> None:
		"""Push the document to redis temporarily and insert later.

		WARN: This doesn't guarantee insertion as redis can be restarted
		before data is flushed to database.
		"""
		...
	
	def __str__(self) -> str:
		...
	
	def __repr__(self): # -> str:
		...
	


def execute_action(__doctype, __name, __action, **kwargs): # -> None:
	"""Execute an action on a document (called by background worker)"""
	...

def bulk_insert(doctype: str, documents: Iterable[Document], ignore_duplicates: bool = ..., chunk_size=..., commit_chunks=...): # -> None:
	"""Insert simple Documents objects to database in bulk.

	Warning/Info:
	        - All documents are inserted without triggering ANY hooks.
	        - This function assumes you've done the due dilligence and inserts in similar fashion as db_insert
	        - Documents can be any iterable / generator containing Document objects
	"""
	...

@frappe.whitelist()
def unlock_document(doctype: str, name: str): # -> None:
	...

def get_lazy_controller(doctype):
	...

class LazyDocument:
	"""Mixin for Document class that implments lazy loading for child tables."""
	@override
	def load_children_from_db(self: Document): # -> None:
		"""Override Document which eagerly loads child tables"""
		...
	
	@override
	def get(self: Document, key, filters=..., limit=..., default=...):
		...
	
	@override
	def append(self, key: str, value: D | dict | None = ..., position: int = ...) -> D:
		...
	
	@override
	def db_update_all(self): # -> None:
		...
	
	@override
	def init_child_tables(self): # -> None:
		...
	


class LazyChildTable:
	__slots__ = ...
	def __init__(self, fieldname: str, doctype: str) -> None:
		...
	
	def __get__(self, doc: Document, objtype=...): # -> Any:
		...
	


def copy_doc(doc: Document, ignore_no_copy: bool = ...) -> Document:
	"""No_copy fields also get copied."""
	...

def new_doc(doctype: str, *, parent_doc: Document | None = ..., parentfield: str | None = ..., as_dict: bool = ..., **kwargs) -> Document:
	"""Return a new document of the given DocType with defaults set.

	:param doctype: DocType of the new document.
	:param parent_doc: [optional] add to parent document.
	:param parentfield: [optional] add against this `parentfield`.
	:param as_dict: [optional] return as dictionary instead of Document.
	:param kwargs: [optional] You can specify fields as field=value pairs in function call.
	"""
	...

def get_cached_doc(*args: Any, **kwargs: Any) -> Document:
	"""Identical to `frappe.get_doc`, but return from cache if available."""
	...

def can_cache_doc(args) -> str | None:
	"""
	Determine if document should be cached based on get_doc params.
	Return cache key if doc can be cached, None otherwise.
	"""
	...

def get_document_cache_key(doctype: str, name: str): # -> str:
	...

def clear_document_cache(doctype: str, name: str | None = ...) -> None:
	...

def get_cached_value(doctype: str, name: str | dict, fieldname: str | Iterable[str] = ..., as_dict: bool = ...) -> Any:
	...

def get_single_value(setting: str, fieldname: str, /, *, as_dict: bool = ...): # -> Any:
	"""Return the cached value associated with the given fieldname from single DocType.

	Usage:
		telemetry_enabled = frappe.get_single_value("System Settings", "telemetry_enabled")
	"""
	...

def get_last_doc(doctype, filters: FilterSignature | None = ..., order_by=..., *, for_update=...): # -> Document:
	"""Get last created document of this type."""
	...

def get_single(doctype): # -> Document:
	"""Return a `frappe.model.document.Document` object of the given Single doctype."""
	...

