"""
This type stub file was generated by pyright.
"""

dynamic_link_queries = ...
def get_dynamic_link_map(for_delete=...): # -> Any | dict[Any, Any]:
	"""Build a map of all dynamically linked tables. For example,
	        if Note is dynamically linked to ToDo, the function will return
	        `{"Note": ["ToDo"], "Sales Invoice": ["Journal Entry Detail"]}`

	Note: Will not map single doctypes
	"""
	...

def get_dynamic_links(): # -> list[Any]:
	"""Return list of dynamic link fields as DocField.
	Uses cache if possible"""
	...

def fetch_distinct_link_doctypes(doctype: str, fieldname: str): # -> str | tuple[()] | Generator[Any | _dict[Incomplete | str | Any, Any] | list[Any], Any, None] | list[Any] | list[_dict[Any, Any]] | list[list[Any]] | tuple[tuple[Any, ...]] | Any | None:
	"""Return all unique doctypes a dynamic link is linking against.
	Note:
	- results are cached and can *possibly be outdated*
	- cache gets updated when a document with different document link is discovered
	- raw queries adding dynamic link won't update this cache
	- cache miss can often be VERY expensive on large table.
	"""
	...

def invalidate_distinct_link_doctypes(doctype: str, fieldname: str, linked_doctype: str): # -> None:
	"""If new linked doctype is discovered for a dynamic link then cache is evicted."""
	...

