"""
This type stub file was generated by pyright.
"""

import frappe
from typing import TYPE_CHECKING
from frappe.model.document import Document
from frappe.model.meta import Meta

if TYPE_CHECKING:
	...
@frappe.whitelist()
def update_document_title(*, doctype: str, docname: str, title: str | None = ..., name: str | None = ..., merge: bool = ..., enqueue: bool = ..., **kwargs) -> str:
	"""
	Update the name or title of a document. Return `name` if document was renamed, `docname` if renaming operation was queued.

	:param doctype: DocType of the document
	:param docname: Name of the document
	:param title: New Title of the document
	:param name: New Name of the document
	:param merge: Merge the current Document with the existing one if exists
	:param enqueue: Enqueue the rename operation, title is updated in current process
	"""
	...

def rename_doc(doctype: str | None = ..., old: str | int | None = ..., new: str | int | None = ..., force: bool = ..., merge: bool = ..., ignore_permissions: bool = ..., ignore_if_exists: bool = ..., show_alert: bool = ..., rebuild_search: bool = ..., doc: Document | None = ..., validate: bool = ...) -> str:
	"""Rename a doc(dt, old) to doc(dt, new) and update all linked fields of type "Link".

	doc: Document object to be renamed.
	new: New name for the record. If None, and doctype is specified, new name may be automatically generated via before_rename hooks.
	doctype: DocType of the document. Not required if doc is passed.
	old: Current name of the document. Not required if doc is passed.
	force: Allow even if document is not allowed to be renamed.
	merge: Merge with existing document of new name.
	ignore_permissions: Ignore user permissions while renaming.
	ignore_if_exists: Don't raise exception if document with new name already exists. This will quietely overwrite the existing document.
	show_alert: Display alert if document is renamed successfully.
	rebuild_search: Rebuild linked doctype search after renaming.
	validate: Validate before renaming. If False, it is assumed that the caller has already validated.
	"""
	...

def update_assignments(old: str, new: str, doctype: str) -> None:
	...

def update_user_settings(old: str, new: str, link_fields: list[dict]) -> None:
	"""
	Update the user settings of all the linked doctypes while renaming.
	"""
	...

def update_customizations(old: str, new: str) -> None:
	...

def update_attachments(doctype: str, old: str, new: str) -> None:
	...

def rename_versions(doctype: str, old: str, new: str) -> None:
	...

def rename_parent_and_child(doctype: str, old: str, new: str, meta: Meta) -> None:
	...

def update_autoname_field(doctype: str, new: str, meta: Meta) -> None:
	...

def validate_rename(doctype: str, old: str | int, new: str | int, meta: Meta, merge: bool, force: bool = ..., ignore_permissions: bool = ..., ignore_if_exists: bool = ..., save_point=..., old_doc: Document | None = ...) -> str:
	...

def rename_doctype(doctype: str, old: str, new: str) -> None:
	...

def update_child_docs(old: str, new: str, meta: Meta) -> None:
	...

def update_link_field_values(link_fields: list[dict], old: str, new: str, doctype: str) -> None:
	...

def get_link_fields(doctype: str) -> list[dict]:
	...

def update_options_for_fieldtype(fieldtype: str, old: str, new: str) -> None:
	...

def get_select_fields(old: str, new: str) -> list[dict]:
	"""
	get select type fields where doctype's name is hardcoded as
	new line separated list
	"""
	...

def update_select_field_values(old: str, new: str): # -> None:
	...

def update_parenttype_values(old: str, new: str): # -> None:
	...

def update_sequence_name(old: str, new: str, slug: str = ...): # -> None:
	...

def rename_dynamic_links(doctype: str, old: str, new: str): # -> None:
	...

def bulk_rename(doctype: str, rows: list[list] | None = ..., via_console: bool = ...) -> list[str] | None:
	"""Bulk rename documents

	:param doctype: DocType to be renamed
	:param rows: list of documents as `((oldname, newname, merge(optional)), ..)`"""
	...

