"""
This type stub file was generated by pyright.
"""

import frappe
from typing import Literal, TYPE_CHECKING

if TYPE_CHECKING:
	...
EMBED_PATTERN = ...
def get_email(recipients, sender=..., msg=..., subject=..., text_content=..., footer=..., print_html=..., formatted=..., attachments=..., content=..., reply_to=..., cc=..., bcc=..., email_account=..., expose_recipients=..., inline_images=..., header=..., x_priority: Literal[1, 3, 5] = ...): # -> EMail:
	"""Prepare an email with the following format:
	- multipart/mixed
	        - multipart/alternative
	                - text/plain
	                - multipart/related
	                        - text/html
	                        - inline image
	                - attachment
	"""
	...

class EMail:
	"""
	Wrapper on the email module. Email object represents emails to be sent to the client.
	Also provides a clean way to add binary `FileData` attachments
	Also sets all messages as multipart/alternative for cleaner reading in text-only clients
	"""
	def __init__(self, sender=..., recipients=..., subject=..., alternative=..., reply_to=..., cc=..., bcc=..., email_account=..., expose_recipients=..., x_priority: Literal[1, 3, 5] = ...) -> None:
		...
	
	def set_html(self, message, text_content=..., footer=..., print_html=..., formatted=..., inline_images=..., header=...): # -> None:
		"""Attach message in the html portion of multipart/alternative"""
		...
	
	def set_text(self, message): # -> None:
		"""
		Attach message in the text portion of multipart/alternative
		"""
		...
	
	def set_part_html(self, message, inline_images): # -> None:
		...
	
	def set_html_as_text(self, html): # -> None:
		"""Set plain text from HTML"""
		...
	
	def set_message(self, message, mime_type=..., as_attachment=..., filename=...): # -> None:
		"""Append the message with MIME content to the root node (as attachment)"""
		...
	
	def attach_file(self, n): # -> None:
		"""attach a file from the `FileData` table"""
		...
	
	def add_attachment(self, fname, fcontent, content_type=..., parent=..., content_id=..., inline=...): # -> None:
		"""add attachment"""
		...
	
	def add_pdf_attachment(self, name, html, options=...): # -> None:
		...
	
	def validate(self): # -> None:
		"""validate the Email Addresses"""
		...
	
	def validate_reply_to(self) -> None:
		...
	
	def replace_sender(self): # -> None:
		...
	
	def replace_sender_name(self): # -> None:
		...
	
	def set_message_id(self, message_id, is_notification=...): # -> None:
		...
	
	def set_in_reply_to(self, in_reply_to): # -> None:
		"""Used to send the Message-Id of a received email back as In-Reply-To"""
		...
	
	def add_headers(self, headers): # -> None:
		"""Add custom headers to the email"""
		...
	
	def make(self): # -> None:
		"""build into msg_root"""
		...
	
	def set_header(self, key, value): # -> None:
		...
	
	def as_string(self): # -> str:
		"""validate, build message and convert to string"""
		...
	


def get_formatted_html(subject, message, footer=..., print_html=..., email_account=..., header=..., unsubscribe_link: frappe._dict | None = ..., sender=..., with_container=..., raw_html=..., add_css=...):
	...

@frappe.whitelist()
def get_email_html(template: str, args: str, subject: str, header: str | list | None = ..., with_container: str | int | bool = ...):
	...

def inline_style_in_html(html, add_css=...):
	"""Convert email.css and html to inline-styled html."""
	...

def add_attachment(fname, fcontent, content_type=..., parent=..., content_id=..., inline=...): # -> None:
	"""Add attachment to parent which must an email object"""
	...

def get_message_id(): # -> str:
	"""Return Message ID created from doctype and name."""
	...

def get_signature(email_account): # -> Literal['']:
	...

def get_footer(email_account, footer=...): # -> Any:
	"""append a footer (signature)"""
	...

def replace_filename_with_cid(message, provided_images=...): # -> tuple[Any | str, list[Any]]:
	"""Replaces <img embed="assets/frappe/images/filename.jpg" ...> with
	<img src="cid:content_id" ...> and return the modified message and
	a list of inline_images with {filename, filecontent, content_id}

	Args:
		message: The HTML message to process
		provided_images: A dictionary of images to use instead of reading from disk
			Example:
			{
				"assets/frappe/images/filename.jpg": filecontent,
				"filename.jpg": filecontent,
			}
	"""
	...

def get_filecontent_from_path(path): # -> bytes | None:
	...

def get_header(header=...): # -> str | Any | None:
	"""Build header from template"""
	...

def sanitize_email_header(header: str): # -> str:
	"""
	Removes all line boundaries in the headers.

	Email Policy (python's std) has some bugs in it which uses splitlines
	and raises ValueError (ref: https://github.com/python/cpython/blob/main/Lib/email/policy.py#L143).
	Hence removing all line boundaries while sanitization of headers to prevent such faliures.
	The line boundaries which are removed can be found here: https://docs.python.org/3/library/stdtypes.html#str.splitlines
	"""
	...

def get_brand_logo(email_account):
	...

