"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

FIELDTYPES_TO_IGNORE = ...
class Version(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		data: DF.Code | None
		docname: DF.Data
		ref_doctype: DF.Link
		...
	def update_version_info(self, old: Document | None, new: Document) -> bool:
		"""Update changed info and return true if change contains useful data."""
		...
	
	@staticmethod
	def set_impersonator(data): # -> None:
		...
	
	def set_diff(self, old: Document, new: Document) -> bool:
		"""Set the data property with the diff of the docs if present"""
		...
	
	def for_insert(self, doc: Document) -> bool:
		...
	
	def get_data(self): # -> Any:
		...
	
	def onload(self): # -> None:
		"""Generate HTML diffs for multiline changes on document load."""
		...
	


def get_diff(old, new, for_child=..., compare_cancelled=...):
	"""Get diff between 2 document objects

	If there is a change, then returns a dict like:

	        {
	                "changed"    : [[fieldname1, old, new], [fieldname2, old, new]],
	                "added"      : [[table_fieldname1, {dict}], ],
	                "removed"    : [[table_fieldname1, {dict}], ],
	                "row_changed": [[table_fieldname1, row_name1, row_index,
	                        [[child_fieldname1, old, new],
	                        [child_fieldname2, old, new]], ]
	                ],

	        }"""
	...

def on_doctype_update(): # -> None:
	...

