"""
This type stub file was generated by pyright.
"""

import contextlib
import frappe
from collections.abc import Callable

verbose = ...
compress = ...
_verbose = ...
base_tables = ...
BACKUP_ENCRYPTION_CONFIG_KEY = ...
class BackupGenerator:
	"""
	This class contains methods to perform On Demand Backup

	To initialize, specify (db_name, user, password, db_file_name=None, db_host="127.0.0.1")
	If specifying db_file_name, also append ".sql.gz"
	"""
	def __init__(self, db_name, user, password, backup_path=..., backup_path_db=..., backup_path_files=..., backup_path_private_files=..., db_socket=..., db_host=..., db_port=..., db_type=..., backup_path_conf=..., ignore_conf=..., compress_files=..., include_doctypes=..., exclude_doctypes=..., verbose=..., old_backup_metadata=..., rollback_callback=...) -> None:
		...
	
	def setup_backup_directory(self): # -> None:
		...
	
	def setup_backup_tables(self): # -> None:
		"""Set self.backup_includes, self.backup_excludes based on include_doctypes, exclude_doctypes"""
		...
	
	def set_backup_tables_from_config(self): # -> None:
		"""Set self.backup_includes, self.backup_excludes based on site config"""
		...
	
	@property
	def site_config_backup_path(self): # -> Any | None:
		...
	
	def get_backup(self, older_than=..., ignore_files=..., force=...): # -> None:
		"""
		Takes a new dump if existing file is old
		and sends the link to the file as email
		"""
		...
	
	def set_backup_file_name(self): # -> None:
		...
	
	def backup_encryption(self): # -> None:
		"""
		Encrypt all the backups created using gpg.
		"""
		...
	
	def get_recent_backup(self, older_than, partial=...): # -> tuple[Any | None, Any | None, Any | None, Any | None]:
		...
	
	def zip_files(self): # -> None:
		...
	
	def get_summary(self): # -> dict[str, dict[str, Any]]:
		...
	
	def print_summary(self): # -> None:
		...
	
	def backup_files(self): # -> None:
		...
	
	def copy_site_config(self): # -> None:
		...
	
	def take_dump(self): # -> None:
		...
	
	def send_email(self): # -> str | tuple[()] | Generator[Any | _dict[Incomplete | str | Any, Any] | list[Any], Any, None] | list[Any] | list[_dict[Any, Any]] | list[list[Any]] | tuple[tuple[Any, ...]] | None:
		"""
		Sends the link to backup file located at erpnext/backups
		"""
		...
	
	def add_to_rollback(self, func: Callable) -> None:
		"""
		Adds the given callable to the rollback CallbackManager stack

		:param func: The callable to add to the rollback stack
		:return: Nothing
		"""
		...
	
	def delete_if_step_fails(self, step: Callable, *paths: str): # -> None:
		"""
		Deletes the given path if the given step fails

		:param step: The step to execute
		:param paths: The paths to delete
		:return: Nothing
		"""
		...
	


@frappe.whitelist()
def fetch_latest_backups(partial: bool = ...) -> dict:
	"""Fetch paths of the latest backup taken in the last 30 days.

	Note: Only for System Managers

	Return:
	        dict: relative Backup Paths
	"""
	...

def scheduled_backup(older_than=..., ignore_files=..., backup_path=..., backup_path_db=..., backup_path_files=..., backup_path_private_files=..., backup_path_conf=..., ignore_conf=..., include_doctypes=..., exclude_doctypes=..., compress=..., force=..., verbose=..., old_backup_metadata=..., rollback_callback=...): # -> BackupGenerator:
	"""this function is called from scheduler
	deletes backups older than 7 days
	takes backup"""
	...

def new_backup(older_than=..., ignore_files=..., backup_path=..., backup_path_db=..., backup_path_files=..., backup_path_private_files=..., backup_path_conf=..., ignore_conf=..., include_doctypes=..., exclude_doctypes=..., compress=..., force=..., verbose=..., old_backup_metadata=..., rollback_callback=...): # -> BackupGenerator:
	...

def delete_temp_backups(older_than=...): # -> None:
	"""
	Cleans up the backup_link_path directory by deleting older files
	"""
	...

def is_file_old(file_path, older_than=...) -> bool:
	"""Return True if file exists and is older than specified hours."""
	...

def get_backup_path():
	...

@frappe.whitelist()
def get_backup_encryption_key(): # -> Any | str:
	...

def get_or_generate_backup_encryption_key(): # -> Any | str:
	...

@contextlib.contextmanager
def decrypt_backup(file_path: str, passphrase: str): # -> Generator[None, Any, None]:
	...

def backup(with_files=..., backup_path_db=..., backup_path_files=..., backup_path_private_files=..., backup_path_conf=...): # -> dict[str, Any | str | None]:
	"Backup"
	...

