"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from functools import lru_cache
from typing import Any, NoReturn
from redis.exceptions import BusyLoadingError, ConnectionError
from rq import Queue, Worker
from rq.job import Job, JobStatus
from rq.worker import DequeueStrategy
from tenacity import retry, retry_if_exception_type, stop_after_attempt, wait_fixed

RQ_JOB_FAILURE_TTL = ...
RQ_FAILED_JOBS_LIMIT = ...
RQ_RESULTS_TTL = ...
RQ_MAX_JOBS = ...
RQ_MAX_JOBS_JITTER = ...
MAX_QUEUED_JOBS = ...
QUEUE_STARVATION_THRESHOLD = ...
_redis_queue_conn = ...
@lru_cache
def get_queues_timeout() -> dict[str, int]:
	"""
	Method returning a mapping of queue name to timeout for that queue

	:return: Dictionary of queue name to timeout
	"""
	...

def enqueue(method: str | Callable, queue: str = ..., timeout: int | None = ..., event: str | None = ..., is_async: bool = ..., job_name: str | None = ..., now: bool = ..., enqueue_after_commit: bool = ..., *, on_success: Callable | None = ..., on_failure: Callable | None = ..., at_front: bool = ..., job_id: str | None = ..., deduplicate=..., at_front_when_starved=..., retry=..., **kwargs) -> Job | Any:
	"""
	Enqueue method to be executed using a background worker

	:param method: method string or method object
	:param queue: should be either long, default or short
	:param timeout: should be set according to the functions
	:param event: this is passed to enable clearing of jobs from queues
	:param is_async: if is_async=False, the method is executed immediately, else via a worker
	:param job_name: [DEPRECATED] can be used to name an enqueue call, which can be used to prevent
	duplicate calls
	:param now: if now=True, the method is executed via frappe.call()
	:param enqueue_after_commit: if True, the job will be enqueued after the current transaction is
	committed
	:param on_success: Success callback
	:param on_failure: Failure callback
	:param at_front: Enqueue the job at the front of the queue or not
	:param kwargs: keyword arguments to be passed to the method
	:param deduplicate: do not re-queue job if it's already queued, requires job_id.
	:param job_id: Assigning unique job id, which can be checked using `is_job_enqueued`
	:param at_front_when_starved: If the queue appears to be starved then new jobs are
	automatically inserted in LIFO fashion.
	"""
	...

def enqueue_doc(doctype, name=..., method=..., queue=..., timeout=..., now=..., **kwargs): # -> Job | Any:
	"""
	Enqueue a method to be run on a document

	:param doctype: DocType of the document on which you want to run the event
	:param name: Name of the document on which you want to run the event
	:param method: method string or method object
	:param queue: (optional) should be either long, default or short
	:param timeout: (optional) should be set according to the functions
	:param kwargs: keyword arguments to be passed to the method
	"""
	...

def run_doc_method(doctype, name, doc_method, **kwargs): # -> None:
	...

def execute_job(site, method, event, job_name, kwargs, user=..., is_async=..., retry=...): # -> Any:
	"""Executes job in a worker, performs commit/rollback and logs if there is any error"""
	...

def start_worker(queue: str | None = ..., quiet: bool = ..., rq_username: str | None = ..., rq_password: str | None = ..., burst: bool = ..., strategy: DequeueStrategy | None = ...) -> NoReturn:
	"""Wrapper to start rq worker. Connects to redis and monitors these queues."""
	...

class FrappeWorker(Worker):
	def work(self, *args, **kwargs): # -> bool:
		...
	
	def run_maintenance_tasks(self, *args, **kwargs): # -> None:
		"""Attempt to start a scheduler in case the worker doing scheduling died."""
		...
	
	def start_frappe_scheduler(self): # -> None:
		...
	


class FrappeWorkerNoFork(FrappeWorker):
	def __init__(self, *args, **kwargs) -> None:
		...
	
	def work(self, *args, **kwargs): # -> bool:
		...
	
	def execute_job(self, job: Job, queue: Queue): # -> None:
		"""Execute job in same thread/process, do not fork()"""
		...
	
	def no_fork_exception_handler(self, job, exc_type, exc_value, traceback): # -> None:
		...
	
	def get_heartbeat_ttl(self, job: Job) -> int:
		...
	
	def kill_horse(self, sig=...): # -> None:
		...
	


def start_worker_pool(queue: str | None = ..., num_workers: int = ..., quiet: bool = ..., burst: bool = ...) -> NoReturn:
	"""Start worker pool with specified number of workers.

	WARNING: This feature is considered "EXPERIMENTAL".
	"""
	...

def get_worker_name(queue): # -> str | None:
	"""When limiting worker to a specific queue, also append queue name to default worker name"""
	...

def get_jobs(site=..., queue=..., key=...): # -> defaultdict[Any, list[Any]]:
	"""Gets jobs per queue or per site or both"""
	...

def get_queue_list(queue_list=..., build_queue_name=...): # -> list[str]:
	"""Defines possible queues. Also wraps a given queue in a list after validating."""
	...

def get_workers(queue=...): # -> list[BaseWorker]:
	"""Return a list of Worker objects tied to a queue object if queue is passed, else return a list of all workers."""
	...

def get_running_jobs_in_queue(queue): # -> list[Any]:
	"""Return a list of Jobs objects that are tied to a queue object and are currently running."""
	...

def get_queue(qtype: str, is_async: bool = ...) -> Queue:
	"""
	Return a Queue object tied to a redis connection.

	:param qtype: Queue type, should be either long, default or short
	:param is_async: Whether the job should be executed asynchronously or in the same process
	:return: Queue object
	"""
	...

def validate_queue(queue: str, default_queue_list: list | None = ...) -> None:
	"""
	Validates if the queue is in the list of default queues.

	:param queue: The queue to be validated
	:param default_queue_list: Optionally, a custom list of queues to validate against
	:return:
	"""
	...

@retry(retry=retry_if_exception_type((BusyLoadingError, ConnectionError)), stop=stop_after_attempt(5), wait=wait_fixed(1), reraise=True)
def get_redis_conn(username=..., password=...): # -> Redis:
	...

def get_redis_connection_without_auth(): # -> Redis:
	...

def get_queues(connection=...) -> list[Queue]:
	"""Get all the queues linked to the current bench."""
	...

def generate_qname(qtype: str) -> str:
	"""Generate qname by combining bench ID and queue type.

	qnames are useful to define namespaces of customers.
	"""
	...

def is_queue_accessible(qobj: Queue) -> bool:
	"""Checks whether queue is relate to current bench or not."""
	...

def enqueue_test_job(): # -> None:
	...

def test_job(s): # -> None:
	...

def create_job_id(job_id: str | None = ...) -> str:
	"""
	Generate unique job id for deduplication

	:param job_id: Optional job id, if not provided, a UUID is generated for it
	:return: Unique job id, namespaced by site
	"""
	...

def is_job_enqueued(job_id: str) -> bool:
	...

def get_job_status(job_id: str) -> JobStatus | None:
	"""Get RQ job status, returns None if job is not found."""
	...

def get_job(job_id: str) -> Job | None:
	...

BACKGROUND_PROCESS_NICENESS = ...
def set_niceness(): # -> None:
	"""Background processes should have slightly lower priority than web processes.

	Calling this function increments the niceness of process by configured value or default.
	Note: This function should be called only once in process' lifetime.
	"""
	...

def truncate_failed_registry(job, connection, type, value, traceback): # -> None:
	"""Ensures that number of failed jobs don't exceed specified limits."""
	...

