"""
This type stub file was generated by pyright.
"""

import frappe
from typing import Any

def read_csv_content_from_attached_file(doc): # -> list[Any] | None:
	...

def read_csv_content(fcontent, use_sniffer: bool = ..., delimiter: str | None = ...): # -> list[Any]:
	...

@frappe.whitelist()
def send_csv_to_client(args: str | dict[str, Any]): # -> None:
	...

def to_csv(data): # -> str:
	...

def build_csv_response(data, filename): # -> None:
	...

class UnicodeWriter:
	def __init__(self, encoding=..., quoting=...) -> None:
		...
	
	def writerow(self, row): # -> None:
		...
	
	def getvalue(self): # -> str:
		...
	


def check_record(d): # -> None:
	"""check for mandatory, select options, dates. these should ideally be in doclist"""
	...

def import_doc(d, doctype, overwrite, row_idx, submit=..., ignore_links=...): # -> str:
	"""import main (non child) document"""
	...

def getlink(doctype, name): # -> str:
	...

def get_csv_content_from_google_sheets(url): # -> bytes | None:
	...

def validate_google_sheets_url(url): # -> None:
	...

