"""
This type stub file was generated by pyright.
"""

from typing import Literal

def get_not_null_defaults(column_type: str) -> Literal["", 0] | None:
	"""
	Method to return a default value for a column type that is not NoneType
	:param column_type: The type of column
	:return: The value to be set
	"""
	...

