"""
This type stub file was generated by pyright.
"""

EXCLUDE_EXCEPTIONS = ...
LDAP_BASE_EXCEPTION = ...
def log_error(title=..., message=..., reference_doctype=..., reference_name=..., *, defer_insert=...): # -> _NewDocument | None:
	"""Log error to Error Log"""
	...

def get_error_metadata() -> str:
	"""
	Returns request/job metadata to store in Error Log for easier debugging
	"""
	...

def log_error_snapshot(exception: Exception): # -> None:
	...

def get_default_args(func): # -> dict[str, Any]:
	"""Get default arguments of a function from its signature."""
	...

def raise_error_on_no_output(error_message, error_type=..., keep_quiet=...): # -> Callable[..., _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]]:
	"""Decorate any function to throw error incase of missing output.

	:param error_message: error message to raise
	:param error_type: type of error to raise
	:param keep_quiet: control error raising with external factor.
	:type error_message: str
	:type error_type: Exception Class
	:type keep_quiet: function

	---
	Example:

	```py
	@raise_error_on_no_output("Ingredients are missing")
	def get_ingredients(_raise_error=1):
	    return


	# this will raise an Exception with message "Ingredients are missing"
	ingredients = get_ingredients()
	```

	---

	TODO: Remove keep_quiet flag after testing and fixing sendmail flow.
	"""
	...

def guess_exception_source(exception: str) -> str | None:
	"""Attempts to guess source of error based on traceback.

	E.g.

	- For unhandled exception last python file from apps folder is responsible.
	- For frappe.throws the exception source is possibly present after skipping frappe.throw frames
	- For server script the file name contains SERVER_SCRIPT_FILE_PREFIX

	"""
	...

