"""
This type stub file was generated by pyright.
"""

import frappe

class MaxFileSizeReachedError(frappe.ValidationError):
	...


def safe_b64decode(binary: bytes) -> bytes:
	"""Adds padding if doesn't already exist before decoding.

	This attempts to avoid the `binascii.Error: Incorrect padding` error raised
	when the number of trailing = is simply not enough :crie:. Although, it may
	be an indication of corrupted data.

	Refs:
	        * https://en.wikipedia.org/wiki/Base64
	        * https://stackoverflow.com/questions/2941995/python-ignore-incorrect-padding-error-when-base64-decoding
	"""
	...

def get_file_url(file_data_name): # -> None:
	...

def upload(): # -> dict[str, Any]:
	...

def get_file_doc(dt=..., dn=..., folder=..., is_private=..., df=...): # -> Document:
	"""Return File object (Document) from given parameters or `form_dict`."""
	...

def save_uploaded(dt, dn, folder, is_private, df=...): # -> Document:
	...

def save_url(file_url, filename, dt, dn, folder, is_private, df=...): # -> Document:
	...

def get_uploaded_content(): # -> tuple[Any | None, bytes] | tuple[None, None]:
	...

def save_file(fname, content, dt, dn, folder=..., decode=..., is_private=..., df=...): # -> Document:
	...

def get_file_data_from_hash(content_hash, is_private=...): # -> dict[Any, list[Any] | tuple[Any, ...] | Any | None] | Literal[False]:
	...

def save_file_on_filesystem(fname, content, content_type=..., is_private=...): # -> dict[str, Any]:
	...

def get_max_file_size(): # -> Any | Literal[10485760]:
	...

def check_max_file_size(content): # -> int:
	...

def write_file(content, fname, is_private=...):
	"""write file to disk with a random name (to compare)"""
	...

def remove_all(dt, dn, from_delete=..., delete_permanently=...): # -> None:
	"""remove all files in a transaction"""
	...

def remove_file(fid=..., attached_to_doctype=..., attached_to_name=..., from_delete=..., delete_permanently=...): # -> _NewDocument | None:
	"""Remove file and File entry"""
	...

def delete_file_data_content(doc, only_thumbnail=...): # -> None:
	...

def delete_file_from_filesystem(doc, only_thumbnail=...): # -> None:
	"""Delete file, thumbnail from File document"""
	...

def delete_file(path): # -> None:
	"""Delete file from `public folder`"""
	...

def get_file(fname): # -> list[Any]:
	"""Return [`file_name`, `content`] for given file name `fname`."""
	...

def get_file_path(file_name): # -> None:
	"""Return file path from given file name."""
	...

def get_content_hash(content): # -> str:
	...

def get_file_name(fname, optional_suffix): # -> str:
	...

@frappe.whitelist()
def add_attachments(doctype: str, name: str | int, attachments: str | list[str]): # -> list[Any]:
	"""Add attachments to the given DocType"""
	...

def is_safe_path(path: str) -> bool:
	...

