"""
This type stub file was generated by pyright.
"""

"""Utils for inter-process synchronization using file-locks.

This file implements a "weak" form lock which is not suitable for synchroniztion. This is only used
for document locking for queue_action.
Use `frappe.utils.synchroniztion.filelock` for process synchroniztion.
"""
LOCKS_DIR = ...
class LockTimeoutError(Exception):
	...


def create_lock(name): # -> Literal[False]:
	"""Creates a file in the /locks folder by the given name.

	Note: This is a "weak lock" and is prone to race conditions. Do not use this lock for small
	sections of code that execute immediately.

	This is primarily use for locking documents for background submission.
	"""
	...

def lock_exists(name): # -> bool:
	"""Return True if lock of the given name exists."""
	...

def lock_age(name) -> float:
	"""Return time in seconds since lock was created."""
	...

def check_lock(path, timeout=...): # -> bool:
	...

def delete_lock(name): # -> Literal[True]:
	...

def get_lock_path(name):
	...

def release_document_locks(): # -> None:
	"""Unlocks all documents that were locked by the current context."""
	...

