"""
This type stub file was generated by pyright.
"""

FRAPPE_CLOUD_DOMAINS = ...
def on_frappecloud() -> bool:
	"""Returns true if running on Frappe Cloud.


	Useful for modifying few features for better UX."""
	...

