"""
This type stub file was generated by pyright.
"""

def resize_images(path, maxdim=...): # -> None:
	...

def strip_exif_data(content, content_type) -> bytes:
	"""Strip EXIF from image files which support it.

	Works by creating a new Image object which ignores exif by
	default and then extracts the binary data back into content.

	Return Stripped image content.
	"""
	...

def optimize_image(content, content_type, max_width=..., max_height=..., optimize=..., quality=...): # -> bytes:
	...

