"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager

def get_jenv(*, restrict_globals=...): # -> Any | FrappeSandboxedEnvironment:
	...

def get_template(path): # -> Template | Any:
	...

def get_email_from_template(name, args): # -> tuple[str | Any, str | Any | None]:
	...

def validate_template(html, restrict_globals=...): # -> None:
	"""Throws exception if there is a syntax error in the Jinja Template"""
	...

def render_template(template, context=..., is_path=..., safe_render=..., *, restrict_globals=...): # -> str | Any | None:
	"""Render a template using Jinja

	:param template: path or HTML containing the jinja template
	:param context: dict of properties to pass to the template
	:param is_path: (optional) assert that the `template` parameter is a path
	:param safe_render: (optional) prevent server side scripting via jinja templating
	:param restrict_globals: (optional) restrict globals in template rendering to render only globals.
	"""
	...

def guess_is_path(template): # -> bool:
	...

def get_jloader(): # -> ChoiceLoader:
	...

def set_filters(jenv): # -> None:
	...

def get_jinja_hooks(): # -> tuple[None, None] | tuple[dict[Any, Any], dict[Any, Any]]:
	"""Return a tuple of (methods, filters) each containing a dict of method name and method definition pair."""
	...

@contextmanager
def safe_render_flags(): # -> Generator[None, Any, None]:
	...

