"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from typing import Literal

def msgprint(msg: str | Sequence[str] | Sequence[Sequence[str]], title: str | None = ..., raise_exception: bool | type[Exception] | Exception = ..., as_table: bool = ..., as_list: bool = ..., indicator: Literal["blue", "green", "orange", "red", "yellow"] | None = ..., alert: bool = ..., primary_action: dict | None = ..., is_minimizable: bool = ..., wide: bool = ..., *, realtime=..., allow_dangerous_html=...) -> None:
	"""Print a message to the user (via HTTP response).
	Messages are sent in the `__server_messages` property in the
	response JSON and shown in a pop-up / modal.

	:param msg: Message.
	:param title: [optional] Message title. Default: "Message".
	:param raise_exception: [optional] Raise given exception and show message.
	:param as_table: [optional] If `msg` is a list of lists, render as HTML table.
	:param as_list: [optional] If `msg` is a list, render as un-ordered list.
	:param primary_action: [optional] Bind a primary server/client side action.
	:param is_minimizable: [optional] Allow users to minimize the modal
	:param wide: [optional] Show wide modal
	:param realtime: Publish message immediately using websocket.
	:param allow_dangerous_html: Allow arbitrary HTML in message.
	"""
	...

def toast(message: str, indicator: Literal["blue", "green", "orange", "red", "yellow"] | None = ...): # -> None:
	...

def clear_messages(): # -> None:
	...

def get_message_log() -> list[dict]:
	...

def clear_last_message(): # -> None:
	...

def throw(msg: str | Sequence[str], exc: type[Exception] | Exception = ..., title: str | None = ..., is_minimizable: bool = ..., wide: bool = ..., as_list: bool = ..., primary_action=..., *, allow_dangerous_html=...) -> None:
	"""Throw execption and show message (`msgprint`).

	:param msg: Message.
	:param exc: Exception class. Default `frappe.ValidationError`
	:param title: [optional] Message title. Default: "Message".
	:param is_minimizable: [optional] Allow users to minimize the modal
	:param wide: [optional] Show wide modal
	:param as_list: [optional] If `msg` is a list, render as un-ordered list.
	:param primary_action: [optional] Bind a primary server/client side action.
	"""
	...

def throw_permission_error(): # -> None:
	...

__all__ = ["clear_last_message", "clear_messages", "get_message_log", "msgprint", "throw", "throw_permission_error", "toast"]
