"""
This type stub file was generated by pyright.
"""

from frappe.utils.caching import redis_cache

def get_modules_from_all_apps_for_user(user: str | None = ...) -> list[dict]:
	...

def get_modules_from_all_apps(): # -> list[Any]:
	...

@redis_cache
def get_modules_from_app(app): # -> list[Any]:
	...

def is_domain(module):
	...

def is_module(module):
	...

