"""
This type stub file was generated by pyright.
"""

import frappe
from collections.abc import Callable
from typing import TYPE_CHECKING
from frappe.core.doctype.user.user import User

if TYPE_CHECKING:
	...
class SignupDisabledError(frappe.PermissionError):
	...


def build_oauth_url(base_url: str, url: str | None = ...) -> str:
	"""
	Build a complete OAuth authorization URL.

	This helper constructs a full OAuth URL starting from a given base URL.

	If `url` is omitted, the function simply returns the normalized base URL.  If the
	`url` contains the relative or absolute path, the function will return this
	appended to the base URL.  If the `url` contains a `scheme` (e.g. "https://" and a
	`netloc` (e.g. "www.example.com")), the function will return the passed `url` alone.

	Args:
		base_url (str): The base OAuth endpoint (e.g. "https://example.com").
		url (str | None): An optional path or override URL to combine with the base.

	Returns:
		str: The fully qualified OAuth URL ready for use in redirects or API calls.
	"""
	...

def get_oauth2_providers() -> dict[str, dict]:
	...

def get_oauth_keys(provider: str) -> dict[str, str]:
	"""get client_id and client_secret from database or conf"""
	...

def get_oauth2_authorize_url(provider: str, redirect_to: str) -> str:
	...

def get_oauth2_flow(provider: str): # -> OAuth2Service:
	...

def get_redirect_uri(provider: str) -> str:
	...

def login_via_oauth2(provider: str, code: str, state: str, decoder: Callable | None = ...): # -> None:
	...

def login_via_oauth2_id_token(provider: str, code: str, state: str, decoder: Callable | None = ...): # -> None:
	...

def get_info_via_oauth(provider: str, code: str, decoder: Callable | None = ..., id_token: bool = ...): # -> dict[str, Any] | Any:
	...

def login_oauth_user(data: dict | str, *, provider: str | None = ..., state: dict | str, generate_login_token: bool = ...): # -> None:
	...

def get_user_record(user: str, data: dict, provider: str) -> User:
	...

def update_oauth_user(user: str, data: dict, provider: str): # -> Literal[False] | None:
	...

def get_first_name(data: dict) -> str:
	...

def get_last_name(data: dict) -> str:
	...

def get_email(data: dict) -> str:
	...

def redirect_post_login(desk_user: bool, redirect_to: str | None = ..., provider: str | None = ...): # -> None:
	...

