"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from zxcvbn import _Result
from collections.abc import Iterable
from zxcvbn.feedback import _Feedback as PasswordStrengthFeedback
from zxcvbn.matching import _Match

if TYPE_CHECKING:
	...
def test_password_strength(password: str, user_inputs: Iterable[object] | None = ...) -> _Result:
	"""Wrapper around zxcvbn.password_strength"""
	...

default_feedback: PasswordStrengthFeedback = ...
def get_feedback(score: int, sequence: list) -> PasswordStrengthFeedback:
	"""Return the feedback dictionary consisting of ("warning","suggestions") for the given sequences."""
	...

def get_match_feedback(match: _Match, is_sole_match: bool) -> PasswordStrengthFeedback:
	"""Return feedback as a dictionary for a certain match."""
	...

def get_dictionary_match_feedback(match: _Match, is_sole_match: bool) -> PasswordStrengthFeedback:
	"""Return feedback for a match that is found in a dictionary."""
	...

