"""
This type stub file was generated by pyright.
"""

import cssutils
import frappe
from pdfkit.pdfkit import PDFKit as OriginalPDFKit
from bs4 import BeautifulSoup
from pypdf import PdfWriter
from frappe.utils.caching import redis_cache

PDF_CONTENT_ERRORS = ...
class FrappePDFKit(OriginalPDFKit):
	...


def pdf_header_html(soup, head, content, styles, html_id, css, path=...): # -> str | Any | None:
	...

def pdf_body_html(template, args, **kwargs): # -> None:
	...

def pdf_footer_html(soup, head, content, styles, html_id, css, path=...): # -> str | Any | None:
	...

def get_pdf(html, options=..., output: PdfWriter | None = ...): # -> PdfWriter | bytes:
	...

def measure_time(func): # -> Callable[..., Any]:
	...

@measure_time
def get_chrome_pdf(print_format, html, options, output, pdf_generator=...): # -> bytes | None:
	...

def get_file_data_from_writer(writer_obj): # -> bytes:
	...

def prepare_options(html, options): # -> tuple[str, Any | dict[Any, Any]]:
	...

def get_cookie_options(): # -> dict[Any, Any]:
	...

def read_options_from_html(html): # -> tuple[str, dict[Any, Any]]:
	...

def get_print_format_styles(soup: BeautifulSoup) -> list[cssutils.css.Property]:
	"""
	Get styles purely on class 'print-format'.
	Valid:
	1) .print-format { ... }
	2) .print-format, p { ... } | p, .print-format { ... }

	Invalid (applied on child elements):
	1) .print-format p { ... } | .print-format > p { ... }
	2) .print-format #abc { ... }

	Returns:
	[cssutils.css.Property(name='margin-top', value='50mm', priority=''), ...]
	"""
	...

def inline_private_images(html) -> str:
	...

def prepare_header_footer(soup: BeautifulSoup): # -> dict[Any, Any]:
	...

def cleanup(options): # -> None:
	...

def toggle_visible_pdf(soup): # -> None:
	...

@frappe.whitelist()
@redis_cache(ttl=60 * 60)
def is_wkhtmltopdf_valid(): # -> bool:
	...

def get_wkhtmltopdf_version(): # -> str | Any:
	...

def pdf_contains_js(file_content: bytes): # -> bool:
	"""
	Check if a PDF file contains JavaScript.

	Args:
		file_content (bytes): The content of the PDF file.

	Returns:
		bool: True if the PDF contains JavaScript, False otherwise and also if the file is encrypted.
	"""
	...

def get_host_url(): # -> str:
	...

