"""
This type stub file was generated by pyright.
"""

import frappe
from typing import ClassVar

@frappe.whitelist()
def render_jinja_template(template: str, doctype: str, docname: str) -> str:
	"""Render a raw Jinja2 template string with doc context (used by the print format builder preview)."""
	...

@frappe.whitelist()
def download_pdf(doctype: str, name: str | int, print_format: str, letterhead: str | None = ...): # -> None:
	...

def get_html(doctype, name, print_format, letterhead=...): # -> str | Any | None:
	...

class PrintFormatGenerator:
	"""Generate a PDF of a Document using Chromium-based rendering."""
	_TOP_POSITIONS: ClassVar[set[str]] = ...
	_BOTTOM_POSITIONS: ClassVar[set[str]] = ...
	_ALIGN_MAP: ClassVar[dict[str, str]] = ...
	def __init__(self, print_format, doc, letterhead=...) -> None:
		...
	
	def build_context(self): # -> None:
		...
	
	def get_html_preview(self): # -> str | Any | None:
		...
	
	def get_main_html(self): # -> str | Any | None:
		...
	
	def get_header_footer_html(self): # -> tuple[str | Any | None, str | Any | None]:
		...
	
	def render_pdf(self): # -> bytes | None:
		"""Return PDF bytes using the Chromium renderer."""
		...
	
	_ZONE_SECTION_TEMPLATE = ...
	def get_layout(self, print_format): # -> str:
		...
	
	def set_field_renderers(self, layout):
		...
	
	def process_margin_texts(self, layout):
		...
	


