"""
This type stub file was generated by pyright.
"""

import redis
from redis.commands.search import Search

DEFAULT_PICKLE_PROTOCOL = ...
class RedisearchWrapper(Search):
	def sugadd(self, key, *suggestions, **kwargs):
		...
	
	def suglen(self, key): # -> int:
		...
	
	def sugdel(self, key, string): # -> int:
		...
	
	def sugget(self, key, *args, **kwargs): # -> List[SuggestionParser]:
		...
	


class RedisWrapper(redis.Redis):
	"""Redis client that will automatically prefix conf.db_name"""
	def connected(self): # -> bool:
		...
	
	def __call__(self): # -> Self:
		"""WARNING: Added for backward compatibility to support frappe.cache().method(...)"""
		...
	
	def make_key(self, key, user=..., shared=...): # -> bytes:
		...
	
	def set_value(self, key, val, user=..., expires_in_sec=..., shared=...): # -> None:
		"""Sets cache value.

		:param key: Cache key
		:param val: Value to be cached
		:param user: Prepends key with User
		:param expires_in_sec: Expire value of this key in X seconds
		"""
		...
	
	def get_value(self, key, generator=..., user=..., expires=..., shared=..., *, use_local_cache=...): # -> Any | None:
		"""Return cache value. If not found and generator function is
		        given, call the generator.

		:param key: Cache key.
		:param generator: Function to be called to generate a value if `None` is returned.
		:param expires: If the key is supposed to be with an expiry, don't store it in frappe.local
		"""
		...
	
	def expire_key(self, key, time, *, user=..., shared=...): # -> ResponseT | None:
		...
	
	def get_all(self, key): # -> dict[Any, Any]:
		...
	
	def get_keys(self, key, user=..., shared=...): # -> ResponseT | list[Any]:
		"""Return keys starting with `key`."""
		...
	
	def delete_keys(self, key, user=..., shared=...): # -> None:
		"""Delete keys with wildcard `*`."""
		...
	
	def delete_key(self, *args, **kwargs): # -> None:
		...
	
	def delete_value(self, keys, user=..., make_keys=..., shared=...): # -> None:
		"""Delete value, list of values."""
		...
	
	def lpush(self, key, value, user=..., shared=...): # -> Awaitable[int] | int:
		...
	
	def rpush(self, key, value): # -> Awaitable[int] | int:
		...
	
	def lpop(self, key, user=..., shared=...): # -> Awaitable[str | List[Any] | None] | str | List[Any] | None:
		...
	
	def rpop(self, key): # -> Awaitable[str | List[Any] | None] | str | List[Any] | None:
		...
	
	def blpop(self, key, timeout=..., user=..., shared=...): # -> Awaitable[list[Any]] | list[Any]:
		...
	
	def llen(self, key): # -> Awaitable[int] | int:
		...
	
	def lrange(self, key, start, stop): # -> Awaitable[list[Any]] | list[Any]:
		...
	
	def ltrim(self, key, start, stop): # -> Awaitable[str] | str:
		...
	
	def hset(self, name: str, key: str, value, shared: bool = ..., *args, **kwargs): # -> None:
		...
	
	def hexists(self, name: str, key: str, shared: bool = ...) -> bool:
		...
	
	def exists(self, *names: str, user=..., shared=...) -> int:
		...
	
	def hgetall(self, name): # -> dict[Any, Any]:
		...
	
	def hget(self, name, key, generator=..., shared=...): # -> Any | None:
		...
	
	def hdel(self, name: str, keys: str | list | tuple, shared=..., pipeline: redis.client.Pipeline | None = ...): # -> None:
		"""
		A wrapper around redis' HDEL command

		:param name: The hash name
		:param keys: the keys to delete
		:param shared: shared frappe key or not
		:param pipeline: A redis.client.Pipeline object, if this transaction is to be run in a pipeline
		"""
		...
	
	def hdel_names(self, names: list | tuple, key: str): # -> None:
		"""
		A function to call HDEL on multiple hash names with a common key, run in a single pipeline

		:param names: The hash names
		:param key: The common key
		"""
		...
	
	def hdel_keys(self, name_starts_with, key): # -> None:
		"""Delete hash names with wildcard `*` and key"""
		...
	
	def hkeys(self, name): # -> Awaitable[List[Any]] | List[Any]:
		...
	
	def sadd(self, name, *values): # -> None:
		"""Add a member/members to a given set"""
		...
	
	def srem(self, name, *values): # -> None:
		"""Remove a specific member/list of members from the set."""
		...
	
	def sismember(self, name, value): # -> Awaitable[Literal[0, 1]] | Literal[0, 1]:
		"""Return True or False based on if a given value is present in the set."""
		...
	
	def spop(self, name): # -> str | List[Any] | None:
		"""Remove and returns a random member from the set."""
		...
	
	def srandmember(self, name, count=...): # -> str | List[Any] | None:
		"""Return a random member from the set."""
		...
	
	def smembers(self, name): # -> Awaitable[Set[Any]] | Set[Any]:
		"""Return all members of the set."""
		...
	
	def ft(self, index_name=...): # -> RedisearchWrapper:
		...
	


def setup_cache() -> RedisWrapper:
	...

def get_sentinel_connection(sentinels: list[tuple[str, int]], sentinel_username=..., sentinel_password=..., master_username=..., master_password=...): # -> Sentinel:
	...

class _ClientTrackingMixin:
	def __init__(self, *args, **kwargs) -> None:
		...
	


class _TrackedConnection(_ClientTrackingMixin, redis.Connection):
	...


class _TrackedUnixDomainSocketConnection(_ClientTrackingMixin, redis.UnixDomainSocketConnection):
	...


CachedValue = ...
CacheStatistics = ...
_PLACEHOLDER_VALUE = ...
class ClientCache:
	"""A subset of RedisWrapper that keeps "local" cache across requests.

	Main reason for doing this is improving performance while reading things like hooks, schema.
	This feature is internal to Frappe Framework and is subjected to change without any notice.
	There aren't many use cases for such aggressive caching outside of core Framework.

	This is an implementation of Redis' "client side caching" concept:
		- https://redis.io/docs/latest/develop/reference/client-side-caching/

	Usage/Notes:
		- Cache keys that do not change often: Think hours-days, not minutes.
		- Cache keys that are read frequently, e.g. every request or at least >10% of the requests.
		- Cache values are not huge, consider avg size of ~4kb per value. You can deviate here and
		  there but not go crazy with caching large values in this cache.
		- We have hardcoded 10 minutes "local" ttl and max 1024 keys.
			You're not supposed to work with these numbers, not change them.
		- Same keys can be accessed with `frappe.cache` too, but that won't implement invalidation.
		- Invalidate things as usual using `delete_value`. Local invalidation should be instant.
		  Do not expect sub-second invalidation guarantees across processes.
		  If you need that kind of guarantees, don't use this cache.
		- When redis connection isn't available or any unknown exceptions are encountered, this
		  cache automatically turns itself off and falls back to behaviour that is equivalent to
		  default Redis cache behaviour.
		- Never use `frappe.cache`'s request local cache along with client-side cache. Two
		  different copies of same key are a big source of data races.
		- This cache uses simple FIFO eviction policy. Make sure your access patterns don't cause
		  the worst case behaviour for this policy. E.g. looping over `maxsize` items repeatedly.
	"""
	def __init__(self, maxsize: int = ..., ttl=..., monitor: RedisWrapper | None = ...) -> None:
		...
	
	def get_value(self, key, *, shared=..., generator=...): # -> Any | None:
		...
	
	def set_value(self, key, val, *, shared=...): # -> None:
		...
	
	def get_doc(self, doctype: str, name: str | None = ...): # -> Any | None:
		"""Utility to fetch and store documents in client cache.

		Use sparingly, this should ideally be used for settings and doctypes that have few known
		number of documents.
		"""
		...
	
	def ensure_max_size(self): # -> None:
		...
	
	def delete_value(self, key, *, shared=...): # -> None:
		...
	
	def delete_keys(self, pattern): # -> None:
		...
	
	def run_invalidator_thread(self): # -> PubSubWorkerThread:
		...
	
	def erase_persistent_caches(self, *, doctype=...): # -> None:
		"""Send signal to clear all worker-specific caches

		This can include cached controller resolution, @site_cache and any other similar persistent
		cache.
		"""
		...
	
	def clear_cache(self): # -> None:
		...
	
	@property
	def statistics(self) -> CacheStatistics:
		...
	
	def reset_statistics(self): # -> None:
		...
	


