"""
This type stub file was generated by pyright.
"""

"""Distributed counting semaphore backed by a Redis LIST."""
class RedisSemaphore:
	"""A distributed counting semaphore backed by a Redis LIST.

	Allows up to *limit* concurrent holders across all processes sharing the
	same Redis instance. The token pool is lazily initialized and self-heals
	after crashes thanks to a TTL on the capacity key.

	Usage as a context manager::

	    sem = RedisSemaphore("my-resource", limit=5, wait_timeout=10)
	    with sem:
	        ...  # at most 5 concurrent holders

	Or acquire/release manually::

	    token = sem.acquire()
	    if token is None:
	        raise Exception("Too busy")
	    try:
	        ...
	    finally:
	        sem.release(token)
	"""
	CAPACITY_TTL = ...
	def __init__(self, key: str, limit: int, wait_timeout: float = ..., shared: bool = ...) -> None:
		"""
		:param key: A unique Redis key name for this semaphore (will be
		    prefixed by the cache layer).
		:param limit: Maximum number of concurrent holders.
		:param wait_timeout: Seconds to block waiting for a free slot.
		    0 means non-blocking (immediate return if unavailable).
		:param shared: If True, the semaphore key is bench-wide (not
		    prefixed with the site's db_name). Defaults to site-scoped.
		"""
		...
	
	def acquire(self) -> str | None:
		"""Try to acquire a token from the pool.

		Returns a token string on success, ``None`` if no slot was
		available within *wait_timeout*, or ``"fallback"`` if Redis is
		unreachable (fail-open).
		"""
		...
	
	def release(self, token: str) -> None:
		"""Return *token* to the pool."""
		...
	
	def __enter__(self): # -> str | None:
		...
	
	def __exit__(self, *exc_info): # -> None:
		...
	


