"""
This type stub file was generated by pyright.
"""

import frappe
from contextlib import contextmanager
from typing import Any
from RestrictedPython import PrintCollector
from RestrictedPython.transformer import RestrictingNodeTransformer

class ServerScriptNotEnabled(frappe.PermissionError):
	...


ARGUMENT_NOT_SET = ...
SAFE_EXEC_CONFIG_KEY = ...
SERVER_SCRIPT_FILE_PREFIX = ...
RENDER_EXEC_CONFIG_KEY = ...
class NamespaceDict(frappe._dict):
	"""Raise AttributeError if function not found in namespace"""
	def __getattr__(self, key): # -> Callable[..., NoReturn] | None:
		...
	


class FrappeTransformer(RestrictingNodeTransformer):
	def check_name(self, node, name, *args, **kwargs): # -> None:
		...
	


class FrappePrintCollector(PrintCollector):
	"""Collect written text, and return it when called."""
	...


def is_safe_exec_enabled() -> bool:
	...

def is_render_exec_enabled() -> bool:
	...

def safe_exec(script: str, _globals: dict | None = ..., _locals: dict | None = ..., *, restrict_commit_rollback: bool = ..., script_filename: str | None = ...): # -> tuple[NamespaceDict, dict[Any, Any] | None]:
	...

def safe_eval(code, eval_globals=..., eval_locals=...): # -> Any:
	...

@contextmanager
def safe_exec_flags(): # -> Generator[None, Any, None]:
	...

def get_doc_as_dict(*args, **kwargs): # -> dict[Any, Any]:
	...

def safer_get_last_doc(*args, **kwargs): # -> dict[Any, Any]:
	...

def safer_get_cached_doc(*args, **kwargs): # -> dict[Any, Any]:
	...

def remove_unsafe_fields(fields): # -> list[Any]:
	...

def safe_get_list(*args, **kwargs): # -> list[Any]:
	...

def safe_get_all(*args, **kwargs): # -> list[Any]:
	...

def safer_get_meta(doctype, cached=...): # -> _dict[Any, Any] | None:
	...

def safer_log_error(title=..., message=..., reference_doctype=..., reference_name=..., *, defer_insert=...): # -> dict[Any, Any]:
	...

def safer_get_visible_columns(*args, **kwargs): # -> list[<subclass of DocField and dict> | dict[Any, Any]] | None:
	...

def safe_get_value(*args, **kwargs): # -> list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | _dict[Any, Any] | list[Any | None] | None:
	...

def safe_get_single_value(*args, **kwargs): # -> int | str | date | datetime | timedelta | None:
	...

def safe_render_template(*args, **kwargs): # -> str | Any | None:
	...

ALLOWED_SCHEMES = ...
def make_safe_get_request(url: str, **kwargs): # -> dict[str, list[str]] | Any | str | None:
	...

def render_safe_globals(): # -> NamespaceDict:
	"""Safer subset of globals for rendering ops."""
	...

def exec_safe_globals(): # -> NamespaceDict:
	"""Safer subset of globals for exec. ops."""
	...

def get_keys_for_autocomplete(key: str, value: Any, prefix: str = ..., offset: int = ..., meta: str = ..., depth: int = ..., max_depth: int | None = ...): # -> Generator[dict[str, Any] | Any, Any, None]:
	...

def is_job_queued(job_name, queue=...): # -> list[Any] | bool | None:
	"""
	:param job_name: used to identify a queued job, usually dotted path to function
	:param queue: should be either long, default or short
	"""
	...

def safe_enqueue(function, **kwargs): # -> Job | Any:
	"""
	Enqueue function to be executed using a background worker
	Accepts frappe.enqueue params like job_name, queue, timeout, etc.
	in addition to params to be passed to function

	:param function: whitelisted function or API Method set in Server Script
	"""
	...

def call_whitelisted_function(function, **kwargs): # -> None:
	"""Executes a whitelisted function or Server Script of type API"""
	...

def run_script(script, **kwargs):
	"""run another server script"""
	...

def call_with_form_dict(function, kwargs):
	...

def get_python_builtins(): # -> dict[str, Any]:
	...

def get_hooks(hook: str | None = ..., default=..., app_name: str | None = ...) -> frappe._dict:
	"""Get hooks via `app/hooks.py`

	:param hook: Name of the hook. Will gather all hooks for this name and return as a list.
	:param default: Default if no hook found.
	:param app_name: Filter by app."""
	...

def read_sql(query, *args, **kwargs): # -> str | tuple[()] | Generator[Any | _dict[Incomplete | str | Any, Any] | list[Any], Any, None] | list[Any] | list[_dict[Any, Any]] | list[list[Any]] | tuple[tuple[Any, ...]] | None:
	"""a wrapper for frappe.db.sql to allow reads"""
	...

def check_safe_sql_query(query: str, throw: bool = ...) -> bool:
	...

UNSAFE_ATTRIBUTES = ...
def get_module_properties(module, filter_method): # -> dict[Any, Any]:
	...

VALID_UTILS = ...
SAFE_DATA_UTILS = ...
WHITELISTED_SAFE_EVAL_GLOBALS = ...
SAFE_ORJSON = ...
SAFE_EXCEPTIONS = ...
get_safe_globals = ...
