"""
This type stub file was generated by pyright.
"""

import frappe
from typing import NoReturn
from frappe.utils.caching import redis_cache

"""
Events:
	always
	daily
	monthly
	weekly
"""
DATETIME_FORMAT = ...
DEFAULT_SCHEDULER_TICK = ...
def cprint(*args, **kwargs): # -> None:
	"""Prints only if called from STDOUT"""
	...

def start_scheduler() -> NoReturn:
	"""Run enqueue_events_for_all_sites based on scheduler tick.
	Specify scheduler_tick_interval in seconds in common_site_config.json"""
	...

def is_schduler_process_running() -> bool:
	"""Checks if any other process is holding the lock.

	Note: FLOCK is held by process until it exits, this function just checks if process is
	running or not. We can't determine if process is stuck somehwere.
	"""
	...

def sleep_duration(tick): # -> float:
	...

def enqueue_events_for_all_sites() -> None:
	"""Loop through sites and enqueue events that are not already queued"""
	...

def enqueue_events_for_site(site: str) -> None:
	...

def enqueue_events() -> list[str] | None:
	...

def is_scheduler_inactive(verbose=...) -> bool:
	...

def is_scheduler_disabled(verbose=...) -> bool:
	...

def toggle_scheduler(enable): # -> None:
	...

def enable_scheduler(): # -> None:
	...

def disable_scheduler(): # -> None:
	...

@redis_cache(ttl=60 * 60)
def schedule_jobs_based_on_activity(check_time=...): # -> bool:
	"""Return True for active sites as defined by `Activity Log`.
	Also return True for inactive sites once every 24 hours based on `Scheduled Job Log`."""
	...

@redis_cache(ttl=60 * 60)
def is_dormant(check_time=...): # -> bool:
	...

@frappe.whitelist()
def activate_scheduler(): # -> None:
	...

@frappe.whitelist()
def get_scheduler_status(): # -> dict[str, str]:
	...

def get_scheduler_tick() -> int:
	...

