"""
This type stub file was generated by pyright.
"""

from sentry_sdk.integrations import Integration

class FrappeIntegration(Integration):
	identifier = ...
	@staticmethod
	def setup_once(): # -> None:
		...
	


def set_scope(scope): # -> None:
	...

def set_sentry_context(): # -> None:
	...

def before_send(event, hint): # -> None:
	...

def capture_exception(message: str | None = ...) -> None:
	"""
	Function to upload exception data to entry

	:param message: A message to be sent if we can't find an exception
	"""
	...

