"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager

"""Utils for thread/process synchronization."""
LOCKS_DIR = ...
@contextmanager
def filelock(lock_name: str, *, timeout=..., is_global=...): # -> Generator[None, Any, None]:
	"""Create a lockfile to prevent concurrent operations acrosss processes.

	args:
	        lock_name: Unique name to identify a specific lock. Lockfile called `{name}.lock` will be
	        created.
	        timeout: time to wait before failing.
	        is_global: if set lock is global to bench

	Lock file location:
	        global - {bench_dir}/config/{name}.lock
	        site - {bench_dir}/sites/sitename/{name}.lock

	"""
	...

