"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from typing import TYPE_CHECKING
from frappe.core.doctype.background_task.background_task import BackgroundTask

if TYPE_CHECKING:
	...
def enqueue_task(method: str | Callable, *, task_name: str | None = ..., queue: str = ..., timeout: int | None = ..., ref_doctype: str | None = ..., ref_docname: str | None = ..., deduplicate: bool = ..., job_id: str | None = ..., enqueue_after_commit: bool = ..., now: bool = ..., on_success: Callable | None = ..., on_failure: Callable | None = ..., retry_on: tuple[type[Exception], ...] = ..., max_retries: int = ..., show_progress_bar: bool = ..., allow_user_cancellation: bool = ..., allow_user_retry: bool = ..., at_front: bool = ..., at_front_when_starved: bool = ..., **kwargs) -> BackgroundTask:
	"""A wrapper around frappe.enqueue. Enqueue a background job with user-facing tracking"""
	...

def get_current_task() -> BackgroundTask | None:
	...

def get_task_status(task_id: str) -> dict | None:
	...

