"""
This type stub file was generated by pyright.
"""

import xlsxwriter
from dataclasses import dataclass
from io import BytesIO
from typing import Any, ClassVar, Literal

ILLEGAL_CHARACTERS_RE = ...
INVALID_SHEET_NAME_RE = ...
MAX_SHEET_NAME_LENGTH = ...
@dataclass(slots=True)
class XLSXMetadata:
	"""
	Metadata container for XLSX report styling.

	- All indexes must be 0-based respecting xlsxwriter's indexing.

	Attributes:
		column_map: Maps column index to column dict (fieldname, fieldtype, etc.).
		row_map: Maps row index to row data (dict or list).
		applied_filters_map: Maps row index to list of applied filter label-value pairs.
		has_total_row: Whether the last row is a total row.
		has_indentation: Whether indentation styling should be applied.

		# optional metadata for custom style builders
		report_name: Name of the report.
		filters: Raw filter values.
	"""
	column_map: dict[int, dict] = ...
	row_map: dict[int, dict | list] = ...
	applied_filters_map: dict[int, list] = ...
	has_total_row: bool = ...
	has_indentation: bool = ...
	report_name: str = ...
	filters: dict = ...
	def get_column(self, fieldname: str) -> dict | None:
		"""
		Get column dict by fieldname, or None if not found.
		"""
		...
	
	def get_header_index(self) -> int:
		"""
		Get header row index based on applied filters.
		Assumes header is always 1 row after the last filter row.
		"""
		...
	
	def get_first_row_index(self) -> int:
		...
	
	def get_last_row_index(self) -> int:
		...
	


class XLSXStyleBuilder:
	"""
	Builder for XLSX cell styles based on report metadata.

	Builds a style dictionary with:
		- styles: List of style definitions (xlsxwriter format properties). List index is the style ID.
		- column_styles: Maps column index to list of style IDs.
		- row_styles: Maps row index to list of style IDs.
		- cell_styles: Maps (row, col) tuple to list of style IDs.

	**Usage:**

	```
	builder = XLSXStyleBuilder(metadata)
	builder.style_column(0, builder.register_style({"bold": True}))
	styles = builder.result
	```
	"""
	RIGHT_ALIGN_FIELDTYPES: ClassVar[set[str]] = ...
	def __init__(self, metadata: XLSXMetadata, default_styling: bool = ...) -> None:
		...
	
	def register_style(self, style: dict) -> int:
		"""
		Register a style and return its ID.

		Style dict uses xlsxwriter format properties.
		"""
		...
	
	def style_column(self, col_idx: int, style_id: int): # -> Self:
		"""
		Apply a style to all cells in a column.

		Args:
			col_idx: 0-based column index
			style_id: ID of the style to apply (from register_style)
		"""
		...
	
	def style_row(self, row_idx: int, style_id: int): # -> Self:
		"""
		Apply a style to all cells in a row.

		Args:
			row_idx: 0-based row index
			style_id: ID of the style to apply (from register_style)
		"""
		...
	
	def style_cell(self, row_idx: int, col_idx: int, style_id: int): # -> Self:
		"""
		Apply a style to a specific cell.

		Args:
			row_idx: 0-based row index
			col_idx: 0-based column index
			style_id: ID of the style to apply (from register_style)
		"""
		...
	
	def apply_default_styles(self, currency_formatting: bool = ...): # -> Self:
		"""
		Apply all default styles:

		- Header row styling
		- Filter rows styling
		- Total row styling (if has_total_row)
		- Indentation styling (if has_indentation)
		- Default fieldtype formatting (numbers, dates, etc.)
			- Currency formatting can be toggled with currency_formatting flag
		"""
		...
	
	def style_header(self): # -> Self:
		...
	
	def style_filters(self): # -> Self:
		...
	
	def apply_indentations(self, col_idx: int = ..., field: str = ..., pt: int = ...): # -> Self:
		...
	
	def style_total_row(self): # -> Self:
		...
	
	def apply_default_fieldtype_formats(self, currency_formatting: bool = ...): # -> Self:
		...
	
	def apply_currency_fieldtype_formats(self): # -> Self:
		...
	
	@staticmethod
	def get_number_format(fieldtype: Literal["Currency", "Float", "Percent"], currency: str | None = ...) -> str:
		"""
		Get Excel number format string for the given fieldtype.
		"""
		...
	
	@staticmethod
	def get_date_format() -> str:
		...
	
	@staticmethod
	def get_time_format() -> str:
		...
	
	@staticmethod
	def get_datetime_format() -> str:
		...
	


def get_default_xlsx_styles(columns: list[dict], data: list[list | dict], applied_filters: list[list] | None = ..., *, has_total_row: bool = ..., has_indentation: bool = ..., currency_formatting: bool = ...) -> dict:
	"""
	Generate default XLSX styles for xlsx exports.

	Args:
		columns: Column definitions with keys: fieldname, fieldtype, label, options.
		data: Row data as list of dicts or lists (excluding header and filter rows).
		applied_filters: Filter rows to display at top of sheet. Each item is [label, value].
		has_total_row: If True, applies bold styling to the last row.
		has_indentation: If True, applies indent styles based on row's 'indent' key.
		currency_formatting: If True, applies currency number formats to Currency fields.
	"""
	...

def make_xlsx(data: list[list[Any]], sheet_name: str, wb: xlsxwriter.Workbook | None = ..., column_widths: list[int] | None = ..., styles: dict | None = ...) -> BytesIO | None:
	"""
	Create an Excel file with the given data and formatting options.

	Args:
		data: List of rows, where each row is a list of cell values
		sheet_name: Name of the Excel sheet
		wb: Existing workbook to add sheet to. If None, creates new workbook
			- Workbook must be closed by caller if provided
			- Should be created with constant_memory=True for large datasets
		column_widths: List of column widths in Excel units. If None, auto-sized
		styles: Dictionary defining styles for cells, rows, and columns
			- as returned by XLSXStyleBuilder.result
	Returns:
		BytesIO | None: BytesIO object containing the Excel file data if a new workbook was created, otherwise None

	"""
	...

def get_sanitized_sheet_name(name: str) -> str:
	...

def handle_html(data: str) -> str:
	...

def read_xlsx_file_from_attached_file(file_url=..., fcontent=..., filepath=..., *, read_only=...): # -> list[Any] | None:
	...

def read_xls_file_from_attached_file(content): # -> list[Sequence[str]]:
	...

def build_xlsx_response(data, filename, styles: dict | None = ...): # -> None:
	...

