"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class CommunicationLink(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		communication_date: DF.Datetime | None
		link_doctype: DF.Link
		link_name: DF.DynamicLink
		link_title: DF.ReadOnly | None
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		...


def on_doctype_update(): # -> None:
	...

