"""
This type stub file was generated by pyright.
"""

from werkzeug.wrappers import Response
from frappe.permissions import handle_does_not_exist_error

def get_response(path=..., http_status_code=...) -> Response:
	"""Resolves path and renders page"""
	...

@handle_does_not_exist_error
def handle_exception(e, endpoint, path, http_status_code): # -> Response:
	...

def get_response_content(path=..., http_status_code=...) -> str:
	...

def get_response_without_exception_handling(path=..., http_status_code=...) -> Response:
	"""Resolves path and renders page.

	Note: This doesn't do any exception handling and assumes you'll implement the exception
	handling that's required."""
	...

