"""
This type stub file was generated by pyright.
"""

from functools import lru_cache

FRONTMATTER_PATTERN = ...
H1_TAG_PATTERN = ...
IMAGE_TAG_PATTERN = ...
CLEANUP_PATTERN_1 = ...
CLEANUP_PATTERN_2 = ...
CLEANUP_PATTERN_3 = ...
def delete_page_cache(path=...): # -> None:
	...

def find_first_image(html): # -> str | Any | None:
	...

def can_cache(no_cache=...): # -> bool:
	...

def get_comment_list(doctype, name): # -> list[Any]:
	...

def get_home_page(): # -> Any | str | None:
	...

def get_home_page_via_hooks():
	...

def get_boot_data(): # -> dict[str, Any]:
	...

def is_signup_disabled(): # -> Any | None:
	...

def cleanup_page_name(title: str) -> str:
	"""make page name from title"""
	...

def abs_url(path): # -> None:
	"""Deconstructs and Reconstructs a URL into an absolute URL or a URL relative from root '/'"""
	...

def get_toc(route, url_prefix=..., app=...): # -> str | Any:
	"""Insert full index (table of contents) for {index} tag"""
	...

def get_next_link(route, url_prefix=..., app=...): # -> str:
	...

def get_full_index(route=..., app=...): # -> Any | None:
	"""Return full index of the website for www upto the n-th level."""
	...

def extract_title(source, path): # -> str | Any:
	"""Return title from `&lt;!-- title --&gt;` or &lt;h1&gt; or path."""
	...

def extract_comment_tag(source: str, tag: str): # -> str | Any | None:
	"""Extract custom tags in comments from source.

	:param source: raw template source in HTML
	:param title: tag to search, example "title"
	"""
	...

def get_html_content_based_on_type(doc, fieldname, content_type): # -> UnicodeWithAttrs | Literal['']:
	"""
	Set content based on content_type
	"""
	...

def clear_cache(path=...): # -> None:
	"""Clear website caches
	:param path: (optional) for the given path"""
	...

def clear_website_cache(path=...): # -> None:
	...

def get_frontmatter(string): # -> dict[str, Any | str]:
	"Reference: https://github.com/jonbeebe/frontmatter"
	...

def get_sidebar_items(parent_sidebar, basepath=...): # -> Any | list[Any]:
	...

def get_portal_sidebar_items(): # -> Any | list[Any]:
	...

def get_sidebar_items_from_sidebar_file(basepath, look_for_sidebar_json): # -> list[Any] | Any:
	...

def get_sidebar_json_path(path, look_for=...): # -> str:
	"""Get _sidebar.json path from directory path
	:param path: path of the current diretory
	:param look_for: if True, look for _sidebar.json going upwards from given path
	:return: _sidebar.json path
	"""
	...

WEBSITE_PAGE_CACHE_PREFIX = ...
def cache_html(func): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
	...

def build_response(path, data, http_status_code, headers: dict | None = ...): # -> Response:
	...

def set_content_type(response, data, path): # -> str:
	...

def add_preload_for_bundled_assets(response): # -> None:
	...

@lru_cache
def is_binary_file(path): # -> bool:
	...

def check_if_webform_exists(route): # -> list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | _dict[Any, Any] | list[Any | None] | None:
	...

