"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class WebsiteGenerator(Document):
	website = ...
	def __init__(self, *args, **kwargs) -> None:
		...
	
	def get_website_properties(self, key=..., default=...): # -> dict[Any, Any] | None:
		...
	
	def autoname(self): # -> None:
		...
	
	def onload(self): # -> None:
		...
	
	def validate(self): # -> None:
		...
	
	def set_route(self): # -> None:
		...
	
	def make_route(self): # -> str:
		"""Return the default route. If `route` is specified in DocType it will be route/title."""
		...
	
	def scrubbed_title(self): # -> str:
		...
	
	def get_title_field(self): # -> Data | dict[Any, Any]:
		"""return title field from website properties or meta.title_field"""
		...
	
	def clear_cache(self): # -> None:
		...
	
	def scrub(self, text): # -> str:
		...
	
	def get_parents(self, context): # -> None:
		"""Return breadcrumbs"""
		...
	
	def on_update(self): # -> None:
		...
	
	def on_change(self): # -> None:
		...
	
	def on_trash(self): # -> None:
		...
	
	def is_website_published(self): # -> list[Any] | tuple[Any, ...] | Any | bool:
		"""Return true if published in website"""
		...
	
	def get_condition_field(self): # -> Data | dict[Any, Any] | None:
		...
	
	def get_page_info(self): # -> _dict[Any, Any]:
		...
	
	def send_indexing_request(self, operation_type=...): # -> None:
		"""Send indexing request on update/trash operation."""
		...
	
	def allow_website_search_indexing(self): # -> Check:
		...
	
	def remove_old_route_from_index(self): # -> None:
		"""Remove page from the website index if the route has changed."""
		...
	
	def update_website_search_index(self): # -> None:
		"""
		Update the full test index executed on document change event.
		- remove document from index if document is unpublished
		- update index otherwise
		"""
		...
	


