"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

STANDARD_ROLES = ...
class Role(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		desk_access: DF.Check
		disabled: DF.Check
		home_page: DF.Data | None
		is_custom: DF.Check
		restrict_to_domain: DF.Link | None
		role_name: DF.Data
		two_factor_auth: DF.Check
		...
	def before_rename(self, old, new, merge=...): # -> None:
		...
	
	def after_insert(self): # -> None:
		...
	
	def validate(self): # -> None:
		...
	
	def disable_role(self): # -> None:
		...
	
	def validate_homepage(self): # -> None:
		...
	
	def set_desk_properties(self): # -> None:
		...
	
	def remove_roles(self): # -> None:
		...
	
	def on_update(self): # -> None:
		"""update system user desk access if this has changed in this update"""
		...
	
	def update_user_type_on_change(self): # -> None:
		"""When desk access changes, all the users that have this role need to be re-evaluated"""
		...
	
	@frappe.whitelist()
	def replicate_role(self, cur_role: str, new_role: str) -> str:
		...
	


def get_info_based_on_role(role, field=..., ignore_permissions=...): # -> list[Any | list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | _dict[Any, Any] | list[Any | None]] | list[Any]:
	"""Get information of all users that have been assigned this role"""
	...

def get_user_info(users, field=...): # -> list[Any]:
	"""Fetch details about users for the specified field"""
	...

def get_users(role): # -> list[Any]:
	...

@frappe.whitelist()
@frappe.validate_and_sanitize_search_inputs
def role_query(doctype: str, txt: str, searchfield: str, start: int, page_len: int, filters: list | dict | str): # -> list[Any]:
	...

