"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class CustomRole(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		page: DF.Link | None
		ref_doctype: DF.Data | None
		report: DF.Link | None
		roles: DF.Table[HasRole]
		...
	def validate(self): # -> None:
		...
	
	def get_permission_log_options(self, event=...): # -> dict[str, Any]:
		...
	


def get_custom_allowed_roles(field, name): # -> list[Any]:
	...

