"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from shutil import which
from frappe.database.database import savepoint

def setup_database(force, verbose=..., mariadb_user_host_login_scope=...): # -> None:
	...

def bootstrap_database(verbose=..., source_sql=...): # -> None:
	...

def drop_user_and_database(db_name, db_user): # -> None:
	...

def get_db(socket=..., host=..., user=..., password=..., port=..., cur_db_name=...): # -> PostgresDatabase | SQLiteDatabase | frappe.database.mariadb.mysqlclient.MariaDBDatabase | frappe.database.mariadb.database.MariaDBDatabase:
	...

def get_command(socket=..., host=..., port=..., user=..., password=..., db_name=..., extra=..., dump=...): # -> tuple[str | None, list[str], Literal['mariadb-dump', 'mariadb', 'sqlite3', 'pg_dump', 'psql']]:
	...

