"""
This type stub file was generated by pyright.
"""

SEQUENCE_CACHE = ...
def create_sequence(doctype_name: str, *, slug: str = ..., temporary: bool = ..., check_not_exists: bool = ..., cycle: bool = ..., cache: int = ..., start_value: int = ..., increment_by: int = ..., min_value: int = ..., max_value: int = ...) -> str:
	...

def get_next_val(doctype_name: str, slug: str = ...) -> int:
	...

def set_next_val(doctype_name: str, next_val: int, *, slug: str = ..., is_val_used: bool = ...) -> None:
	...

def create_missing_sequences() -> list[str]:
	"""Recreate sequences for autoincrement doctypes whose sequence object is missing."""
	...

