"""
This type stub file was generated by pyright.
"""

import frappe
from typing import Any

def load_address_and_contact(doc, key=...) -> None:
	"""Loads address list and contact list in `__onload`"""
	...

def has_permission(doc, ptype, user): # -> bool:
	...

def get_permission_query_conditions_for_contact(user): # -> str:
	...

def get_permission_query_conditions_for_address(user): # -> str:
	...

def get_permission_query_conditions(doctype): # -> str:
	...

def get_permitted_and_not_permitted_links(doctype): # -> dict[str, list[Any]]:
	...

def delete_contact_and_address(doctype: str, docname: str) -> None:
	...

@frappe.whitelist()
@frappe.validate_and_sanitize_search_inputs
def filter_dynamic_link_doctypes(doctype: str, txt: str, searchfield: str, start: int, page_len: int, filters: dict[str, Any]) -> list[list[str]]:
	...

def set_link_title(doc): # -> None:
	...

