"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

class WebsiteSettings(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		address: DF.SmallText | None
		app_logo: DF.AttachImage | None
		app_name: DF.Data | None
		auto_account_deletion: DF.Int
		banner_html: DF.Code | None
		banner_image: DF.AttachImage | None
		brand_html: DF.Code | None
		call_to_action: DF.Data | None
		call_to_action_url: DF.Data | None
		copyright: DF.Data | None
		disable_signup: DF.Check
		enable_google_indexing: DF.Check
		enable_view_tracking: DF.Check
		favicon: DF.Attach | None
		footer_items: DF.Table[TopBarItem]
		footer_logo: DF.AttachImage | None
		footer_powered: DF.SmallText | None
		footer_template: DF.Link | None
		footer_template_values: DF.Code | None
		google_analytics_anonymize_ip: DF.Check
		google_analytics_id: DF.Data | None
		head_html: DF.Code | None
		hide_footer_signup: DF.Check
		hide_login: DF.Check
		home_page: DF.Data | None
		indexing_authorization_code: DF.Data | None
		indexing_refresh_token: DF.Data | None
		navbar_search: DF.Check
		navbar_template: DF.Link | None
		navbar_template_values: DF.Code | None
		robots_txt: DF.Code | None
		route_redirects: DF.Table[WebsiteRouteRedirect]
		show_account_deletion_link: DF.Check
		show_footer_on_login: DF.Check
		show_language_picker: DF.Check
		splash_image: DF.AttachImage | None
		subdomain: DF.SmallText | None
		title_prefix: DF.Data | None
		top_bar_items: DF.Table[TopBarItem]
		website_theme: DF.Link | None
		website_theme_image_link: DF.Code | None
		...
	def validate(self): # -> None:
		...
	
	def validate_home_page(self): # -> None:
		...
	
	def validate_top_bar_items(self): # -> None:
		"""validate url in top bar items"""
		...
	
	def validate_footer_items(self): # -> None:
		"""validate url in top bar items"""
		...
	
	def validate_google_settings(self): # -> None:
		...
	
	def validate_redirects(self): # -> None:
		...
	
	def on_update(self): # -> None:
		...
	
	def clear_cache(self): # -> None:
		...
	
	def get_access_token(self): # -> str | int | None:
		...
	


def get_website_settings(context=...): # -> _dict[Any, Any]:
	...

def get_items(parentfield: str) -> list[dict]:
	...

def modify_header_footer_items(items: list): # -> list[Any]:
	...

@frappe.whitelist(allow_guest=True)
def get_auto_account_deletion(): # -> int | str | date | datetime | timedelta | None:
	...

