"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class Language(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		based_on: DF.Link | None
		date_format: DF.Literal["", yyyy - mm - dd, dd - mm - yyyy, dd / mm / yyyy, dd.mm.yyyy, mm / dd / yyyy, mm - dd - yyyy]
		enabled: DF.Check
		first_day_of_the_week: DF.Literal["", Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]
		flag: DF.Data | None
		language_code: DF.Data
		language_name: DF.Data
		number_format: DF.Literal["", "#,###.##", "#.###,##", "# ###.##", "# ###,##", "#'###.##", "#, ###.##", "#,##,###.##", "#,###.###", "#.###", "#,###",]
		time_format: DF.Literal["", "HH:mm:ss", "HH:mm"]
		...
	def validate(self): # -> None:
		...
	
	def before_rename(self, old, new, merge=...): # -> None:
		...
	
	def on_update(self): # -> None:
		...
	
	def update_user_defaults(self): # -> None:
		"""Update user defaults for date, time, number format and first day of the week.

		When we change any settings of a language, the defaults for all users with that language
		should be updated.
		"""
		...
	


def validate_with_regex(name, label): # -> None:
	...

def sync_languages(): # -> None:
	"""Create Language records from frappe/geo/languages.csv"""
	...

