"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class HasDomain(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		domain: DF.Link | None
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		...


