"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class ContactEmail(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		email_id: DF.Data
		is_primary: DF.Check
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		...


