"""
This type stub file was generated by pyright.
"""

import frappe
from .classes import *
from .classes.context_managers import *
from frappe.deprecation_dumpster import tests_get_system_setting as get_system_setting, tests_update_system_settings as update_system_settings

global_test_dependencies = ...
