"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

FORMATS = ...
FORBIDDEN_DOCUMENT_TYPES = ...
DATE_BASED_EVENTS = ...
class Notification(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		attach_files: DF.Literal["", "From Field", All]
		attach_print: DF.Check
		channel: DF.Literal[Email, Slack, "System Notification", SMS]
		condition: DF.Code | None
		condition_type: DF.Literal[Python, Filters]
		date_changed: DF.Literal[None]
		datetime_changed: DF.Literal[None]
		datetime_last_run: DF.Datetime | None
		days_in_advance: DF.Int
		document_type: DF.Link
		enabled: DF.Check
		event: DF.Literal["", New, Save, Submit, Cancel, "Days After", "Days Before", "Minutes After", "Minutes Before", "Value Change", Method,]
		filters: DF.Code | None
		from_attach_field: DF.Literal[None]
		is_standard: DF.Check
		message: DF.Code | None
		message_type: DF.Literal[Markdown, HTML, "Plain Text"]
		method: DF.Data | None
		minutes_offset: DF.Int
		module: DF.Link | None
		print_format: DF.Link | None
		property_value: DF.Data | None
		recipients: DF.Table[NotificationRecipient]
		send_system_notification: DF.Check
		send_to_all_assignees: DF.Check
		sender: DF.Link | None
		sender_email: DF.Data | None
		set_property_after_alert: DF.Literal[None]
		slack_webhook_url: DF.Link | None
		subject: DF.Data | None
		value_changed: DF.Literal[None]
		...
	def onload(self): # -> None:
		"""load message"""
		...
	
	def autoname(self): # -> None:
		...
	
	@frappe.whitelist()
	def preview_meets_condition(self, preview_document: str): # -> str | None:
		...
	
	@frappe.whitelist()
	def preview_message(self, preview_document: str): # -> Any | str | None:
		...
	
	@frappe.whitelist()
	def preview_subject(self, preview_document: str): # -> str | Any | None:
		...
	
	def before_save(self): # -> None:
		...
	
	def validate(self): # -> None:
		...
	
	def clear_cache(self): # -> None:
		...
	
	def on_update(self): # -> None:
		...
	
	def validate_standard(self): # -> None:
		...
	
	def remove_invalid_condition(self): # -> None:
		...
	
	def validate_condition(self): # -> None:
		...
	
	def validate_filters(self): # -> None:
		...
	
	def validate_forbidden_document_types(self): # -> None:
		...
	
	def get_documents_for_today(self): # -> list[Any]:
		"""get list of documents that will be triggered today"""
		...
	
	def get_documents_for_this_moment(self) -> list[Document]:
		"""
		Get list of documents that will be triggered at this moment.

		This method retrieves documents based on the specified datetime field and minutes offset.
		It considers documents that fall within the time range from the last run time plus the offset
		up to the current time plus the offset.

		Returns:
		        list: A list of document objects that meet the criteria for notification.
		"""
		...
	
	def queue_send(self, doc, enqueue_after_commit=...): # -> Job | Any:
		"""
		Enqueue the process to build recipients and send notifications.

		This method is particularly useful for sending notifications, especially 'Custom'-type,
		without the additional overhead associated with `Document.queue_action`.

		Args:
		              doc (Document): The document object for which the notification is being sent.
		              enqueue_after_commit (bool, optional): If True, the task will be enqueued after
		                the current transaction is committed. Defaults to True.

		Note:
		              This method is the recommended way to send 'Custom'-type notifications.

		Example:
		              To queue a notification from a server script:

		              ```python
		              notification = frappe.get_doc(
		                  "Notification", "My Notification", ignore_permissions=True
		              )
		              notification.queue_send(customer)
		              ```

		              This example queues the "My Notification" to be sent for the specified customer document.
		"""
		...
	
	def send(self, doc): # -> None:
		"""Build recipients and send Notification"""
		...
	
	def send_notification_by_channel(self, doc, context): # -> None:
		"""Send notification based on the specified channel."""
		...
	
	def create_system_notification(self, doc, context): # -> None:
		...
	
	def send_an_email(self, doc, context): # -> None:
		...
	
	def send_a_slack_msg(self, doc, context): # -> None:
		...
	
	def send_sms(self, doc, context): # -> None:
		...
	
	@staticmethod
	def get_mobile_no(doc, field): # -> Any:
		...
	
	def get_list_of_recipients(self, doc, context): # -> tuple[list[Any], list[Any], list[Any]]:
		...
	
	def get_receiver_list(self, doc, context, field_on_user=..., recipient_extractor_func=...): # -> list[Any]:
		"""return receiver list based on the doc field and role specified"""
		...
	
	def get_attachment(self, doc) -> list[dict]:
		"""Check Attachment Settings and return attachments accordingly"""
		...
	
	def get_print(self, doc): # -> dict[str, Any] | None:
		"""check print settings and return dict with print info"""
		...
	
	def get_template(self, md_as_html=...): # -> Any | str | None:
		...
	
	def load_standard_properties(self, context): # -> None:
		"""load templates and run get_context"""
		...
	
	def on_trash(self): # -> None:
		...
	
	def delete_notification_folder(self): # -> None:
		...
	


def clear_notification_cache(): # -> None:
	...

@frappe.whitelist()
def get_documents_for_today(notification: str): # -> list[Any]:
	...

def trigger_offset_alerts(): # -> None:
	...

def trigger_daily_alerts(): # -> None:
	...

def trigger_notifications(doc, method=...): # -> None:
	...

def evaluate_alert(doc: Document, alert, event=...): # -> None:
	...

def get_context(doc): # -> dict[str, Any]:
	...

def get_assignees(doc): # -> list[Any]:
	...

def get_emails_from_template(template, context): # -> tuple[()] | filter[str]:
	...

def get_reference_doctype(doc):
	...

def get_reference_name(doc):
	...

def create_notifications(notifications: list[dict], update: bool = ...): # -> None:
	"""
	Unlike standard notifications, these are NOT marked as is_standard=1,
	so they won't be overwritten during migrations. Users can freely customize them.

	Args:
		notifications: List of notification dicts.
		update: If True, update existing notification. If False (default), skip if exists.
	"""
	...

def get_notification_templates(templates_dir: str) -> list[dict]:
	"""
	Load notification templates from the templates directory.

	Templates are stored in subdirectories:
		<templates_dir>/<name>/<name>.json
		<templates_dir>/<name>/<name>.html|.md|.txt (optional message content based on message_type)
	"""
	...

def install_notification_templates(): # -> None:
	...

