"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class UserSessionDisplay(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		id: DF.Data | None
		ip_address: DF.Data | None
		is_current: DF.Check
		last_updated: DF.Datetime | None
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		session_created: DF.Datetime | None
		user_agent: DF.SmallText | None
		...
	def db_insert(self, *args, **kwargs):
		...
	
	def load_from_db(self, *args, **kwargs):
		...
	
	def db_update(self, *args, **kwargs):
		...
	
	def delete(self, *args, **kwargs):
		...
	


