"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

class PrintFormat(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		absolute_value: DF.Check
		align_labels_right: DF.Check
		css: DF.Code | None
		custom_format: DF.Check
		default_print_language: DF.Link | None
		disabled: DF.Check
		doc_type: DF.Link | None
		font: DF.Data | None
		font_size: DF.Int
		format_data: DF.Code | None
		html: DF.Code | None
		line_breaks: DF.Check
		margin_bottom: DF.Float
		margin_left: DF.Float
		margin_right: DF.Float
		margin_top: DF.Float
		module: DF.Link | None
		page_number: DF.Literal[Hide, "Top Left", "Top Center", "Top Right", "Bottom Left", "Bottom Center", "Bottom Right"]
		pdf_generator: DF.Literal[wkhtmltopdf, chrome]
		print_format_builder: DF.Check
		print_format_builder_beta: DF.Check
		print_format_for: DF.Literal[DocType, Report]
		print_format_type: DF.Literal[Jinja, JS]
		raw_commands: DF.Code | None
		raw_printing: DF.Check
		report: DF.Link | None
		show_section_headings: DF.Check
		standard: DF.Literal[No, Yes]
		...
	def onload(self): # -> None:
		...
	
	def before_save(self): # -> None:
		...
	
	def get_html(self, docname, letterhead=...): # -> str | Any | None:
		...
	
	def download_pdf(self, docname, letterhead=...): # -> None:
		...
	
	def validate(self): # -> None:
		...
	
	def extract_images(self): # -> None:
		...
	
	def on_update(self): # -> None:
		...
	
	def after_rename(self, old: str, new: str, *args, **kwargs): # -> None:
		...
	
	def export_doc(self): # -> str | None:
		...
	
	def on_trash(self): # -> None:
		...
	


@frappe.whitelist()
def make_default(name: str): # -> None:
	"""Set print format as default"""
	...

