"""
This type stub file was generated by pyright.
"""

import frappe
from typing import Literal, TYPE_CHECKING
from frappe.database.database import savepoint
from frappe.email.frappemail import FrappeMail
from frappe.email.smtp import SMTPServer
from frappe.model.document import Document

if TYPE_CHECKING:
	...
class EmailQueue(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		add_unsubscribe_link: DF.Check
		attachments: DF.Code | None
		communication: DF.Link | None
		email_account: DF.Link | None
		error: DF.Code | None
		expose_recipients: DF.Data | None
		message: DF.Code | None
		message_id: DF.SmallText | None
		priority: DF.Int
		raw_html: DF.Check
		recipients: DF.Table[EmailQueueRecipient]
		reference_doctype: DF.Link | None
		reference_name: DF.Data | None
		retry: DF.Int
		send_after: DF.Datetime | None
		sender: DF.Data | None
		show_as_cc: DF.SmallText | None
		status: DF.Literal["Not Sent", Sending, Sent, "Partially Sent", Error]
		unsubscribe_method: DF.Data | None
		unsubscribe_params: DF.Code | None
		...
	DOCTYPE = ...
	def onload(self): # -> None:
		...
	
	def set_recipients(self, recipients): # -> None:
		...
	
	def on_trash(self): # -> None:
		...
	
	def prevent_email_queue_delete(self): # -> None:
		...
	
	def get_duplicate(self, recipients): # -> _NewDocument:
		...
	
	@classmethod
	def new(cls, doc_data, ignore_permissions=...) -> EmailQueue:
		...
	
	@classmethod
	def find(cls, name) -> EmailQueue:
		...
	
	@classmethod
	def find_one_by_filters(cls, **kwargs): # -> EmailQueue | None:
		...
	
	def update_db(self, commit=..., **kwargs): # -> None:
		...
	
	def update_status(self, status, commit=..., **kwargs): # -> None:
		...
	
	@property
	def cc(self): # -> list[str]:
		...
	
	@property
	def to(self): # -> list[Data | None]:
		...
	
	@property
	def attachments_list(self): # -> Any | list[Any]:
		...
	
	def get_email_account(self, raise_error=...): # -> Document | dict[str | Any, EmailAccount] | dict[Any, EmailAccount] | dict[str, EmailAccount] | None:
		...
	
	def is_to_be_sent(self): # -> bool:
		...
	
	def can_send_now(self): # -> bool:
		...
	
	def send(self, smtp_server_instance: SMTPServer = ..., frappe_mail_client: FrappeMail = ..., force_send: bool = ...): # -> None:
		"""Send emails to recipients."""
		...
	
	@staticmethod
	def clear_old_logs(days=...): # -> None:
		"""Remove low priority older than 31 days in Outbox or configured in Log Settings.
		Note: Used separate query to avoid deadlock
		"""
		...
	


send_mail = ...
class SendMailContext:
	def __init__(self, queue_doc: Document, smtp_server_instance: SMTPServer = ..., frappe_mail_client: FrappeMail = ...) -> None:
		...
	
	def fetch_outgoing_server(self): # -> None:
		...
	
	def __enter__(self): # -> Self:
		...
	
	def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
		...
	
	@savepoint(catch=Exception)
	def notify_failed_email(self): # -> None:
		...
	
	def update_recipient_status_to_sent(self, recipient): # -> None:
		...
	
	def get_message_object(self, message): # -> EmailMessage[Any, Any]:
		...
	
	def message_placeholder(self, placeholder_key): # -> str | None:
		...
	
	def build_message(self, recipient_email) -> bytes:
		"""Build message specific to the recipient."""
		...
	
	def get_tracker_str(self, recipient_email) -> str:
		...
	
	def get_unsubscribe_str(self, recipient_email: str) -> str:
		...
	
	def get_receivers_str(self): # -> str:
		...
	
	def get_recipient_str(self, recipient_email): # -> Literal['']:
		...
	
	def include_attachments(self, message): # -> bytes | str:
		...
	


@frappe.whitelist()
def retry_sending(queues: str | list[str]): # -> None:
	...

@frappe.whitelist()
def send_now(name: str | int, force_send: bool = ...): # -> None:
	...

@frappe.whitelist()
def toggle_sending(enable: bool | int | str): # -> None:
	...

def on_doctype_update(): # -> None:
	"""Add index in `tabCommunication` for `(reference_doctype, reference_name)`"""
	...

def get_email_retry_limit(): # -> int:
	...

class QueueBuilder:
	"""Builds Email Queue from the given data"""
	def __init__(self, recipients=..., sender=..., subject=..., message=..., text_content=..., reference_doctype=..., reference_name=..., unsubscribe_method=..., unsubscribe_params=..., unsubscribe_message=..., attachments=..., reply_to=..., cc=..., bcc=..., message_id=..., in_reply_to=..., send_after=..., expose_recipients=..., send_priority=..., communication=..., read_receipt=..., queue_separately=..., is_notification=..., add_unsubscribe_link=..., inline_images=..., header=..., print_letterhead=..., with_container=..., email_read_tracker_url=..., x_priority: Literal[1, 3, 5] = ..., email_headers=..., raw_html=..., add_css=...) -> None:
		"""Add email to sending queue (Email Queue)

		:param recipients: List of recipients.
		:param sender: Email sender.
		:param subject: Email subject.
		:param message: Email message.
		:param text_content: Text version of email message.
		:param reference_doctype: Reference DocType of caller document.
		:param reference_name: Reference name of caller document.
		:param send_priority: Priority for Email Queue, default 1.
		:param unsubscribe_method: URL method for unsubscribe. Default is `/api/method/frappe.email.queue.unsubscribe`.
		:param unsubscribe_params: additional params for unsubscribed links. default are name, doctype, email
		:param attachments: Attachments to be sent.
		:param reply_to: Reply to be captured here (default inbox)
		:param in_reply_to: Used to send the Message-Id of a received email back as In-Reply-To.
		:param send_after: Send this email after the given datetime. If value is in integer, then `send_after` will be the automatically set to no of days from current date.
		:param communication: Communication link to be set in Email Queue record
		:param queue_separately: Queue each email separately (one per recipient). When True, each TO recipient
		receives an individual email. Note: If CC/BCC are provided with queue_separately=True, CC/BCC
		recipients will receive one email for each TO recipient(duplicates), as each TO email is a separate message
		that includes CC/BCC. To avoid this, either don't use queue_separately, or add CC/BCC recipients
		to the recipients list instead.
		:param is_notification: Marks email as notification so will not trigger notifications from system
		:param add_unsubscribe_link: Send unsubscribe link in the footer of the Email, default 1.
		:param inline_images: List of inline images as {"filename", "filecontent"}. All src properties will be replaced with random Content-Id
		:param header: Append header in email (boolean)
		:param with_container: Wraps email inside styled container
		:param email_read_tracker_url: A URL for tracking whether an email is read by the recipient.
		:param x_priority: 1 = HIGHEST, 3 = NORMAL, 5 = LOWEST
		:param email_headers: Additional headers to be added in the email, e.g. {"X-Custom-Header": "value"} or {"Custom-Header": "value"}. Automatically prepends "X-" to the header name if not present.
		:param raw_html: Whether to treat email template as a complete HTML file
		:param add_css: Add default CSS from hooks/email_css to the email template (default True)
		"""
		...
	
	@property
	def unsubscribe_method(self): # -> Literal['/api/method/frappe.email.queue.unsubscribe']:
		...
	
	@property
	def recipients(self): # -> list[Any]:
		...
	
	@property
	def cc(self): # -> list[Any]:
		...
	
	@property
	def bcc(self): # -> list[Any]:
		...
	
	@property
	def send_after(self): # -> DateTimeLikeObject | None:
		...
	
	@property
	def sender(self):
		...
	
	def email_text_content(self): # -> str:
		...
	
	def email_html_content(self):
		...
	
	def should_include_unsubscribe_link(self): # -> Literal[False] | None:
		...
	
	def unsubscribe_message(self): # -> _dict[str, str] | None:
		...
	
	def get_outgoing_email_account(self): # -> dict[str | Any, EmailAccount] | dict[Any, EmailAccount] | dict[str, EmailAccount] | None:
		...
	
	def get_unsubscribed_user_emails(self): # -> list[Any]:
		...
	
	def final_recipients(self): # -> list[Any]:
		...
	
	def final_cc(self): # -> list[Any]:
		...
	
	def final_bcc(self): # -> list[Any]:
		...
	
	def get_attachments(self): # -> list[Any]:
		...
	
	def prepare_email_content(self): # -> EMail:
		...
	
	def process(self, send_now=...) -> EmailQueue | None:
		"""Build and return the email queues those are created.

		Sends email incase if it is requested to send now.
		"""
		...
	
	def send_emails(self, queue_data, final_recipients): # -> None:
		"""
		Send emails to recipients separately.

		Note: CC/BCC recipients are included in each email sent to TO recipients.
		This means CC/BCC will receive one email per TO recipient. This is expected
		behavior because queue_separately creates individual emails for each TO
		recipient, and CC/BCC are copied on each individual email.

		"""
		...
	
	def as_dict(self, include_recipients=...): # -> dict[str, Any] | None:
		...
	


