"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class Comment(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		comment_by: DF.Data | None
		comment_email: DF.Data | None
		comment_type: DF.Literal[Comment, Like, Info, Label, Workflow, Created, Submitted, Cancelled, Updated, Deleted, Assigned, "Assignment Completed", Attachment, "Attachment Removed", Shared, Unshared, Bot, Relinked, Edit,]
		content: DF.HTMLEditor | None
		ip_address: DF.Data | None
		published: DF.Check
		reference_doctype: DF.Link | None
		reference_name: DF.DynamicLink | None
		reference_owner: DF.Data | None
		seen: DF.Check
		subject: DF.Text | None
		...
	no_feed_on_delete = ...
	def after_insert(self): # -> None:
		...
	
	def validate(self): # -> None:
		...
	
	def on_update(self): # -> None:
		...
	
	def on_trash(self): # -> None:
		...
	
	def notify_change(self, action): # -> None:
		...
	
	def remove_comment_from_cache(self): # -> None:
		...
	


def on_doctype_update(): # -> None:
	...

def update_comment_in_doc(doc): # -> None:
	"""Updates `_comments` (JSON) property in parent Document.
	Creates a column `_comments` if property does not exist.

	Only user created Communication or Comment of type Comment are saved.

	`_comments` format

	        {
	                "comment": [String],
	                "by": [user],
	                "name": [Comment Document name]
	        }"""
	...

def get_comments_from_parent(doc): # -> Any | list[Any]:
	"""
	get the list of comments cached in the document record in the column
	`_comments`
	"""
	...

def update_comments_in_parent(reference_doctype, reference_name, _comments): # -> None:
	"""Updates `_comments` property in parent Document with given dict.

	:param _comments: Dict of comments."""
	...

