"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.core.doctype.file.file import File

@frappe.whitelist()
def unzip_file(name: str): # -> list[File]:
	"""Unzip the given file and make file records for each of the extracted files"""
	...

@frappe.whitelist()
def get_attached_images(doctype: str, names: list[str] | str) -> frappe._dict:
	"""Return list of image urls attached in form `{name: ['image.jpg', 'image.png']}`."""
	...

@frappe.whitelist()
def get_files_in_folder(folder: str, start: int = ..., page_length: int = ...) -> dict:
	...

@frappe.whitelist()
def get_files_by_search_text(text: str) -> list[dict]:
	...

@frappe.whitelist(allow_guest=True)
def get_max_file_size() -> int:
	...

def get_file_chunk_size() -> int:
	...

@frappe.whitelist()
def create_new_folder(file_name: str, folder: str) -> File:
	"""create new folder under current parent folder"""
	...

@frappe.whitelist()
def move_file(file_list: list[File | dict] | str, new_parent: str, old_parent: str) -> None:
	...

@frappe.whitelist()
def zip_files(files: str): # -> None:
	...

