"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class AssignmentRuleUser(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		user: DF.Link
		weight: DF.Int
		...


