"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class LogsToClear(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		days: DF.Int
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		ref_doctype: DF.Link
		...


