"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from contextlib import contextmanager
from typing import Any, TYPE_CHECKING
from .integration_test_case import IntegrationTestCase
from .unit_test_case import UnitTestCase
from frappe.model import Document

if TYPE_CHECKING:
	...
logger = ...
@UnitTestCase.registerAs(staticmethod)
@contextmanager
def freeze_time(time_to_freeze: Any, is_utc: bool = ..., *args: Any, **kwargs: Any) -> None:
	"""Temporarily: freeze time with freezegun."""
	...

@UnitTestCase.registerAs(staticmethod)
@contextmanager
def set_user(user: str): # -> Generator[None, Any, None]:
	"""Temporarily: set the user."""
	...

@UnitTestCase.registerAs(staticmethod)
@contextmanager
def patch_hooks(overridden_hooks: dict) -> None:
	"""Temporarily: patch a hook."""
	...

@IntegrationTestCase.registerAs(staticmethod)
@contextmanager
def change_settings(doctype, settings_dict=..., /, commit=..., **settings) -> None:
	"""Temporarily: change settings in a settings doctype."""
	...

@IntegrationTestCase.registerAs(staticmethod)
@contextmanager
def switch_site(site: str) -> None:
	"""Temporarily: drop current connection and switch to a different site."""
	...

@UnitTestCase.registerAs(staticmethod)
@contextmanager
def enable_safe_exec() -> None:
	"""Temporarily: enable safe exec (server scripts)."""
	...

@UnitTestCase.registerAs(staticmethod)
@contextmanager
def debug_on(*exceptions) -> None:
	"""Temporarily: enter an interactive debugger on specified exceptions, default: (AssertionError,)."""
	...

@UnitTestCase.registerAs(staticmethod)
@contextmanager
def timeout_context(seconds=..., error_message=...) -> None:
	"""Temporarily: timeout an operation."""
	...

def timeout(seconds=..., error_message=...): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any] | Callable[..., _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]]:
	"""Timeout decorator to ensure a test doesn't run for too long."""
	...

@UnitTestCase.registerAs(staticmethod)
@contextmanager
def trace_fields(doc_class: type, field_name: str | None = ..., forbidden_values: list | None = ..., custom_validation: Callable | None = ..., **field_configs: dict[str, list | Callable | None]) -> Document:
	"""
	A context manager for temporarily tracing fields in a DocType.

	Can be used in two ways:
	1. Tracing a single field:
	   trace_fields(DocType, "field_name", forbidden_values=[...], custom_validation=...)
	2. Tracing multiple fields:
	   trace_fields(DocType, field1={"forbidden_values": [...], "custom_validation": ...}, ...)

	Args:
	    doc_class (Document): The DocType class to modify.
	    field_name (str, optional): The name of the field to trace (for single field tracing).
	    forbidden_values (list, optional): A list of forbidden values for the field (for single field tracing).
	    custom_validation (callable, optional): A custom validation function (for single field tracing).
	    **field_configs: Keyword arguments for multiple field tracing, where each key is a field name and
	                     the value is a dict containing 'forbidden_values' and/or 'custom_validation'.

	Yields:
	    Document class
	"""
	...

__all__ = ["change_settings", "debug_on", "enable_safe_exec", "freeze_time", "patch_hooks", "set_user", "switch_site", "timeout", "timeout_context", "trace_fields"]
