"""
This type stub file was generated by pyright.
"""

from contextlib import AbstractContextManager, contextmanager
from .unit_test_case import UnitTestCase

logger = ...
STUCK_TEST_THRESHOLD = ...
class IntegrationTestCase(UnitTestCase):
	"""Integration test class for Frappe tests.

	Key features:
	- Automatic database setup and teardown
	- Utilities for managing database connections
	- Context managers for query counting and Redis call monitoring
	- Lazy loading of test record dependencies

	Note: If you override `setUpClass`, make sure to call `super().setUpClass()`
	to maintain the functionality of this base class.
	"""
	TEST_SITE = ...
	SHOW_TRANSACTION_COMMIT_WARNINGS = ...
	maxDiff = ...
	@classmethod
	def setUpClass(cls) -> None:
		...
	
	@classmethod
	def tearDownClass(cls) -> None:
		...
	
	def setUp(self) -> None:
		...
	
	def tearDown(self) -> None:
		...
	
	@contextmanager
	def primary_connection(self) -> AbstractContextManager[None]:
		"""Switch to primary DB connection

		This is used for simulating multiple users performing actions by simulating two DB connections"""
		...
	
	@contextmanager
	def secondary_connection(self) -> AbstractContextManager[None]:
		"""Switch to secondary DB connection."""
		...
	
	@contextmanager
	def assertQueryCount(self, count: int, query_type: tuple[str] | None = ...): # -> Generator[None, Any, None]:
		...
	
	@contextmanager
	def assertRedisCallCounts(self, count: int, *, exact=...) -> AbstractContextManager[None]:
		...
	
	@contextmanager
	def assertRowsRead(self, count: int) -> AbstractContextManager[None]:
		...
	


