"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class NumberCardLink(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		card: DF.Link | None
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		...


