"""
This type stub file was generated by pyright.
"""

def setup_database(): # -> None:
	...

def bootstrap_database(verbose, source_sql=...): # -> None:
	...

def import_db_from_sql(source_sql=..., verbose=...): # -> None:
	...

def get_root_connection(): # -> Any:
	...

def drop_user_and_database(db_name, db_user): # -> None:
	...

