"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class EmailQueueRecipient(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		error: DF.Code | None
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		recipient: DF.Data | None
		status: DF.Literal["", "Not Sent", Sent]
		...
	DOCTYPE = ...
	def is_mail_to_be_sent(self): # -> bool:
		...
	
	def is_mail_sent(self): # -> bool:
		...
	
	def update_db(self, commit=..., **kwargs): # -> None:
		...
	


def on_doctype_update(): # -> None:
	"""Index required for log clearing, modified is not indexed on child table by default"""
	...

