"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class CustomDocPerm(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		amend: DF.Check
		cancel: DF.Check
		create: DF.Check
		delete: DF.Check
		email: DF.Check
		export: DF.Check
		if_owner: DF.Check
		mask: DF.Check
		parent: DF.Data | None
		permlevel: DF.Int
		print: DF.Check
		read: DF.Check
		report: DF.Check
		role: DF.Link
		select: DF.Check
		share: DF.Check
		submit: DF.Check
		write: DF.Check
		...
	def on_update(self): # -> None:
		...
	
	def get_permission_log_options(self, event=...): # -> dict[str, Any]:
		...
	


def update_custom_docperm(docperm, values): # -> None:
	...

