"""
This type stub file was generated by pyright.
"""

import ldap3
import frappe
from typing import TYPE_CHECKING
from ldap3.abstract.entry import Entry
from frappe.model.document import Document
from frappe.core.doctype.user.user import User

if TYPE_CHECKING:
	...
class LDAPSettings(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		base_dn: DF.Data
		default_role: DF.Link | None
		default_user_type: DF.Link
		do_not_create_new_user: DF.Check
		enabled: DF.Check
		ldap_custom_group_search: DF.Data | None
		ldap_directory_server: DF.Literal["", "Active Directory", OpenLDAP, Custom]
		ldap_email_field: DF.Data
		ldap_first_name_field: DF.Data
		ldap_group_field: DF.Data | None
		ldap_group_member_attribute: DF.Data | None
		ldap_group_objectclass: DF.Data | None
		ldap_groups: DF.Table[LDAPGroupMapping]
		ldap_last_name_field: DF.Data | None
		ldap_middle_name_field: DF.Data | None
		ldap_mobile_field: DF.Data | None
		ldap_phone_field: DF.Data | None
		ldap_search_path_group: DF.Data
		ldap_search_path_user: DF.Data
		ldap_search_string: DF.Data
		ldap_server_url: DF.Data
		ldap_username_field: DF.Data
		local_ca_certs_file: DF.Data | None
		local_private_key_file: DF.Data | None
		local_server_certificate_file: DF.Data | None
		password: DF.Password
		require_trusted_certificate: DF.Literal[No, Yes]
		ssl_tls_mode: DF.Literal[Off, StartTLS]
		...
	def validate(self): # -> None:
		...
	
	def connect_to_ldap(self, base_dn, password, read_only=...) -> ldap3.Connection:
		...
	
	@staticmethod
	def get_ldap_client_settings() -> dict:
		...
	
	@classmethod
	def update_user_fields(cls, user: User, user_data: dict): # -> None:
		...
	
	def sync_roles(self, user: User, additional_groups: list | None = ...): # -> None:
		...
	
	def create_or_update_user(self, user_data: dict, groups: list | None = ...): # -> User:
		...
	
	def get_ldap_attributes(self): # -> list[Data]:
		...
	
	def fetch_ldap_groups(self, user: Entry, conn: ldap3.Connection) -> list:
		...
	
	def authenticate(self, username: str, password: str): # -> User | None:
		...
	
	def reset_password(self, user: str, password: str, logout_sessions: int = ...): # -> None:
		...
	
	def convert_ldap_entry_to_dict(self, user_entry: Entry): # -> dict[str, Any]:
		...
	


@frappe.whitelist(allow_guest=True)
def login(): # -> Literal[False] | None:
	...

@frappe.whitelist()
def reset_password(user: str, password: str, logout: int): # -> None:
	...

