"""
This type stub file was generated by pyright.
"""

import MySQLdb
import frappe
from contextlib import contextmanager
from frappe.database.database import Database

ER_STATEMENT_TIMEOUT = ...
class MariaDBExceptionUtil:
	ProgrammingError = MySQLdb.ProgrammingError
	TableMissingError = MySQLdb.ProgrammingError
	OperationalError = MySQLdb.OperationalError
	InternalError = MySQLdb.InternalError
	SQLError = MySQLdb.ProgrammingError
	DataError = MySQLdb.DataError
	InterfaceError = MySQLdb.InterfaceError
	SequenceGeneratorLimitExceeded = MySQLdb.OperationalError
	@staticmethod
	def is_deadlocked(e: MySQLdb.Error) -> bool:
		...
	
	@staticmethod
	def is_timedout(e: MySQLdb.Error) -> bool:
		...
	
	@staticmethod
	def is_read_only_mode_error(e: MySQLdb.Error) -> bool:
		...
	
	@staticmethod
	def is_table_missing(e: MySQLdb.Error) -> bool:
		...
	
	@staticmethod
	def is_missing_table(e: MySQLdb.Error) -> bool:
		...
	
	@staticmethod
	def is_missing_column(e: MySQLdb.Error) -> bool:
		...
	
	@staticmethod
	def is_duplicate_fieldname(e: MySQLdb.Error) -> bool:
		...
	
	@staticmethod
	def is_duplicate_entry(e: MySQLdb.Error) -> bool:
		...
	
	@staticmethod
	def is_access_denied(e: MySQLdb.Error) -> bool:
		...
	
	@staticmethod
	def cant_drop_field_or_key(e: MySQLdb.Error) -> bool:
		...
	
	@staticmethod
	def is_syntax_error(e: MySQLdb.Error) -> bool:
		...
	
	@staticmethod
	def is_statement_timeout(e: MySQLdb.Error) -> bool:
		...
	
	@staticmethod
	def is_data_too_long(e: MySQLdb.Error) -> bool:
		...
	
	@staticmethod
	def is_db_table_size_limit(e: MySQLdb.Error) -> bool:
		...
	
	@staticmethod
	def is_primary_key_violation(e: MySQLdb.Error) -> bool:
		...
	
	@staticmethod
	def is_unique_key_violation(e: MySQLdb.Error) -> bool:
		...
	
	@staticmethod
	def is_interface_error(e: MySQLdb.Error): # -> bool:
		...
	


class MariaDBConnectionUtil:
	def get_connection(self): # -> Connection:
		...
	
	def create_connection(self): # -> Connection:
		...
	
	def set_execution_timeout(self, seconds: int): # -> None:
		...
	
	def get_connection_settings(self) -> dict:
		...
	


def escape_frozenset(obj, mapping=...): # -> Any:
	...

def escape_timedelta(obj, mapping=...): # -> str:
	...

def escape_dict(obj, mapping=...):
	...

class MariaDBDatabase(MariaDBConnectionUtil, MariaDBExceptionUtil, Database):
	REGEX_CHARACTER = ...
	CONVERSION_MAP = ...
	default_port = ...
	MAX_ROW_SIZE_LIMIT = ...
	def setup_type_map(self): # -> None:
		...
	
	def get_database_size(self): # -> None:
		"""Return database size in MB."""
		...
	
	def log_query(self, query, query_type, values, debug):
		...
	
	@staticmethod
	def escape(s, percent=...): # -> str:
		"""Escape quotes and percent in given string."""
		...
	
	@staticmethod
	def is_type_number(code):
		...
	
	@staticmethod
	def is_type_datetime(code):
		...
	
	def rename_table(self, old_name: str, new_name: str) -> list | tuple:
		...
	
	def describe(self, doctype: str) -> list | tuple:
		...
	
	def change_column_type(self, doctype: str, column: str, type: str, nullable: bool = ...) -> list | tuple:
		...
	
	def rename_column(self, doctype: str, old_column_name, new_column_name): # -> None:
		...
	
	def create_auth_table(self): # -> None:
		...
	
	def create_global_search_table(self): # -> None:
		...
	
	def create_user_settings_table(self): # -> None:
		...
	
	@staticmethod
	def get_on_duplicate_update(): # -> Literal['ON DUPLICATE key UPDATE ']:
		...
	
	def get_table_columns_description(self, table_name): # -> str | tuple[()] | Generator[Any | _dict[Incomplete | str | Any, Any] | list[Any], Any, None] | list[Any] | list[_dict[Any, Any]] | list[list[Any]] | tuple[tuple[Any, ...]] | None:
		"""Return list of columns with descriptions."""
		...
	
	def get_column_type(self, doctype, column):
		"""Return column type from database."""
		...
	
	def has_index(self, table_name, index_name): # -> str | tuple[()] | Generator[Any | _dict[Incomplete | str | Any, Any] | list[Any], Any, None] | list[Any] | list[_dict[Any, Any]] | list[list[Any]] | tuple[tuple[Any, ...]] | None:
		...
	
	def get_column_index(self, table_name: str, fieldname: str, unique: bool = ...) -> frappe._dict | None:
		"""Check if column exists for a specific fields in specified order.

		This differs from db.has_index because it doesn't rely on index name but columns inside an
		index.
		"""
		...
	
	def add_index(self, doctype: str, fields: list, index_name: str | None = ...): # -> None:
		"""Creates an index with given fields if not already created.
		Index name will be `fieldname1_fieldname2_index`"""
		...
	
	def add_unique(self, doctype, fields, constraint_name=...): # -> None:
		...
	
	def updatedb(self, doctype, meta=...): # -> None:
		"""
		Syncs a `DocType` to the table
		* creates if required
		* updates columns
		* updates indices
		"""
		...
	
	def get_database_list(self): # -> str | tuple[()] | Generator[Any | _dict[Incomplete | str | Any, Any] | list[Any], Any, None] | list[Any] | list[_dict[Any, Any]] | list[list[Any]] | tuple[tuple[Any, ...]] | None:
		...
	
	def get_tables(self, cached=...): # -> Any | None:
		"""Return list of tables."""
		...
	
	def get_row_size(self, doctype: str) -> int:
		"""Get estimated max row size of any table in bytes."""
		...
	
	@contextmanager
	def unbuffered_cursor(self): # -> Generator[None, Any, None]:
		...
	


