"""
This type stub file was generated by pyright.
"""

from frappe.database.schema import DBTable

class MariaDBTable(DBTable):
	def create(self): # -> None:
		...
	
	def alter(self): # -> None:
		...
	
	def alter_primary_key(self) -> str | None:
		...
	


