"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from babel.messages.catalog import Catalog

PO_DIR = ...
POT_FILE = ...
def new_catalog(app: str, locale: str | None = ...) -> Catalog:
	...

def get_po_dir(app: str) -> Path:
	...

def get_locale_dir() -> Path:
	...

def get_locales(app: str) -> list[str]:
	...

def get_po_path(app: str, locale: str | None = ...) -> Path:
	...

def get_mo_path(app: str, locale: str | None = ...) -> Path:
	...

def get_pot_path(app: str) -> Path:
	...

def get_catalog(app: str, locale: str | None = ...) -> Catalog:
	"""Returns a catatalog for the given app and locale"""
	...

def write_catalog(app: str, catalog: Catalog, locale: str | None = ...) -> Path:
	"""Writes a catalog to the given app and locale"""
	...

def write_binary(app: str, catalog: Catalog, locale: str) -> Path:
	...

def get_method_map(app: str): # -> list[tuple[str, str]] | list[Any]:
	...

def generate_pot(target_app: str | None = ...): # -> None:
	"""
	Generate a POT (PO template) file. This file will contain only messages IDs.
	https://en.wikipedia.org/wiki/Gettext
	:param target_app: If specified, limit to `app`
	"""
	...

def get_is_gitignored_function_for_app(app: str | None): # -> Callable[..., bool]:
	"""
	Used to check if a directory is gitignored or not.
	Can NOT be used to check if a file is gitignored or not.
	"""
	...

def new_po(locale, target_app: str | None = ...): # -> None:
	...

def compile_translations(target_app: str | None = ..., locale: str | None = ..., force=...): # -> None:
	...

def update_po(target_app: str | None = ..., locale: str | None = ...): # -> None:
	"""
	Add keys to available PO files, from POT file. This could be used to keep
	track of available keys, and missing translations
	:param target_app: Limit operation to `app`, if specified
	"""
	...

def migrate(app: str | None = ..., locale: str | None = ...): # -> None:
	...

def csv_to_po(app: str, locale: str): # -> None:
	...

def get_translations_from_mo(lang, app): # -> dict[Any, Any]:
	"""Get translations from MO files.

	For dialects (i.e. es_GT), take translations from the base language (i.e. es)
	and then update with specific translations from the dialect (i.e. es_GT).

	If we only have a translation with context, also use it as a translation
	without context. This way we can provide the context for each source string
	but don't have to create a translation for each context.
	"""
	...

def escape_percent(s: str): # -> str:
	...

