"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class WebPageBlock(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		add_background_image: DF.Check
		add_border_at_bottom: DF.Check
		add_border_at_top: DF.Check
		add_bottom_padding: DF.Check
		add_container: DF.Check
		add_shade: DF.Check
		add_top_padding: DF.Check
		background_image: DF.AttachImage | None
		css_class: DF.SmallText | None
		hide_block: DF.Check
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		section_id: DF.Data | None
		web_template: DF.Link | None
		web_template_values: DF.Code | None
		...


