"""
This type stub file was generated by pyright.
"""

def anonymize_user(user): # -> str:
	"""
	Create consistent anonymous ID from user email.
	Same email always produces same anonymous ID.
	"""
	...

def parse_interval(interval): # -> int | None:
	"""
	Parse interval string or integer into seconds.

	Args:
	    interval: Can be:
	        - Integer: seconds (e.g., 3600)
	        - String: number + unit (e.g., "1h", "30m", "7d")

	Returns:
	    int: Total seconds

	Examples:
	    parse_interval(3600) -> 3600
	    parse_interval("1h") -> 3600
	    parse_interval("30m") -> 1800
	    parse_interval("7d") -> 604800
	"""
	...

def utc_iso() -> str:
	...

def ensure_http(url: str) -> str:
	...

