"""
This type stub file was generated by pyright.
"""

import frappe
from typing import Literal

ENDPOINTS = ...
def get_oauth_server(): # -> Server | Any:
	...

def sanitize_kwargs(param_kwargs):
	"""Remove 'data' and 'cmd' keys, if present."""
	...

def encode_params(params): # -> str:
	"""
	Encode a dict of params into a query string.

	Use `quote_via=urllib.parse.quote` so that whitespaces will be encoded as
	`%20` instead of as `+`. This is needed because oauthlib cannot handle `+`
	as a whitespace.
	"""
	...

@frappe.whitelist()
def approve(*args, **kwargs): # -> None:
	...

@frappe.whitelist(allow_guest=True)
def authorize(**kwargs): # -> None:
	...

@frappe.whitelist(allow_guest=True)
def get_token(*args, **kwargs): # -> None:
	...

@frappe.whitelist(allow_guest=True)
def revoke_token(*args, **kwargs): # -> None:
	...

@frappe.whitelist()
def openid_profile(*args, **kwargs): # -> None:
	...

def get_openid_configuration(): # -> Response:
	...

@frappe.whitelist(allow_guest=True)
def introspect_token(token: str, token_type_hint: str | None = ...): # -> None:
	...

def handle_wellknown(path: str): # -> Response:
	"""Path handler for GET requests to /.well-known/ endpoints. Invoked in app.py"""
	...

def get_authorization_server_metadata(): # -> Response:
	"""
	Creates response for the /.well-known/oauth-authorization-server endpoint.

	Reference: https://datatracker.ietf.org/doc/html/rfc8414
	"""
	...

@frappe.whitelist(allow_guest=True, methods=["POST"])
def register_client(): # -> Response:
	"""
	Registers an OAuth client.

	Reference: https://datatracker.ietf.org/doc/html/rfc7591
	"""
	...

def get_protected_resource_metadata(): # -> Response:
	"""
	Creates response for the /.well-known/oauth-protected-resource endpoint.

	Reference: https://datatracker.ietf.org/doc/html/rfc9728
	"""
	...

def is_oauth_metadata_enabled(label: Literal["resource", "auth_server"]): # -> bool:
	...

def get_resource_url(): # -> str:
	"""Uses request URL to reflect the resource URL"""
	...

def set_cors_for_privileged_requests(): # -> None:
	"""
	Called in before_request hook, prevents failure of privileged requests,
	for OPTIONS and:
	1. GET requests on /.well-known/
	2. POST requests on /api/method/frappe.integrations.oauth2.register_client

	Point 2. also depends on OAuth Settings for dynamic client registration.
	Without these, registration requests from public clients will fail due to
	preflight requests failing.
	"""
	...

