"""
This type stub file was generated by pyright.
"""

from pydantic import BaseModel, HttpUrl

class OAuth2DynamicClientMetadata(BaseModel):
	"""
	OAuth 2.0 Dynamic Client Registration Metadata.

	As defined in RFC7591 - OAuth 2.0 Dynamic Client Registration Protocol
	https://datatracker.ietf.org/doc/html/rfc7591#section-2
	"""
	redirect_uris: list[HttpUrl]
	token_endpoint_auth_method: str | None = ...
	grant_types: list[str] | None = ...
	response_types: list[str] | None = ...
	client_name: str
	scope: str | None = ...
	client_uri: HttpUrl | None = ...
	logo_uri: HttpUrl | None = ...
	contacts: list[str] | None = ...
	tos_uri: HttpUrl | None = ...
	policy_uri: HttpUrl | None = ...
	software_id: str | None = ...
	software_version: str | None = ...
	jwks_uri: HttpUrl | None = ...
	jwks: dict | None = ...


def make_request(method: str, url: str, auth=..., headers=..., data=..., json=..., params=...): # -> dict[str, list[str]] | Any | str | None:
	...

def make_get_request(url: str, **kwargs): # -> dict[str, list[str]] | Any | str | None:
	"""Make a 'GET' HTTP request to the given `url` and return processed response.

	You can optionally pass the below parameters:

	* `headers`: Headers to be set in the request.
	* `params`: Query parameters to be passed in the request.
	* `auth`: Auth credentials.
	"""
	...

def make_post_request(url: str, **kwargs): # -> dict[str, list[str]] | Any | str | None:
	"""Make a 'POST' HTTP request to the given `url` and return processed response.

	You can optionally pass the below parameters:

	* `headers`: Headers to be set in the request.
	* `data`: Data to be passed in body of the request.
	* `json`: JSON to be passed in the request.
	* `params`: Query parameters to be passed in the request.
	* `auth`: Auth credentials.
	"""
	...

def make_put_request(url: str, **kwargs): # -> dict[str, list[str]] | Any | str | None:
	"""Make a 'PUT' HTTP request to the given `url` and return processed response.

	You can optionally pass the below parameters:

	* `headers`: Headers to be set in the request.
	* `data`: Data to be passed in body of the request.
	* `json`: JSON to be passed in the request.
	* `params`: Query parameters to be passed in the request.
	* `auth`: Auth credentials.
	"""
	...

def make_patch_request(url: str, **kwargs): # -> dict[str, list[str]] | Any | str | None:
	"""Make a 'PATCH' HTTP request to the given `url` and return processed response.

	You can optionally pass the below parameters:

	* `headers`: Headers to be set in the request.
	* `data`: Data to be passed in body of the request.
	* `json`: JSON to be passed in the request.
	* `params`: Query parameters to be passed in the request.
	* `auth`: Auth credentials.
	"""
	...

def make_delete_request(url: str, **kwargs): # -> dict[str, list[str]] | Any | str | None:
	"""Make a 'DELETE' HTTP request to the given `url` and return processed response.

	You can optionally pass the below parameters:

	* `headers`: Headers to be set in the request.
	* `data`: Data to be passed in body of the request.
	* `json`: JSON to be passed in the request.
	* `params`: Query parameters to be passed in the request.
	* `auth`: Auth credentials.
	"""
	...

def create_request_log(data, integration_type=..., service_name=..., name=..., error=..., request_headers=..., output=..., **kwargs): # -> _NewDocument:
	"""
	DEPRECATED: The parameter integration_type will be removed in the next major release.
	Use is_remote_request instead.
	"""
	...

def get_json(obj): # -> str:
	...

def json_handler(obj): # -> str | None:
	...

def validate_dynamic_client_metadata(client: OAuth2DynamicClientMetadata): # -> LiteralString | None:
	...

def create_new_oauth_client(client: OAuth2DynamicClientMetadata): # -> OAuthClient:
	...

def get_oauth_settings(): # -> _dict[str, Any]:
	"""Return OAuth settings."""
	...

