"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class ContactPhone(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		is_primary_mobile_no: DF.Check
		is_primary_phone: DF.Check
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		phone: DF.Data
		...


