"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from PIL.ImageFile import ImageFile
from requests.models import Response
from frappe.model.document import Document
from .file import File

if TYPE_CHECKING:
	...
def make_home_folder() -> None:
	...

def setup_folder_path(filename: str, new_parent: str) -> None:
	...

def get_extension(filename, extn: str | None = ..., content: bytes | None = ..., response: Response | None = ...) -> str:
	...

def get_local_image(file_url: str) -> tuple[ImageFile, str, str]:
	...

def get_web_image(file_url: str) -> tuple[ImageFile, str, str]:
	...

def delete_file(path: str) -> None:
	"""Delete file from `public folder`"""
	...

def remove_file_by_url(file_url: str, doctype: str | None = ..., name: str | None = ...) -> Document:
	...

def get_content_hash(content: bytes | str) -> str:
	...

def generate_file_name(name: str, suffix: str | None = ..., is_private: bool = ..., content_hash=...) -> str:
	"""Generate conflict-free file name. Suffix will be ignored if name available. If the
	provided suffix doesn't result in an available path, a random suffix will be picked.
	"""
	...

def get_file_name(fname: str, optional_suffix: str | None = ...) -> str:
	...

def extract_images_from_doc(doc: Document, fieldname: str, is_private=...): # -> None:
	...

def extract_images_from_html(doc: Document, content: str, is_private: bool = ...): # -> str:
	...

def get_corrupted_image_msg(): # -> str:
	...

def get_random_filename(content_type: str | None = ...) -> str:
	...

def update_existing_file_docs(doc: File) -> None:
	...

def attach_files_to_document(doc: Document, event) -> None:
	"""Runs on on_update hook of all documents.
	Goes through every file linked with the Attach and Attach Image field and attaches
	the file to the document if not already attached. If no file is found, a new file
	is created.
	"""
	...

def relink_files(doc, fieldname, temp_doc_name): # -> None:
	"""
	Relink files attached to incorrect document name to the new document name
	by check if file with temp name exists that was created in last 60 minutes
	"""
	...

def relink_mismatched_files(doc: Document) -> None:
	...

def decode_file_content(content: bytes) -> bytes:
	...

def find_file_by_url(path: str, name: str | None = ...) -> File | None:
	...

def get_safe_file_name(file_name: str) -> str:
	...

def check_path_safety(base_path: str, requested_path: str) -> bool:
	"""Util to check path safety by ensuring sandboxing and logging unsuccessful attempts"""
	...

