"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

parse_cron = ...
class ScheduledJobType(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		create_log: DF.Check
		cron_format: DF.Data
		frequency: DF.Literal[All, Hourly, "Hourly Long", "Hourly Maintenance", Daily, "Daily Long", "Daily Maintenance", Weekly, "Weekly Long", Monthly, "Monthly Long", Cron, Yearly, Annual,]
		last_execution: DF.Datetime | None
		method: DF.Data
		scheduler_event: DF.Link | None
		server_script: DF.Link | None
		stopped: DF.Check
		...
	def validate(self): # -> None:
		...
	
	def enqueue(self, force=...) -> bool:
		...
	
	def is_event_due(self, current_time=...): # -> bool:
		"""Return true if event is due based on time lapsed since last execution"""
		...
	
	def is_job_in_queue(self) -> bool:
		...
	
	@property
	def rq_job_id(self): # -> str:
		"""Unique ID created to deduplicate jobs with single RQ call."""
		...
	
	@property
	def next_execution(self): # -> datetime:
		...
	
	def get_next_execution(self): # -> datetime:
		...
	
	def execute(self): # -> None:
		...
	
	def log_status(self, status): # -> None:
		...
	
	def update_scheduler_log(self, status): # -> None:
		...
	
	def get_queue_name(self): # -> Literal['long', 'default']:
		...
	
	def on_trash(self): # -> None:
		...
	


@frappe.whitelist()
def execute_event(doc: str): # -> str:
	...

@frappe.whitelist()
def skip_next_execution(doc: str): # -> ScheduledJobType:
	...

def run_scheduled_job(scheduled_job_type: str, job_type: str | None = ...): # -> None:
	"""This is a wrapper function that runs a hooks.scheduler_events method"""
	...

def sync_jobs(hooks: dict | None = ...): # -> None:
	...

def insert_events(scheduler_events: dict) -> list:
	...

def insert_cron_jobs(events: dict) -> list:
	...

def insert_event_jobs(events: list, event_type: str) -> list:
	...

def insert_single_event(frequency: str, event: str, cron_format: str | None = ...): # -> None:
	...

def clear_events(scheduler_events: dict): # -> None:
	...

def on_doctype_update(): # -> None:
	...

