"""
This type stub file was generated by pyright.
"""

from typing import ClassVar

class Browser:
	def __init__(self, generator, print_format, html, options) -> None:
		...
	
	def open(self, generator): # -> None:
		...
	
	def create_browser_context(self): # -> None:
		...
	
	def set_html(self, html): # -> None:
		...
	
	def set_options(self, options): # -> None:
		...
	
	def new_page(self, page_type): # -> Page:
		"""
		# create a new page in the browser inside browser context
		----
		TODO: Implement Deterministic rendering for headless-chrome via DevTools Protocol ( waiting for macos support )
		https://docs.google.com/document/d/1PppegrpXhOzKKAuNlP6XOEnviXFGUiX2hop00Cxcv4o/edit?tab=t.0#bookmark=id.dukbomwxpb3j

		NOTE: In theory this will make it faster but more importantly use less cpu, ram etc.
		"""
		...
	
	def setup_body_page(self): # -> None:
		...
	
	def close_page(self, type): # -> None:
		...
	
	def is_page_no_used(self, soup): # -> bool:
		...
	
	def prepare_header_footer(self): # -> None:
		...
	
	def try_async_header_footer_pdf(self): # -> None:
		...
	
	def prepare_options_for_pdf(self): # -> None:
		...
	
	def get_rendered_header_footer(self, content, type, head, styles, css):
		...
	
	def update_header_footer_page(self): # -> None:
		...
	
	def update_header_footer_page_pd(self): # -> None:
		...
	
	def close(self): # -> None:
		...
	


class PageSize:
	page_sizes: ClassVar[dict[str, tuple[int, int]]] = ...
	@classmethod
	def get(cls, name): # -> dict[str, int] | None:
		...
	


