"""
This type stub file was generated by pyright.
"""

class CDPSocketClient:
	"""
	Manages WebSocket communications with Chrome DevTools Protocol.
	Ensures robust error handling and consistent logging.
	"""
	def __init__(self, websocket_url) -> None:
		...
	
	def connect(self): # -> None:
		"""Open the WebSocket connection and start listening for messages."""
		...
	
	def disconnect(self): # -> None:
		...
	
	def send(self, method, params=..., session_id=..., return_future=...): # -> Task[Future[Any]] | tuple[Any, Any]:
		...
	
	def start_listener(self, method, callback, session_id=..., target_id=..., frame_id=...): # -> tuple[Any, Future[Any], dict[str, Any | None]]:
		"""Register a listener for a specific CDP event with optional filtering."""
		...
	
	def wait_for_event(self, event, timeout=...): # -> None:
		...
	
	def remove_listener(self, method, event): # -> None:
		"""Remove a listener for a specific CDP event."""
		...
	


