"""
This type stub file was generated by pyright.
"""

from typing import ClassVar

class ChromePDFGenerator:
	_instance = ...
	_browsers: ClassVar[list] = ...
	def add_browser(self, browser): # -> None:
		...
	
	def remove_browser(self, browser): # -> None:
		...
	
	def __new__(cls): # -> Self:
		...
	
	def __init__(self) -> None:
		"""Initialize only once."""
		...
	
	def start_chromium_process(self, debug=...): # -> None:
		"""
		Launches Chromium in headless mode with robust logging and error handling.
		chrome switches
		https://peter.sh/experiments/chromium-command-line-switches/

		NOTE: dbus issue in docker
		  https://source.chromium.org/chromium/chromium/src/+/main:content/app/content_main.cc;l=229-241?q=DBUS_SESSION_BUS_ADDRESS&ss=chromium
		"""
		...
	
	def detach_debug_browser(self): # -> None:
		"""
		Detach the generator from an interactive debug Chromium process.

		This keeps the debug browser window available for inspection, while ensuring
		the next PDF request starts with a fresh generator/process instead of reusing
		the old debug session.
		"""
		...
	
	def fetch_devtools_url(self, port): # -> Any | None:
		...
	


