"""
This type stub file was generated by pyright.
"""

TRANSLATE_PATTERN = ...
EXCLUDE_SELECT_OPTIONS = ...
def extract_messages_from_code(code): # -> list[Any]:
	"""
	Extracts translatable strings from a code file
	:param code: code from which translatable files are to be extracted
	"""
	...

def is_translatable(m): # -> bool:
	...

def add_line_number(messages, code): # -> list[Any]:
	...

def extract_messages_from_docfield(doctype: str, field: dict): # -> Generator[tuple[Any, str], Any, None]:
	"""Extract translatable strings from docfield definition.

	`field` should have the following keys:

	- fieldtype: str
	- fieldname: str
	- label: str (optional)
	- description: str (optional)
	- options: str (optional)
	"""
	...

def extract_messages_from_links(doctype: str, links: list[dict]): # -> Generator[tuple[Any, str], Any, None]:
	"""Extract translatable strings from a list of link definitions."""
	...

