"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

class Dashboard(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		cards: DF.Table[NumberCardLink]
		chart_options: DF.Code | None
		charts: DF.Table[DashboardChartLink]
		dashboard_name: DF.Data
		is_default: DF.Check
		is_standard: DF.Check
		module: DF.Link | None
		...
	def on_update(self): # -> None:
		...
	
	def validate(self): # -> None:
		...
	
	def validate_custom_options(self): # -> None:
		...
	


def get_permission_query_conditions(user): # -> str | None:
	...

@frappe.whitelist()
def get_permitted_charts(dashboard_name: str): # -> list[Any]:
	...

@frappe.whitelist()
def get_permitted_cards(dashboard_name: str): # -> list[Any]:
	...

def get_non_standard_charts_in_dashboard(dashboard): # -> list[Any]:
	...

def get_non_standard_cards_in_dashboard(dashboard): # -> list[Any]:
	...

def get_non_standard_warning_message(non_standard_docs_map): # -> str:
	...

