"""
This type stub file was generated by pyright.
"""

import frappe
from typing import Any
from frappe.model.document import Document

class Address(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		address_line1: DF.Data
		address_line2: DF.Data | None
		address_title: DF.Data | None
		address_type: DF.Literal[Billing, Shipping, Office, Personal, Plant, Postal, Shop, Subsidiary, Warehouse, Current, Permanent, Other,]
		city: DF.Data
		country: DF.Link
		county: DF.Data | None
		disabled: DF.Check
		email_id: DF.Data | None
		fax: DF.Data | None
		is_primary_address: DF.Check
		is_shipping_address: DF.Check
		links: DF.Table[DynamicLink]
		phone: DF.Data | None
		pincode: DF.Data | None
		state: DF.Data | None
		...
	def __setup__(self): # -> None:
		...
	
	def autoname(self): # -> None:
		...
	
	def validate(self): # -> None:
		...
	
	def link_address(self): # -> bool:
		"""Link address based on owner"""
		...
	
	def validate_preferred_address(self): # -> None:
		...
	
	def get_display(self): # -> str | None:
		...
	
	def has_link(self, doctype, name): # -> Literal[True] | None:
		...
	
	def has_common_link(self, doc): # -> bool:
		...
	


def get_preferred_address(doctype, name, preferred_key=...): # -> None:
	...

@frappe.whitelist()
def get_default_address(doctype: str, name: str | None, sort_key: str = ...) -> str | None:
	"""Return default Address name for the given doctype, name."""
	...

@frappe.whitelist()
def get_address_display(address_dict: dict | str | None) -> str | None:
	...

def render_address(address: dict | str | None, check_permissions=...) -> str | None:
	...

def get_territory_from_address(address): # -> list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | _dict[Any, Any] | list[Any | None] | None:
	"""Tries to match city, state and country of address to existing territory"""
	...

def get_list_context(context=...): # -> dict[str, Any]:
	...

def get_address_list(doctype, txt, filters, limit_start, limit_page_length=..., order_by=...): # -> list[Any]:
	...

def has_website_permission(doc, ptype, user, verbose=...): # -> Literal[False]:
	"""Return True if there is a related lead or contact related to this document."""
	...

def get_address_templates(address): # -> list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | _dict[Any, Any] | list[Any | None] | None:
	...

def get_company_address(company): # -> _dict[Any, Any]:
	...

@frappe.whitelist()
@frappe.validate_and_sanitize_search_inputs
def address_query(doctype: str, txt: str, searchfield: str, start: int, page_len: int, filters: dict[str, Any]): # -> list[Any]:
	...

def get_condensed_address(doc, no_title=...): # -> LiteralString:
	...

def update_preferred_address(address, field): # -> None:
	...

def get_address_display_list(doctype: str, name: str) -> list[dict]:
	...

