"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class PermissionLog(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		changed_at: DF.Datetime | None
		changed_by: DF.Link | None
		changes: DF.Text | None
		for_doctype: DF.Link
		for_document: DF.DynamicLink
		reference: DF.DynamicLink | None
		reference_type: DF.Link | None
		status: DF.Literal[Updated, Removed, Added, Reset]
		...
	@property
	def changed_at(self): # -> Datetime:
		...
	


def make_perm_log(doc, method=...): # -> None:
	...

def insert_perm_log(doc: Document, doc_before_save: Document = ..., for_doctype: str | None = ..., for_document: str | None = ..., fields: list | tuple | None = ..., custom_changes: dict | None = ...): # -> None:
	"""Log a permission change. When custom_changes is provided (e.g. for reset-to-standard),
	it must be {"from": {...}, "to": {...}} and optionally "status"; doc is used for
	reference/owner only."""
	...

def get_changes(doc: Document, doc_before_save=..., fields=...): # -> tuple[dict[Any, Any], dict[Any, str]] | tuple[dict[Any, str], dict[Any, Any]] | tuple[dict[Any, Any], dict[Any, Any]]:
	...

def get_changes_diff(current_changes, previous_changes): # -> tuple[dict[Any, Any], dict[Any, Any]]:
	...

def get_filtered_changes(changes, filters=...): # -> dict[Any, Any]:
	...

