"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class UserDocumentType(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		amend: DF.Check
		cancel: DF.Check
		create: DF.Check
		delete: DF.Check
		document_type: DF.Link
		email: DF.Check
		is_custom: DF.Check
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		print: DF.Check
		read: DF.Check
		share: DF.Check
		submit: DF.Check
		write: DF.Check
		...


