"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

not_allowed_fieldtype_change = ...
class PropertySetter(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		default_value: DF.Data | None
		doc_type: DF.Link
		doctype_or_field: DF.Literal["", DocField, DocType, "DocType Link", "DocType Action", "DocType State"]
		field_name: DF.Data | None
		is_system_generated: DF.Check
		module: DF.Link | None
		property: DF.Data
		property_type: DF.Data | None
		row_name: DF.Data | None
		value: DF.SmallText | None
		...
	def autoname(self): # -> None:
		...
	
	def validate(self): # -> None:
		...
	
	def on_trash(self): # -> None:
		...
	
	def validate_fieldtype_change(self): # -> None:
		...
	
	def on_update(self): # -> None:
		...
	
	def get_permission_log_options(self, event=...): # -> dict[str, Any] | None:
		...
	


def make_property_setter(doctype, fieldname, property, value, property_type, for_doctype=..., validate_fields_for_doctype=..., is_system_generated=...): # -> _NewDocument:
	...

def delete_property_setter(doc_type, property=..., field_name=..., row_name=...): # -> None:
	"""delete other property setters on this, if this is new"""
	...

def bulk_delete_property_setters(property_setters: list[dict], bypass_hooks: bool = ...): # -> None:
	"""
	Delete property setters.

	:param property_setters: List of filters for Property Setter rows.
	:param bypass_hooks: If `True`, raw delete without doc hooks.

	Example of `property_setters`:
	```
	[
	    {"doctype": "ToDo", "fieldname": "status", "property": "hidden"},
	    {"doctype": "ToDo", "fieldname": "status", "property": "read_only"},
	]
	```

	---

	Note: `doctype` and `fieldname` are mandatory.
	"""
	...

