"""
This type stub file was generated by pyright.
"""

import os
import frappe
from frappe.model.document import Document

if any((os.getenv("CI"), frappe.conf.developer_mode, frappe.conf.allow_tests)):
	...
class ConnectedApp(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		authorization_uri: DF.SmallText | None
		client_id: DF.Data | None
		client_secret: DF.Password | None
		introspection_uri: DF.Data | None
		openid_configuration: DF.Data | None
		provider_name: DF.Data
		query_parameters: DF.Table[QueryParameters]
		redirect_uri: DF.Data | None
		revocation_uri: DF.Data | None
		scopes: DF.Table[OAuthScope]
		token_uri: DF.Data | None
		userinfo_uri: DF.Data | None
		...
	@frappe.whitelist()
	def get_openid_configuration(self): # -> dict[str, list[str]] | Any | str | None:
		...
	
	def validate(self): # -> None:
		...
	
	def get_oauth2_session(self, user=..., init=...): # -> OAuth2Session:
		"""Return an auto-refreshing OAuth2 session which is an extension of a requests.Session()"""
		...
	
	@frappe.whitelist()
	def initiate_web_application_flow(self, user: str | None = ..., success_uri: str | None = ...): # -> str:
		"""Return an authorization URL for the user. Save state in Token Cache."""
		...
	
	def get_user_token(self, user=..., success_uri=...): # -> Document | str:
		"""Return an existing user token or initiate a Web Application Flow."""
		...
	
	def get_token_cache(self, user): # -> Document | None:
		...
	
	def get_scopes(self): # -> list[Data | None]:
		...
	
	def get_query_params(self): # -> dict[Data, Data]:
		...
	
	def get_active_token(self, user=...): # -> Document | None:
		...
	
	def get_backend_app_token(self, include_client_id=...): # -> Document:
		"""Get an Access Token for the Cloud-Registered Service Principal"""
		...
	


@frappe.whitelist(methods=["GET"], allow_guest=True)
def callback(code: str | None = ..., state: str | None = ...): # -> None:
	"""Handle client's code.

	Called during the oauthorization flow by the remote oAuth2 server to
	transmit a code that can be used by the local server to obtain an access
	token.
	"""
	...

@frappe.whitelist()
def has_token(connected_app: str, connected_user: str | None = ...): # -> bool:
	...

