"""
This type stub file was generated by pyright.
"""

from typing import Any
from pypika.functions import DistinctOptionFunction, Function
from pypika.terms import Term
from pypika.utils import builder

class GROUP_CONCAT(DistinctOptionFunction):
	def __init__(self, column: str, alias: str | None = ...) -> None:
		"""[ Implements the group concat function read more about it at https://www.geeksforgeeks.org/mysql-group_concat-function ]
		Args:
		        column (str): [ name of the column you want to concat]
		        alias (Optional[str], optional): [ is this an alias? ]. Defaults to None.
		"""
		...
	
	@builder
	def separator(self, separator: str = ...): # -> None:
		"""Adds a separator to the GROUP_CONCAT function.
		Args:
				separator (str, optional): [separator to be used]. Defaults to ",".
		"""
		...
	
	def get_sql(self, **kwargs): # -> str:
		...
	


class STRING_AGG(DistinctOptionFunction):
	def __init__(self, column: str, separator: str = ..., alias: str | None = ...) -> None:
		"""[ Implements the group concat function read more about it at https://docs.microsoft.com/en-us/sql/t-sql/functions/string-agg-transact-sql?view=sql-server-ver15 ]

		Args:
		        column (str): [ name of the column you want to concat ]
		        separator (str, optional): [separator to be used]. Defaults to ",".
		        alias (Optional[str], optional): [description]. Defaults to None.
		"""
		...
	


class MATCH(DistinctOptionFunction):
	def __init__(self, column: str, *args, **kwargs) -> None:
		"""[ Implementation of Match Against read more about it https://dev.mysql.com/doc/refman/8.0/en/fulltext-search.html#function_match ]

		Args:
		        column (str):[ column to search in ]
		"""
		...
	
	def get_function_sql(self, **kwargs): # -> str:
		...
	
	@builder
	def Against(self, text: str): # -> None:
		"""[ Text that has to be searched against ]

		Args:
		        text (str): [ the text string that we match it against ]
		"""
		...
	


class TO_TSVECTOR(DistinctOptionFunction):
	def __init__(self, column: str, *args, **kwargs) -> None:
		"""[ Implementation of TO_TSVECTOR read more about it https://www.postgresql.org/docs/9.1/textsearch-controls.html]

		Args:
		        column (str): [ column to search in ]
		"""
		...
	
	def get_function_sql(self, **kwargs): # -> str:
		...
	
	@builder
	def Against(self, text: str): # -> None:
		"""[ Text that has to be searched against ]

		Args:
		        text (str): [ the text string that we match it against ]
		"""
		...
	


class ConstantColumn(Term):
	alias = ...
	def __init__(self, value: str) -> None:
		"""Return a pseudo column with the given constant `value` in all the rows."""
		...
	
	def get_sql(self, quote_char: str | None = ..., **kwargs: Any) -> str:
		...
	


class MonthName(Function):
	def __init__(self, field, alias=...) -> None:
		...
	


class Quarter(Function):
	def __init__(self, field, alias=...) -> None:
		...
	


class Month(Function):
	def __init__(self, field, alias=...) -> None:
		...
	


