"""
This type stub file was generated by pyright.
"""

from enum import Enum
from pypika.functions import *
from pypika.terms import ArithmeticExpression, Function

# pypika is bench-injected and has no stub, so `from pypika.functions import *`
# re-exports nothing for pyright. Declare the aggregate functions the app imports
# by name (e.g. `from frappe.query_builder.functions import Count`).
class Count(Function):
	def __init__(self, param, alias=...) -> None: ...

class Concat_ws(Function):
	def __init__(self, *terms, **kwargs) -> None:
		...
	


class Locate(Function):
	def __init__(self, needle, haystack, **kwargs) -> None:
		...
	


class Strpos(Function):
	def __init__(self, needle, haystack, **kwargs) -> None:
		...
	


class Instr(Function):
	def __init__(self, needle, haystack, **kwargs) -> None:
		...
	


Locate = ...
Ifnull = IfNull
class Timestamp(Function):
	def __init__(self, term: str, time=..., alias=...) -> None:
		...
	


class Round(Function):
	def __init__(self, term, decimal=..., **kwargs) -> None:
		...
	


class Truncate(Function):
	def __init__(self, term, decimal, **kwargs) -> None:
		...
	


GroupConcat = ...
Match = ...
class _PostgresTimestamp(ArithmeticExpression):
	def __init__(self, datepart, timepart, alias=...) -> None:
		"""Postgres would need both datepart and timepart to be a string for concatenation"""
		...
	


CombineDatetime = ...
DateFormat = ...
class YearWeek(Function):
	def __init__(self, term) -> None:
		...
	


class _PostgresUnixTimestamp(Extract):
	def __init__(self, field, alias=...) -> None:
		...
	


UnixTimestamp = ...
class _MariaDBJSONExtract(Function):
	def __init__(self, field, path, **kwargs) -> None:
		...
	


class _MariaDBJSONValue(Function):
	def __init__(self, field, path, **kwargs) -> None:
		...
	


class _MariaDBJSONContains(Function):
	def __init__(self, target, candidate, **kwargs) -> None:
		...
	


JSONExtract = ...
JSONValue = ...
JSONContains = ...
class Cast_(Function):
	def __init__(self, value, as_type, alias=...) -> None:
		...
	
	def get_special_params_sql(self, **kwargs): # -> str | None:
		...
	


class SqlFunctions(Enum):
	DayOfYear = ...
	Extract = ...
	Locate = ...
	Count = ...
	Sum = ...
	Avg = ...
	Max = ...
	Min = ...
	Abs = ...
	Timestamp = ...
	IfNull = ...


