"""
This type stub file was generated by pyright.
"""

from typing import Any
from pypika.dialects import SQLLiteValueWrapper
from pypika.queries import QueryBuilder
from pypika.terms import Criterion, Function, ValueWrapper

class NamedParameterWrapper:
	"""Utility class to hold parameter values and keys"""
	__slots__ = ...
	def __init__(self) -> None:
		...
	
	def get_sql(self, param_value: Any, **kwargs) -> str:
		"""Return SQL for a parameter, while adding the real value in a dict.

		Args:
		        param_value (Any): Value of the parameter

		Return:
		        str: parameter used in the SQL query
		"""
		...
	
	def get_parameters(self) -> dict[str, Any]:
		"""Get dict with parameters and values."""
		...
	


class ParameterizedValueWrapper(ValueWrapper):
	"""
	Class to monkey patch ValueWrapper

	Adds functionality to parameterize queries when a `param wrapper` is passed in get_sql()
	"""
	def get_sql(self, quote_char: str | None = ..., secondary_quote_char: str = ..., param_wrapper: NamedParameterWrapper | None = ..., **kwargs: Any) -> str:
		...
	


class SQLiteParameterizedValueWrapper(ParameterizedValueWrapper, SQLLiteValueWrapper):
	...


class ParameterizedFunction(Function):
	"""
	Class to monkey patch pypika.terms.Functions

	Only to pass `param_wrapper` in `get_function_sql`.
	"""
	def get_sql(self, **kwargs: Any) -> str:
		...
	


class SubQuery(Criterion):
	def __init__(self, subq: QueryBuilder, alias: str | None = ...) -> None:
		...
	
	def get_sql(self, **kwg: Any) -> str:
		...
	


subqry = SubQuery
