"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from enum import Enum
from typing import Any
from pypika.queries import QueryBuilder
from pypika.terms import PseudoColumn
from .builder import MariaDB, Postgres, SQLite

class PseudoColumnMapper(PseudoColumn):
	def __init__(self, name: str) -> None:
		...
	
	def get_sql(self, **kwargs): # -> str:
		...
	


class db_type_is(Enum):
	MARIADB = ...
	POSTGRES = ...
	SQLITE = ...


DB_TYPE_MAP = ...
class ImportMapper:
	def __init__(self, func_map: dict[db_type_is, Callable]) -> None:
		...
	
	def __call__(self, *args: Any, **kwds: Any) -> Callable:
		...
	


class BuilderIdentificationFailed(Exception):
	def __init__(self) -> None:
		...
	


def get_query_builder(type_of_db: str) -> Postgres | MariaDB | SQLite:
	"""Return the query builder object.

	Args:
	        type_of_db: string value of the db used
	"""
	...

def get_query(*args, **kwargs) -> QueryBuilder:
	...

def get_attr(method_string): # -> Any:
	...

def DocType(*args, **kwargs): # -> Table:
	...

def Table(*args, **kwargs): # -> _TableClass:
	...

def mask_fields(doctype: str, fields: list[Any], result: list[dict] | list[tuple], as_dict: bool = ...) -> list[dict] | list[tuple]:
	"""Mask fields in the result based on the doctype's masked fields.

	Args:
		doctype: Name of the DocType being queried
		fields: List of field objects from the query
		result: Query results as list of dicts or tuples
		as_dict: Whether results are dictionaries (True) or tuples (False)

	Returns:
		Result with masked field values applied based on user permissions
	"""
	...

def execute_query(query, *args, **kwargs): # -> list[dict[Any, Any]] | list[tuple[Any, ...]] | Any:
	...

def execute_child_queries(queries, result): # -> None:
	...

def prepare_query(query): # -> tuple[str, dict[Any, Any]]:
	...

def patch_query_execute(): # -> None:
	"""Patch the Query Builder with helper execute method
	This excludes the use of `frappe.db.sql` method while
	executing the query object
	"""
	...

def patch_query_aggregation(): # -> None:
	"""Patch aggregation functions to frappe.qb"""
	...

def patch_get_query(): # -> None:
	...

def patch_all(): # -> None:
	...

