"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

class FormTour(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		dashboard_name: DF.Link | None
		first_document: DF.Check
		include_name_field: DF.Check
		is_standard: DF.Check
		list_name: DF.Literal[List, Report, Dashboard, Kanban, Gantt, Calendar, File, Image, Inbox, Map]
		module: DF.Link | None
		new_document_form: DF.Check
		page_name: DF.Link | None
		page_route: DF.SmallText | None
		reference_doctype: DF.Link | None
		report_name: DF.Link | None
		save_on_complete: DF.Check
		steps: DF.Table[FormTourStep]
		title: DF.Data
		track_steps: DF.Check
		ui_tour: DF.Check
		view_name: DF.Literal[Workspaces, List, Form, Tree, Page]
		workspace_name: DF.Link | None
		...
	def before_save(self): # -> None:
		...
	
	def on_update(self): # -> None:
		...
	
	def on_trash(self): # -> None:
		...
	


@frappe.whitelist()
def reset_tour(tour_name: str): # -> None:
	...

@frappe.whitelist()
def update_user_status(value: str, step: str): # -> None:
	...

def get_onboarding_ui_tours(): # -> list[Any] | list[list[Any]]:
	...

