"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

class WebsiteTheme(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		background_color: DF.Link | None
		button_gradients: DF.Check
		button_rounded_corners: DF.Check
		button_shadows: DF.Check
		custom: DF.Check
		custom_overrides: DF.Code | None
		custom_scss: DF.Code | None
		dark_color: DF.Link | None
		font_properties: DF.Data | None
		font_size: DF.Data | None
		google_font: DF.Data | None
		ignored_apps: DF.Table[WebsiteThemeIgnoreApp]
		js: DF.Code | None
		light_color: DF.Link | None
		module: DF.Link
		primary_color: DF.Link | None
		text_color: DF.Link | None
		theme: DF.Data
		theme_scss: DF.Code | None
		theme_url: DF.Data | None
		...
	def validate(self): # -> None:
		...
	
	def on_update(self): # -> None:
		...
	
	def is_standard_and_not_valid_user(self): # -> bool:
		...
	
	def on_trash(self): # -> None:
		...
	
	def validate_if_customizable(self): # -> None:
		...
	
	def export_doc(self): # -> None:
		"""Export to standard folder `[module]/website_theme/[name]/[name].json`."""
		...
	
	def clear_cache_if_current_theme(self): # -> None:
		...
	
	def generate_bootstrap_theme(self): # -> None:
		...
	
	def delete_old_theme_files(self, folder_path): # -> None:
		...
	
	@frappe.whitelist()
	def set_as_default(self): # -> None:
		...
	
	@frappe.whitelist()
	def get_apps(self): # -> list[dict[str, Any]]:
		...
	


def get_active_theme() -> WebsiteTheme | None:
	...

def get_scss(website_theme): # -> str | Any | None:
	"""
	Render `website_theme_template.scss` with the values defined in Website Theme.

	params:
	website_theme - instance of a Website Theme
	"""
	...

def get_scss_paths(): # -> list[Any]:
	"""
	Return a set of SCSS import paths from all apps that provide `website.scss`.

	If `$BENCH_PATH/apps/frappe/frappe/public/scss/website[.bundle].scss` exists, the
	returned set will contain 'frappe/public/scss/website[.bundle]'.
	"""
	...

def after_migrate(): # -> None:
	"""
	Regenerate Active Theme CSS file after migration.

	Necessary to reflect possible changes in the imported SCSS files. Called at
	the end of every `bench migrate`.
	"""
	...

