"""
This type stub file was generated by pyright.
"""

from frappe.utils.caching import redis_cache
from frappe.website.website_generator import WebsiteGenerator

H_TAG_PATTERN = ...
class WebPage(WebsiteGenerator):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		breadcrumbs: DF.Code | None
		content_type: DF.Literal["Rich Text", Markdown, HTML, "Page Builder", Slideshow]
		context_script: DF.Code | None
		css: DF.Code | None
		dynamic_route: DF.Check
		dynamic_template: DF.Check
		enable_comments: DF.Check
		end_date: DF.Datetime | None
		full_width: DF.Check
		header: DF.HTMLEditor | None
		idx: DF.Int
		insert_style: DF.Check
		javascript: DF.Code | None
		main_section: DF.TextEditor | None
		main_section_html: DF.HTMLEditor | None
		main_section_md: DF.MarkdownEditor | None
		meta_description: DF.SmallText | None
		meta_image: DF.AttachImage | None
		meta_title: DF.Data | None
		module: DF.Link | None
		page_blocks: DF.Table[WebPageBlock]
		published: DF.Check
		route: DF.Data | None
		show_sidebar: DF.Check
		show_title: DF.Check
		slideshow: DF.Link | None
		start_date: DF.Datetime | None
		text_align: DF.Literal[Left, Center, Right]
		title: DF.Data
		website_sidebar: DF.Link | None
		...
	def validate(self): # -> None:
		...
	
	def get_context(self, context):
		...
	
	def render_dynamic(self, context): # -> None:
		...
	
	def set_breadcrumbs(self, context): # -> None:
		"""Build breadcrumbs template"""
		...
	
	def set_title_and_header(self, context): # -> None:
		"""Extract and set title and header from content or context."""
		...
	
	def set_page_blocks(self, context): # -> None:
		...
	
	def add_hero(self, context): # -> None:
		"""Add a hero element if specified in content or hooks.
		Hero elements get full page width."""
		...
	
	def check_for_redirect(self, context): # -> None:
		...
	
	def set_metatags(self, context): # -> None:
		...
	
	def validate_dates(self): # -> None:
		...
	


def check_publish_status(): # -> None:
	...

def get_web_blocks_html(blocks): # -> _dict[Any, str | dict[Any, Any]]:
	"""Convert a list of blocks into Raw HTML and extract out their scripts for deduplication."""
	...

def extract_script_and_style_tags(html): # -> tuple[str, list[Any], list[Any]]:
	...

@redis_cache(ttl=60 * 60)
def get_dynamic_web_pages() -> dict[str, str]:
	...

