"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class WorkflowDocumentState(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		allow_edit: DF.Link
		avoid_status_override: DF.Check
		doc_status: DF.Literal[0, 1, 2]
		evaluate_as_expression: DF.Check
		is_optional_state: DF.Check
		message: DF.Text | None
		next_action_email_template: DF.Link | None
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		send_email: DF.Check
		state: DF.Link
		update_field: DF.Literal[None]
		update_value: DF.Data | None
		workflow_builder_id: DF.Data | None
		...


