"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

PUBLISH_THROTTLE_SECONDS = ...
class BackgroundTask(Document):
	if TYPE_CHECKING:
		arguments: DF.JSON | None
		ended_at: DF.Datetime | None
		on_failure_callback: DF.Data | None
		on_success_callback: DF.Data | None
		exception: DF.LongText | None
		method: DF.Data
		progress: DF.Percent
		queue: DF.Data | None
		ref_docname: DF.DynamicLink | None
		ref_doctype: DF.Link | None
		result: DF.LongText | None
		show_progress_bar: DF.Check
		stage: DF.Data | None
		started_at: DF.Datetime | None
		status: DF.Literal[Queued, Running, Completed, Failed, Cancelled]
		task_id: DF.Data
		job_id: DF.Data | None
		task_name: DF.Data
		user: DF.Link
		...
	def __init__(self, *args, **kwargs) -> None:
		...
	
	def after_insert(self): # -> None:
		...
	
	def update_stage(self, stage: str) -> None:
		"""Publish a stage description without numeric progress"""
		...
	
	def publish_progress(self, percent: int | float, stage: str | None = ...) -> None:
		"""Publish numeric progress (0-100)"""
		...
	
	def store_result(self, result) -> None:
		"""Store a JSON result of the task in DB"""
		...
	
	def attach_file(self, file_name: str, content: bytes, is_private: bool = ..., doctype: str | None = ..., docname: str | None = ...) -> str:
		"""Attach a file to a document (defaults to the background task) and return its file URL"""
		...
	
	@staticmethod
	def clear_old_logs(days=...): # -> None:
		...
	


@frappe.whitelist()
def get_recent_tasks(limit: int = ...) -> list[dict]:
	...

@frappe.whitelist()
def get_cached_task_status(task_id: str) -> dict | None:
	...

@frappe.whitelist()
def stop_task(task_id: str): # -> None:
	...

@frappe.whitelist()
def retry_task(task_id: str): # -> None:
	...

