"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class DomainSettings(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		active_domains: DF.Table[HasDomain]
		...
	def set_active_domains(self, domains): # -> None:
		...
	
	def on_update(self): # -> None:
		...
	
	def restrict_roles_and_modules(self): # -> None:
		"""Disable all restricted roles and set `restrict_to_domain` property in Module Def"""
		...
	


def get_active_domains(): # -> Any | None:
	"""get the domains set in the Domain Settings as active domain"""
	...

def get_active_modules(): # -> Any | None:
	"""get the active modules from Module Def"""
	...

