"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class TopBarItem(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		label: DF.Data
		open_in_new_tab: DF.Check
		parent: DF.Data
		parent_label: DF.Literal[None]
		parentfield: DF.Data
		parenttype: DF.Data
		right: DF.Check
		url: DF.Data | None
		...


