"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

class BaseUrlNotSetError(frappe.ValidationError):
	...


class AuthorizeUrlNotSetError(frappe.ValidationError):
	...


class AccessTokenUrlNotSetError(frappe.ValidationError):
	...


class RedirectUrlNotSetError(frappe.ValidationError):
	...


class ClientIDNotSetError(frappe.ValidationError):
	...


class ClientSecretNotSetError(frappe.ValidationError):
	...


class SocialLoginKey(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		access_token_url: DF.Data | None
		api_endpoint: DF.Data | None
		api_endpoint_args: DF.Code | None
		auth_url_data: DF.Code | None
		authorize_url: DF.Data | None
		base_url: DF.Data | None
		client_id: DF.Data | None
		client_secret: DF.Password | None
		custom_base_url: DF.Check
		enable_social_login: DF.Check
		icon: DF.Data | None
		provider_name: DF.Data
		redirect_url: DF.Data | None
		show_in_resource_metadata: DF.Check
		sign_ups: DF.Literal["", Allow, Deny]
		social_login_provider: DF.Literal[Custom, Facebook, Frappe, GitHub, Google, "Office 365", Salesforce, fairlogin, Keycloak,]
		user_id_property: DF.Data | None
		...
	def autoname(self): # -> None:
		...
	
	def validate(self): # -> None:
		...
	
	def set_icon(self): # -> None:
		...
	
	@frappe.whitelist()
	def get_social_login_provider(self, provider: str, initialize: int | bool = ...): # -> dict[Any, Any] | None:
		...
	


def provider_allows_signup(provider: str) -> bool:
	...

