"""
This type stub file was generated by pyright.
"""

import frappe

def get_country_info(country=...): # -> _dict[Any, Any]:
	...

def get_all(): # -> Any:
	...

@frappe.whitelist(allow_guest=True)
def get_country_timezone_info(): # -> dict[str, Any]:
	...

def get_translated_countries(): # -> dict[Any, Any]:
	...

def update(): # -> None:
	...

