"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from .utils import debug_timer
from .runner import TestRunner

"""
This module provides functionality for discovering and organizing tests in the Frappe framework.

Key components:
- discover_all_tests: Discovers all tests for specified app(s)
- discover_doctype_tests: Discovers tests for specific DocType(s)
- discover_module_tests: Discovers tests for specific module(s)
- _add_module_tests: Helper function to add tests from a module to the test runner

The module uses various strategies to find and categorize tests, including:
- Walking through app directories
- Importing test modules
- Categorizing tests (e.g., unit, integration)
- Filtering tests based on configuration

It also includes error handling and logging to facilitate debugging and provide informative error messages.

Usage:
These functions are typically called by the test runner to populate the test suite before execution.
"""
if TYPE_CHECKING:
	...
logger = ...
@debug_timer
def discover_all_tests(apps: list[str], runner) -> TestRunner:
	"""Discover all tests for the specified app(s)"""
	...

@debug_timer
def discover_doctype_tests(doctypes: list[str], runner, app: str, force: bool = ...) -> TestRunner:
	"""Discover tests for the specified doctype(s)"""
	...

@debug_timer
def discover_module_tests(modules: list[str], runner, app: str) -> TestRunner:
	"""Discover tests for the specified test module"""
	...

class TestRunnerError(Exception):
	"""Custom exception for test runner errors"""
	...


