"""
This type stub file was generated by pyright.
"""

import unittest
from frappe.testing.config import TestParameters

class FrappeTestLoader(unittest.TestLoader):
	def recursive_load_suites_in_pymodule(self, suite): # -> None:
		...
	
	def load_testsuites_in_pymodule(self, file_modules): # -> None:
		...
	
	def load_pymodule_for_files(self, files: list): # -> list[Any]:
		"""
		files: list of tuple of (Path, str)
		"""
		...
	
	def get_files(self, apps: list) -> list:
		...
	
	def discover_tests(self, params: TestParameters) -> unittest.TestSuite:
		...
	


