"""
This type stub file was generated by pyright.
"""

import redis
import frappe
from contextlib import suppress
from typing import TYPE_CHECKING
from frappe.utils.data import cstr
from frappe.realtime.registry import realtime as realtime
from frappe.realtime.socket import Socket as Socket

if TYPE_CHECKING:
	...
def publish_progress(percent, title=..., doctype=..., docname=..., description=..., task_id=...): # -> None:
	...

def publish_realtime(event: str | None = ..., message: dict | None = ..., room: str | None = ..., user: str | None = ..., doctype: str | None = ..., docname: str | None = ..., task_id: str | None = ..., after_commit: bool = ...): # -> None:
	"""Publish real-time updates

	:param event: Event name, like `task_progress` etc. that will be handled by the client (default is `task_progress` if within task or `global`)
	:param message: JSON message object. For async must contain `task_id`
	:param room: Room in which to publish update (default entire site)
	:param user: Transmit to user
	:param doctype: Transmit to doctype, docname
	:param docname: Transmit to doctype, docname
	:param after_commit: (default False) will emit after current transaction is committed"""
	...

def flush_realtime_log(): # -> None:
	...

def clear_realtime_log(): # -> None:
	...

def emit_via_redis(event, message, room): # -> None:
	"""Publish real-time updates via redis

	:param event: Event name, like `task_progress` etc.
	:param message: JSON message object. For async must contain `task_id`
	:param room: name of the room"""
	...

@frappe.whitelist(allow_guest=True)
def has_permission(doctype: str, name: str, ptype: str = ...) -> bool:
	...

SOCKETIO_SECRET_KEY = ...
def get_socketio_secret(): # -> Any | str:
	"""Generate socket.io secret and store in redis"""
	...

@frappe.whitelist(allow_guest=True)
def get_user_info(): # -> dict[Any, Any] | dict[str, Any]:
	...

def get_doctype_room(doctype): # -> str:
	...

def get_doc_room(doctype, docname): # -> str:
	...

def get_user_room(user): # -> str:
	...

def get_site_room(): # -> Literal['all']:
	...

def get_task_progress_room(task_id): # -> str:
	...

def get_website_room(): # -> Literal['website']:
	...

def publish_to_user(user: str, event: str, message: dict | None = ..., *, after_commit: bool = ...): # -> None:
	"""Publish to a specific user's room (user:{user})."""
	...

def publish_to_doc(doctype: str, docname: str, event: str, message: dict | None = ..., *, after_commit: bool = ...): # -> None:
	"""Publish to a document's room (doc:{doctype}/{docname})."""
	...

def publish_to_doctype(doctype: str, event: str, message: dict | None = ..., *, after_commit: bool = ...): # -> None:
	"""Publish to a doctype's room (doctype:{doctype})."""
	...

def publish_task_progress(task_id: str, message: dict | None = ..., *, after_commit: bool = ...): # -> None:
	"""Publish task progress to task_progress:{task_id}."""
	...

def publish_to_website(event: str, message: dict | None = ..., *, after_commit: bool = ...): # -> None:
	"""Publish to the website room."""
	...

def publish_to_all(event: str, message: dict | None = ..., *, after_commit: bool = ...): # -> None:
	"""Publish to the site "all" room (System Users of THIS site).

	NOTE: this is the site-scoped room, NOT the cross-site no-room broadcast that
	build events use."""
	...

def publish_to_room(room: str, event: str, message: dict | None = ..., *, after_commit: bool = ...): # -> None:
	"""Publish to an arbitrary room."""
	...

def __getattr__(name: str) -> object:
	...

