"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from dataclasses import dataclass
from typing import Literal
from frappe.realtime.config import RealtimeConfig

logger = ...
SOCKETIO_SECRET_KEY = ...
HttpMethod = Literal["GET", "POST", "PUT", "PATCH", "DELETE"]
WebRequest = Callable[..., dict]
@dataclass(frozen=True)
class Credentials:
	"""Client credential from the Socket.IO handshake."""
	sid: str | None = ...
	authorization: str | None = ...
	def headers(self) -> dict[str, str]:
		...
	


@dataclass
class Session:
	"""Authenticated user session stored on the socket.

	Carries the identity plus an authenticated client toward the web process, so
	handlers (via Socket) can call back without rebuilding auth. ``data`` is a bag
	for transient per-socket state (e.g. presence tracking)."""
	site: str
	user: str
	user_type: str | None
	installed_apps: list[str]
	request: WebRequest
	data: dict = ...
	def get(self, path: str, params: dict | None = ...) -> dict:
		...
	
	def post(self, path: str, body: dict | None = ..., params: dict | None = ...) -> dict:
		...
	
	def put(self, path: str, body: dict | None = ..., params: dict | None = ...) -> dict:
		...
	
	def delete(self, path: str, params: dict | None = ...) -> dict:
		...
	
	def send_request(self, path: str, method: HttpMethod = ..., params: dict | None = ..., body: dict | None = ...) -> dict:
		"""Authenticated request to the web process; returns the decoded JSON body.

		method: HTTP verb. params: query string. body: JSON body.
		Prefer get/post/put/delete for the common cases.
		"""
		...
	
	def has_permission(self, doctype: str, name: str | None = ..., ptype: str = ...) -> bool:
		"""HTTP permission check against the web process (no DB in realtime)."""
		...
	


def authenticate(environ: dict, namespace: str, config: RealtimeConfig) -> Session:
	"""Authenticate a connection.

	Port of realtime/middlewares/authenticate.js. Auth is delegated to the web
	process over HTTP; the realtime process never resumes a session in-process.
	Runs the checks in order and refuses the connection as soon as one fails.
	"""
	...

_secret_client = ...
def get_socketio_secret(redis_url: str) -> str | None:
	"""Read socketio_auth_secret from the no-auth queue redis (same key the web sets)."""
	...

