"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass

"""Resolve realtime server config.

Reuses ``frappe.get_common_site_config()`` (the same ``common_site_config.json``
the Node ``node_utils.get_conf`` reads) instead of re-porting the JSON parse.
Config comes only from common_site_config.json / site_config.json — no env vars.

``frappe`` is imported lazily so this module can be imported in tests without a
configured bench, and so import never precedes the gevent monkeypatch in server.py.
"""
DEFAULT_SOCKETIO_PORT = ...
DEFAULT_REDIS_QUEUE = ...
@dataclass(frozen=True)
class RealtimeConfig:
	port: int
	redis_queue: str
	uds: str | None = ...
	default_site: str | None = ...
	developer_mode: bool = ...
	webserver_port: int | None = ...


def get_config(sites_path: str | None = ...) -> RealtimeConfig:
	"""Build the realtime config from common_site_config.json."""
	...

