"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager

logger = ...
@contextmanager
def frappe_context(site: str, user: str): # -> Generator[Any, Any, None]:
	"""Per-handler Frappe context.

	Opened only for handlers registered with frappe_context=True. Every such event
	pays the full init -> connect -> set_user -> commit/rollback -> destroy cycle and
	forces a DB connection into the realtime process, so use it sparingly; the cheap
	default is the HTTP permission check on Socket.

	The DB connection is forced onto the pure-python PyMySQL driver (see
	server.force_pymysql) — the mysqlclient C extension would stall the gevent hub.
	"""
	...

