"""
This type stub file was generated by pyright.
"""

from frappe.realtime import Socket, realtime

WEBSITE_ROOM = ...
SITE_ROOM = ...
def user_room(user: str) -> str:
	...

def doctype_room(doctype: str) -> str:
	...

def doc_room(doctype: str, docname: str) -> str:
	...

def task_room(task_id: str) -> str:
	...

def open_doc_room(doctype: str, docname: str) -> str:
	...

@realtime.on("connect", allow_guest=True)
def on_connect(socket: Socket) -> None:
	...

@realtime.on("ping", allow_guest=True)
def ping(socket: Socket) -> None:
	...

@realtime.on("doctype_subscribe", allow_guest=True)
def doctype_subscribe(socket: Socket, doctype: str) -> None:
	...

@realtime.on("doctype_unsubscribe", allow_guest=True)
def doctype_unsubscribe(socket: Socket, doctype: str) -> None:
	...

@realtime.on("task_subscribe", allow_guest=True)
def task_subscribe(socket: Socket, task_id: str) -> None:
	...

@realtime.on("task_unsubscribe", allow_guest=True)
def task_unsubscribe(socket: Socket, task_id: str) -> None:
	...

@realtime.on("progress_subscribe", allow_guest=True)
def progress_subscribe(socket: Socket, task_id: str) -> None:
	...

@realtime.on("doc_subscribe", allow_guest=True)
def doc_subscribe(socket: Socket, doctype: str, docname: str) -> None:
	...

@realtime.on("doc_unsubscribe", allow_guest=True)
def doc_unsubscribe(socket: Socket, doctype: str, docname: str) -> None:
	...

@realtime.on("doc_open", allow_guest=True)
def doc_open(socket: Socket, doctype: str, docname: str) -> None:
	...

@realtime.on("doc_close", allow_guest=True)
def doc_close(socket: Socket, doctype: str, docname: str) -> None:
	...

@realtime.on("disconnect", allow_guest=True)
def on_disconnect(socket: Socket) -> None:
	...

def notify_doc_viewers(socket: Socket, doctype: str, docname: str) -> None:
	"""Emit doc_viewers to everyone in the open-doc room. Port of notify_subscribed_doc_users."""
	...

@realtime.on("open_in_editor")
def open_in_editor(socket: Socket, data: object) -> None:
	"""Dev-only: forward esbuild "open in editor" to the redis open_in_editor channel."""
	...

