"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from frappe.realtime.auth import Session
from socketio.server import Server as SocketIOServer

if TYPE_CHECKING:
	...
class Socket:
	"""Typed Socket wrapper passed to handlers.

	Thin facade over the python-socketio server bound to one sid + namespace,
	plus the authenticated Session stored at connect. Read-only identity fields
	and emit/room helpers; identity + has_permission delegate to the Session, so
	the wrapper carries no auth/HTTP logic itself.
	"""
	def __init__(self, sio: SocketIOServer, sid: str, namespace: str, session: Session) -> None:
		...
	
	@property
	def site(self) -> str:
		...
	
	@property
	def user(self) -> str:
		...
	
	@property
	def user_type(self) -> str:
		...
	
	@property
	def installed_apps(self) -> list[str]:
		...
	
	def join(self, room: str) -> None:
		...
	
	def leave(self, room: str) -> None:
		...
	
	def emit(self, event: str, data: object | None = ..., room: str | None = ...) -> None:
		"""Emit to a room, or to this client (default)."""
		...
	
	def get(self, key: str, default: object = ...) -> object:
		"""Read transient per-socket state from the session."""
		...
	
	def set(self, key: str, value: object) -> None:
		"""Persist transient per-socket state onto the session."""
		...
	
	def participants(self, room: str) -> list[str]:
		"""sids currently in ``room`` of this namespace."""
		...
	
	def user_of(self, sid: str) -> str | None:
		"""User on another socket's session, or None if it has none."""
		...
	
	def has_permission(self, doctype: str, name: str | None = ...) -> bool:
		"""HTTP permission check via the web process (no DB in realtime).

		For in-process checks use frappe.has_permission inside a
		frappe_context=True handler."""
		...
	


