"""
This type stub file was generated by pyright.
"""

from frappe.realtime.config import RealtimeConfig

"""Small helpers for the realtime connect path: header reads, hostnames, URLs,
and site resolution. Kept separate so auth.py stays focused on the pipeline."""
def read_header(environ: dict, name: str) -> str | None:
	"""Read an HTTP header from a WSGI environ (HTTP_FOO style)."""
	...

def get_hostname(url: str | None) -> str | None:
	"""hostname without scheme or port. Port of node_utils get_hostname."""
	...

def resolve_site_name(environ: dict, config: RealtimeConfig) -> str | None:
	"""Resolve the site name. Port of authenticate.js get_site_name (order preserved)."""
	...

def get_url(origin: str | None, path: str, config: RealtimeConfig) -> str:
	"""Build the web-process URL for a request. Port of realtime/utils.js get_url."""
	...

