"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.utils import cint

@frappe.whitelist(allow_guest=True)
def web_search(query: str, scope: str | None = ..., limit: int = ...): # -> list[_dict[Any, Any]]:
	...

