"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.search.full_text_search import FullTextSearch

INDEX_NAME = ...
class WebsiteSearch(FullTextSearch):
	"""Wrapper for WebsiteSearch"""
	def get_schema(self): # -> Schema:
		...
	
	def get_fields_to_search(self): # -> list[str]:
		...
	
	def get_id(self): # -> Literal['path']:
		...
	
	def get_items_to_index(self): # -> list[Any]:
		"""Get all routes to be indexed, this includes the static pages in www/ and routes from published documents.

		Return:
		        self (object): FullTextSearch Instance
		"""
		...
	
	def get_document_to_index(self, route: str) -> frappe._dict | None:
		"""Render a page and parse it using `BeautifulSoup`.

		Args:
		        path: route of the page to be parsed

		Return a dictionary with title, path and content.
		"""
		...
	
	def parse_result(self, result): # -> _dict[Any, Any]:
		...
	


def slugs_with_web_view(_items_to_index): # -> list[Any]:
	...

def get_static_pages_from_all_apps(): # -> list[Any]:
	...

def update_index_for_path(path): # -> None:
	...

def remove_document_from_index(path): # -> None:
	...

def build_index_for_all_routes(): # -> None:
	...

