"""
This type stub file was generated by pyright.
"""

import subprocess
import sys
import click
import frappe
import frappe.utils
from functools import wraps
from io import StringIO
from os import environ

def pass_context(f): # -> Callable[..., Any]:
	...

def get_site(context, raise_err=...): # -> None:
	...

def popen(command, *args, **kwargs): # -> int:
	...

def call_command(cmd, context): # -> Any:
	...

def get_commands(): # -> list[Command]:
	...

commands = ...
