"""
This type stub file was generated by pyright.
"""

import click

@click.command("create-rq-users")
@click.option("--set-admin-password", is_flag=True, default=False, help="Set new Redis admin(default user) password")
@click.option("--use-rq-auth", is_flag=True, default=False, help="Enable Redis authentication for sites")
def create_rq_users(set_admin_password=..., use_rq_auth=...): # -> None:
	"""Create Redis Queue users and add to acl and app configs.

	acl config file will be used by redis server while starting the server
	and app config is used by app while connecting to redis server.
	"""
	...

commands = ...
