"""
This type stub file was generated by pyright.
"""

import click
from frappe.commands import pass_context
from frappe.utils.bench_helper import CliCtxObj

@click.command("trigger-scheduler-event", help="Trigger a scheduler event")
@click.argument("event")
@pass_context
def trigger_scheduler_event(context: CliCtxObj, event):
	...

@click.command("enable-scheduler")
@pass_context
def enable_scheduler(context: CliCtxObj): # -> None:
	"Enable scheduler"
	...

@click.command("disable-scheduler")
@pass_context
def disable_scheduler(context: CliCtxObj): # -> None:
	"Disable scheduler"
	...

@click.command("scheduler")
@click.option("--site", help="site name")
@click.argument("state", type=click.Choice(["pause", "resume", "disable", "enable", "status"]))
@click.option("--format", "-f", default="text", type=click.Choice(["json", "text"]), help="Output format")
@click.option("--verbose", "-v", is_flag=True, help="Verbose output")
@pass_context
def scheduler(context: CliCtxObj, state: str, format: str, verbose: bool = ..., site: str | None = ...): # -> None:
	"""Control scheduler state."""
	...

@click.command("set-maintenance-mode")
@click.option("--site", help="site name")
@click.argument("state", type=click.Choice(["on", "off"]))
@pass_context
def set_maintenance_mode(context: CliCtxObj, state, site=...): # -> None:
	"""Put the site in maintenance mode for upgrades."""
	...

@click.command("doctor")
@click.option("--site", help="site name")
@pass_context
def doctor(context: CliCtxObj, site=...): # -> Literal[True]:
	"Get diagnostic info about background workers"
	...

@click.command("show-pending-jobs")
@click.option("--site", help="site name")
@pass_context
def show_pending_jobs(context: CliCtxObj, site=...): # -> None:
	"Get diagnostic info about background jobs"
	...

@click.command("purge-jobs")
@click.option("--site", help="site name")
@click.option("--queue", default=None, help='one of "low", "default", "high')
@click.option("--event", default=None, help='one of "all", "weekly", "monthly", "hourly", "daily", "weekly_long", "daily_long"')
def purge_jobs(site=..., queue=..., event=...): # -> None:
	"Purge any pending periodic tasks, if event option is not given, it will purge everything for the site"
	...

@click.command("schedule")
def start_scheduler():
	"""Start scheduler process which is responsible for enqueueing the scheduled job types."""
	...

@click.command("worker")
@click.option("--queue", type=str, help="Queue to consume from. Multiple queues can be specified using comma-separated string. If not specified all queues are consumed.")
@click.option("--quiet", is_flag=True, default=False, help="Hide Log Outputs")
@click.option("-u", "--rq-username", default=None, help="Redis ACL user")
@click.option("-p", "--rq-password", default=None, help="Redis ACL user password")
@click.option("--burst", is_flag=True, default=False, help="Run Worker in Burst mode.")
@click.option("--strategy", required=False, type=click.Choice(["round_robin", "random"]), help="Dequeuing strategy to use")
def start_worker(queue, quiet=..., rq_username=..., rq_password=..., burst=..., strategy=...):
	"""Start a background worker"""
	...

@click.command("worker-pool")
@click.option("--queue", type=str, help="Queue to consume from. Multiple queues can be specified using comma-separated string. If not specified all queues are consumed.")
@click.option("--num-workers", type=int, default=2, help="Number of workers to spawn in pool.")
@click.option("--quiet", is_flag=True, default=False, help="Hide Log Outputs")
@click.option("--burst", is_flag=True, default=False, help="Run Worker in Burst mode.")
def start_worker_pool(queue, quiet=..., num_workers=..., burst=...):
	"""Start a pool of background workers"""
	...

@click.command("ready-for-migration")
@click.option("--site", help="site name")
@pass_context
def ready_for_migration(context: CliCtxObj, site=...): # -> Literal[0]:
	...

commands = ...
