"""
This type stub file was generated by pyright.
"""

import typing
import click
from frappe.commands import pass_context
from frappe.utils.bench_helper import CliCtxObj
from IPython.terminal.embed import InteractiveShellEmbed

EXTRA_ARGS_CTX = ...
if typing.TYPE_CHECKING:
	...
@click.command("build")
@click.option("--app", help="Build assets for app")
@click.option("--apps", help="Build assets for specific apps")
@click.option("--hard-link", is_flag=True, default=False, help="Copy the files instead of symlinking", envvar="FRAPPE_HARD_LINK_ASSETS")
@click.option("--production", is_flag=True, default=False, help="Build assets in production mode")
@click.option("--verbose", is_flag=True, default=False, help="Verbose")
@click.option("--force", is_flag=True, default=False, help="Force build assets instead of downloading available")
@click.option("--save-metafiles", is_flag=True, default=False, help="Saves esbuild metafiles for built assets. Useful for analyzing bundle size. More info: https://esbuild.github.io/api/#metafile")
@click.option("--using-cached", is_flag=True, default=False, envvar="USING_CACHED", help="Skips build and uses cached build artifacts (cache is set by Bench). Ignored if developer_mode enabled.")
def build(app=..., apps=..., hard_link=..., production=..., verbose=..., force=..., save_metafiles=..., using_cached=...): # -> None:
	"Compile JS and CSS source files"
	...

def run_after_build_hook(apps): # -> None:
	...

@click.command("watch")
@click.option("--apps", help="Watch assets for specific apps")
def watch(apps=...): # -> None:
	"Watch and compile JS and CSS files as and when they change"
	...

@click.command("clear-cache")
@pass_context
def clear_cache(context: CliCtxObj): # -> None:
	"Clear cache, doctype cache and defaults"
	...

@click.command("clear-website-cache")
@pass_context
def clear_website_cache(context: CliCtxObj): # -> None:
	"Clear website cache"
	...

@click.command("destroy-all-sessions")
@click.option("--reason")
@pass_context
def destroy_all_sessions(context: CliCtxObj, reason=...): # -> None:
	"Clear sessions of all users (logs them out)"
	...

@click.command("show-config")
@click.option("--format", "-f", type=click.Choice(["text", "json"]), default="text")
@pass_context
def show_config(context: CliCtxObj, format): # -> None:
	"Print configuration file to STDOUT in specified format"
	...

@click.command("reset-perms")
@pass_context
def reset_perms(context: CliCtxObj): # -> None:
	"Reset permissions for all doctypes"
	...

@click.command("execute", context_settings=EXTRA_ARGS_CTX)
@click.argument("method")
@click.option("--args")
@click.option("--kwargs")
@click.option("--profile", is_flag=True, default=False)
@click.argument("extra_args", nargs=-1)
@pass_context
def execute(context: CliCtxObj, method, args=..., kwargs=..., profile=..., extra_args=...): # -> None:
	"Execute a function"
	...

@click.command("add-to-email-queue")
@click.argument("email-path")
@pass_context
def add_to_email_queue(context: CliCtxObj, email_path): # -> None:
	"Add an email to the Email Queue"
	...

@click.command("export-doc")
@click.argument("doctype")
@click.argument("docname")
@pass_context
def export_doc(context: CliCtxObj, doctype, docname): # -> None:
	"Export a single document to csv"
	...

@click.command("export-json")
@click.argument("doctype")
@click.argument("path")
@click.option("--name", help="Export only one document")
@pass_context
def export_json(context: CliCtxObj, doctype, path, name=...): # -> None:
	"Export doclist as json to the given path, use '-' as name for Singles."
	...

@click.command("export-csv")
@click.argument("doctype")
@click.argument("path")
@pass_context
def export_csv(context: CliCtxObj, doctype, path): # -> None:
	"Export data import template with data for DocType"
	...

@click.command("export-fixtures")
@click.option("--app", default=None, help="Export fixtures of a specific app")
@pass_context
def export_fixtures(context: CliCtxObj, app=...): # -> None:
	"Export fixtures"
	...

@click.command("import-doc")
@click.argument("path")
@pass_context
def import_doc(context: CliCtxObj, path, force=...): # -> None:
	"Import (insert/update) doclist. If the argument is a directory, all files ending with .json are imported"
	...

@click.command("data-import")
@click.option("--file", "file_path", type=click.Path(exists=True, dir_okay=False, resolve_path=True), required=True, help="Path to import file (.csv, .xlsx). Consider that relative paths will resolve from 'sites' directory")
@click.option("--doctype", type=str, required=True)
@click.option("--type", "import_type", type=click.Choice(["Insert", "Update"], case_sensitive=False), default="Insert", help="Insert New Records or Update Existing Records")
@click.option("--submit-after-import", default=False, is_flag=True, help="Submit document after importing it")
@click.option("--mute-emails", default=True, is_flag=True, help="Mute emails during import")
@pass_context
def data_import(context: CliCtxObj, file_path, doctype, import_type=..., submit_after_import=..., mute_emails=...): # -> None:
	"Import documents in bulk from CSV or XLSX using data import"
	...

@click.command("bulk-rename")
@click.argument("doctype")
@click.argument("path")
@pass_context
def bulk_rename(context: CliCtxObj, doctype, path): # -> None:
	"Rename multiple records via CSV file"
	...

@click.command("db-console", context_settings=EXTRA_ARGS_CTX)
@click.argument("extra_args", nargs=-1)
@pass_context
def database(context: CliCtxObj, extra_args): # -> None:
	"""
	Enter into the Database console for given site.
	"""
	...

@click.command("mariadb", context_settings=EXTRA_ARGS_CTX)
@click.argument("extra_args", nargs=-1)
@pass_context
def mariadb(context: CliCtxObj, extra_args): # -> None:
	"""
	Enter into mariadb console for a given site.
	"""
	...

@click.command("postgres", context_settings=EXTRA_ARGS_CTX)
@click.argument("extra_args", nargs=-1)
@pass_context
def postgres(context: CliCtxObj, extra_args): # -> None:
	"""
	Enter into postgres console for a given site.
	"""
	...

@click.command("sqlite", context_settings=EXTRA_ARGS_CTX)
@click.argument("extra_args", nargs=-1)
@pass_context
def sqlite(context: CliCtxObj, extra_args): # -> None:
	"""
	Enter into sqlite console for a given site.
	"""
	...

@click.command("jupyter")
@pass_context
def jupyter(context: CliCtxObj):
	"""Start an interactive jupyter notebook"""
	...

def store_logs(terminal: InteractiveShellEmbed) -> None:
	...

@click.command("console")
@click.option("--autoreload", is_flag=True, help="Reload changes to code automatically")
@pass_context
def console(context: CliCtxObj, autoreload=...): # -> None:
	"Start ipython console for a site"
	...

@click.command("transform-database", help="Change tables' internal settings changing engine and row formats")
@click.option("--table", required=True, help="Comma separated name of tables to convert. To convert all tables, pass 'all'")
@click.option("--engine", default=None, type=click.Choice(["InnoDB", "MyISAM"]), help="Choice of storage engine for said table(s)")
@click.option("--row_format", default=None, type=click.Choice(["DYNAMIC", "COMPACT", "REDUNDANT", "COMPRESSED"]), help="Set ROW_FORMAT parameter for said table(s)")
@click.option("--failfast", is_flag=True, default=False, help="Exit on first failure occurred")
@pass_context
def transform_database(context: CliCtxObj, table, engine, row_format, failfast): # -> None:
	"Transform site database through given parameters"
	...

@click.command("serve")
@click.option("--port", default=8000)
@click.option("--profile", is_flag=True, default=False)
@click.option("--proxy", is_flag=True, default=False, help="The development server may be run behind a proxy, e.g. ngrok / localtunnel")
@click.option("--noreload", "no_reload", is_flag=True, default=False)
@click.option("--nothreading", "no_threading", is_flag=True, default=False)
@click.option("--with-coverage", is_flag=True, default=False)
@pass_context
def serve(context: CliCtxObj, port=..., profile=..., proxy=..., no_reload=..., no_threading=..., sites_path=..., site=..., with_coverage=...): # -> None:
	"Start development web server"
	...

@click.command("request")
@click.option("--args", help="arguments like `?cmd=test&key=value` or `/api/request/method?..`")
@click.option("--path", help="path to request JSON")
@pass_context
def request(context: CliCtxObj, args=..., path=...): # -> None:
	"Run a request as an admin"
	...

@click.command("make-app")
@click.argument("destination")
@click.argument("app_name")
@click.option("--no-git", is_flag=True, default=False, help="Do not initialize git repository for the app")
def make_app(destination, app_name, no_git=...): # -> None:
	"Creates a boilerplate app"
	...

@click.command("create-patch")
def create_patch(): # -> None:
	"Creates a new patch interactively"
	...

@click.command("set-config")
@click.argument("key")
@click.argument("value")
@click.option("-g", "--global", "global_", is_flag=True, default=False, help="Set value in bench config")
@click.option("-p", "--parse", is_flag=True, default=False, help="Evaluate as Python Object")
@pass_context
def set_config(context: CliCtxObj, key, value, global_=..., parse=...): # -> None:
	"Insert/Update a value in site_config.json"
	...

@click.command("version")
@click.option("-f", "--format", "output", type=click.Choice(["plain", "table", "json", "legacy"]), help="Output format", default="plain")
def get_version(output): # -> None:
	"""Show the versions of all the installed apps."""
	...

@click.command("rebuild-global-search")
@click.option("--static-pages", is_flag=True, default=False, help="Rebuild global search for static pages")
@pass_context
def rebuild_global_search(context: CliCtxObj, static_pages=...): # -> None:
	"""Setup help table in the current site (called after migrate)"""
	...

@click.command("list-sites")
@click.option("--json", "output_json", is_flag=True, help="Output in JSON format")
@pass_context
def list_sites(context: CliCtxObj, output_json=...): # -> None:
	"List all the sites in current bench"
	...

@click.command("setup-chrome")
def setup_chrome(): # -> None:
	...

commands = ...
