"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class WebsiteSlideshowItem(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		description: DF.Text | None
		heading: DF.Data | None
		image: DF.Attach | None
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		url: DF.Data | None
		...


