"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class InstalledApplication(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		app_name: DF.Data
		app_version: DF.Data
		git_branch: DF.Data
		has_setup_wizard: DF.Check
		is_setup_complete: DF.Check
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		...


