"""
This type stub file was generated by pyright.
"""

import sqlite3
import frappe
from frappe.database.database import Database

_PARAM_COMP = ...
IMPLICIT_COMMIT_QUERY_TYPES = ...
class SQLiteExceptionUtil:
	ProgrammingError = sqlite3.ProgrammingError
	TableMissingError = sqlite3.OperationalError
	OperationalError = sqlite3.OperationalError
	InternalError = sqlite3.InternalError
	SQLError = sqlite3.OperationalError
	DataError = sqlite3.DataError
	@staticmethod
	def is_deadlocked(e: sqlite3.Error) -> bool:
		...
	
	@staticmethod
	def is_timedout(e: sqlite3.Error) -> bool:
		...
	
	@staticmethod
	def is_read_only_mode_error(e: sqlite3.Error) -> bool:
		...
	
	@staticmethod
	def is_table_missing(e: sqlite3.Error) -> bool:
		...
	
	@staticmethod
	def is_missing_column(e: sqlite3.Error) -> bool:
		...
	
	@staticmethod
	def is_duplicate_fieldname(e: sqlite3.Error) -> bool:
		...
	
	@staticmethod
	def is_duplicate_entry(e: sqlite3.Error) -> bool:
		...
	
	@staticmethod
	def is_access_denied(e: sqlite3.Error) -> bool:
		...
	
	@staticmethod
	def cant_drop_field_or_key(e: sqlite3.Error) -> bool:
		...
	
	@staticmethod
	def is_syntax_error(e: sqlite3.Error) -> bool:
		...
	
	@staticmethod
	def is_statement_timeout(e: sqlite3.Error) -> bool:
		...
	
	@staticmethod
	def is_data_too_long(e: sqlite3.Error) -> bool:
		...
	
	@staticmethod
	def is_db_table_size_limit(e: sqlite3.Error) -> bool:
		...
	
	@staticmethod
	def is_primary_key_violation(e: sqlite3.IntegrityError) -> bool:
		...
	
	@staticmethod
	def is_unique_key_violation(e: sqlite3.IntegrityError) -> bool:
		...
	
	@staticmethod
	def is_interface_error(e: sqlite3.Error): # -> bool:
		...
	
	@staticmethod
	def is_nested_transaction_error(e: sqlite3.Error): # -> bool:
		...
	


class SQLiteDatabase(SQLiteExceptionUtil, Database):
	REGEX_CHARACTER = ...
	default_port = ...
	MAX_ROW_SIZE_LIMIT = ...
	def get_connection(self, read_only: bool = ...): # -> Connection:
		...
	
	def create_connection(self, read_only: bool = ...): # -> Connection:
		...
	
	def get_db_path(self): # -> Path:
		...
	
	def set_execution_timeout(self, seconds: int): # -> None:
		...
	
	def setup_type_map(self): # -> None:
		...
	
	def get_database_size(self): # -> float:
		"""Return database size in MB."""
		...
	
	@staticmethod
	def escape(s, percent=...):
		"""Escape quotes and percent in given string."""
		...
	
	@staticmethod
	def is_type_number(code): # -> bool:
		...
	
	@staticmethod
	def is_type_datetime(code):
		...
	
	def rename_table(self, old_name: str, new_name: str) -> list | tuple:
		...
	
	def describe(self, doctype: str) -> list | tuple:
		...
	
	def change_column_type(self, doctype: str, column: str, type: str, nullable: bool = ...) -> list | tuple:
		"""Change column type by recreating the table"""
		...
	
	def rename_column(self, doctype: str, old_column_name: str, new_column_name: str): # -> None:
		"""Rename column by recreating the table"""
		...
	
	def create_auth_table(self): # -> None:
		...
	
	def create_global_search_table(self): # -> None:
		...
	
	def create_user_settings_table(self): # -> None:
		...
	
	@staticmethod
	def get_on_duplicate_update(): # -> Literal['ON CONFLICT DO UPDATE SET ']:
		...
	
	def get_table_columns_description(self, table_name): # -> str | tuple[()] | Generator[Any | _dict[Incomplete | str | Any, Any] | list[Any], Any, None] | list[Any] | list[_dict[Any, Any]] | list[list[Any]] | tuple[tuple[Any, ...]] | None:
		"""Return list of columns with descriptions."""
		...
	
	def get_column_type(self, doctype, column): # -> str | None:
		"""Return column type from database."""
		...
	
	def has_index(self, table_name, index_name): # -> str | tuple[()] | Generator[Any | _dict[Incomplete | str | Any, Any] | list[Any], Any, None] | list[Any] | list[_dict[Any, Any]] | list[list[Any]] | tuple[tuple[Any, ...]] | None:
		...
	
	def get_column_index(self, table_name: str, fieldname: str, unique: bool = ...) -> frappe._dict | None:
		"""Check if column exists for a specific fields in specified order."""
		...
	
	def add_index(self, doctype: str, fields: list, index_name: str | None = ...): # -> None:
		"""Creates an index with given fields if not already created."""
		...
	
	def add_unique(self, doctype, fields, constraint_name=...): # -> None:
		"""Creates unique constraint on fields."""
		...
	
	def updatedb(self, doctype, meta=...): # -> None:
		"""Syncs a `DocType` to the table."""
		...
	
	def get_database_list(self): # -> list[Any]:
		...
	
	def get_tables(self, cached=...): # -> str | tuple[()] | Generator[Any | _dict[Incomplete | str | Any, Any] | list[Any], Any, None] | list[Any] | list[_dict[Any, Any]] | list[list[Any]] | tuple[tuple[Any, ...]] | Any | None:
		"""Return list of tables."""
		...
	
	def get_row_size(self, doctype: str) -> int:
		"""Get estimated max row size of any table in bytes."""
		...
	
	def execute_query(self, query, values=...): # -> Cursor | int:
		...
	
	def sql(self, *args, **kwargs): # -> str | tuple[()] | Generator[Any | _dict[Incomplete | str | Any, Any] | list[Any], Any, None] | list[Any] | list[_dict[Any, Any]] | list[list[Any]] | tuple[tuple[Any, ...]] | None:
		...
	
	def sql_ddl(self, query, *args, **kwargs): # -> None:
		"""Execute DDL query."""
		...
	
	def begin(self, *, read_only=...): # -> None:
		...
	
	def commit(self, chain=...): # -> None:
		"""Commit current transaction. Calls SQL `COMMIT`."""
		...
	
	def rollback(self, *, save_point=..., chain=...): # -> None:
		"""`ROLLBACK` current transaction. Optionally rollback to a known save_point."""
		...
	
	def get_db_table_columns(self, table) -> list[str]:
		"""Return list of column names from given table."""
		...
	
	def estimate_count(self, doctype: str): # -> int:
		"""Get estimated count of total rows in a table."""
		...
	
	def truncate(self, doctype: str): # -> None:
		"""Truncate a table."""
		...
	
	def check_implicit_commit(self, query: str, query_type: str): # -> None:
		...
	


def modify_query(query): # -> str:
	"""
	Modifies query according to the requirements of SQLite
	"""
	...

def replace_locate_with_instr(query: str) -> str:
	...

def regexp(expr: str, item: str) -> bool:
	"""
	Define regexp implementation for SQLite manually

	Although it works in the CLI - doesn't work through python
	"""
	...

def regexp_replace(item: str, pattern: str, repl: str) -> str:
	"""
	Define regexp_replace implementation for SQLite
	"""
	...

