"""
This type stub file was generated by pyright.
"""

import frappe
from typing import Any

"""assign/unassign to ToDo"""
class DuplicateToDoError(frappe.ValidationError):
	...


def get(args=...): # -> list[Any]:
	"""get assigned to"""
	...

@frappe.whitelist()
def add(args: dict[str, Any] | None = ...): # -> list[Any]:
	"""add in someone's to do list
	args = {
	        "assign_to": [],
	        "doctype": ,
	        "name": ,
	        "description": ,
	        "assignment_rule":
	}

	"""
	...

@frappe.whitelist()
def add_multiple() -> None:
	...

def close_all_assignments(doctype, name, ignore_permissions=...): # -> bool:
	...

@frappe.whitelist()
def remove(doctype: str, name: str | int, assign_to: str): # -> list[Any]:
	...

@frappe.whitelist()
def remove_multiple(doctype: str, names: str): # -> None:
	...

@frappe.whitelist()
def close(doctype: str, name: str, assign_to: str): # -> list[Any]:
	...

def set_status(doctype, name, todo=..., assign_to=..., status=..., ignore_permissions=...): # -> list[Any]:
	"""remove from todo"""
	...

def clear(doctype, name, ignore_permissions=...): # -> bool:
	"""
	Clears assignments, return False if not assigned.
	"""
	...

def notify_assignment(assigned_by, allocated_to, doc_type, doc_name, action=..., description=...): # -> None:
	"""
	Notify assignee that there is a change in assignment
	"""
	...

def format_message_for_assign_to(users): # -> str:
	...

