"""
This type stub file was generated by pyright.
"""

import frappe
from typing import TYPE_CHECKING
from frappe.model.document import Document

if TYPE_CHECKING:
	...
@frappe.whitelist()
def update_follow(doctype: str, doc_name: str, following: bool | str): # -> bool:
	...

@frappe.whitelist()
def follow_document(doctype: str, doc_name: str, user: str) -> Document | bool:
	"""
	param:
	Doctype name
	doc name
	user email

	condition:
	avoided for some doctype
	follow only if track changes are set to 1
	"""
	...

@frappe.whitelist()
def unfollow_document(doctype: str, doc_name: str, user: str) -> bool:
	...

def get_message(doc_name, doctype, frequency, user): # -> list[Any]:
	...

def send_email_alert(receiver, docinfo, timeline): # -> None:
	...

def send_document_follow_mails(frequency): # -> None:
	"""
	param:
	frequency for sanding mails

	task:
	set receiver according to frequency
	group document list according to user
	get changes, activity, comments on doctype
	call method to send mail
	"""
	...

def get_user_list(frequency):
	...

def get_message_for_user(frequency, user): # -> tuple[list[Any], list[Any]]:
	...

def get_document_followed_by_user(user):
	...

def get_version(doctype, doc_name, frequency, user): # -> list[Any]:
	...

def get_comments(doctype, doc_name, frequency, user): # -> list[Any]:
	...

def is_document_followed(doctype, doc_name, user): # -> list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | _dict[Any, Any] | list[Any | None] | None:
	...

@frappe.whitelist()
def get_follow_users(doctype: str, doc_name: str): # -> list[Any]:
	...

def get_row_changed(row_changed, time, doctype, doc_name, v): # -> list[Any]:
	...

def get_added_row(added, time, doctype, doc_name, v): # -> list[dict[str, Any]]:
	...

def get_field_changed(changed, time, doctype, doc_name, v): # -> list[Any]:
	...

def send_hourly_updates(): # -> None:
	...

def send_daily_updates(): # -> None:
	...

def send_weekly_updates(): # -> None:
	...

