"""
This type stub file was generated by pyright.
"""

import frappe
from frappe import _dict
from frappe.model.document import Document

@frappe.whitelist()
def getdoc(doctype: str, name: str | int): # -> list[Any] | None:
	"""
	Loads a doclist for a given document. This method is called directly from the client.
	Requires "doctype", "name" as form variables.
	Will also call the "onload" method on the document.
	"""
	...

@frappe.whitelist()
def getdoctype(doctype: str, with_parent: int | bool = ...): # -> None:
	"""load doctype"""
	...

def get_meta_bundle(doctype): # -> list[FormMeta]:
	...

@frappe.whitelist()
def get_docinfo(doc: Document | dict | str | None = ..., doctype: str | None = ..., name: str | int | None = ...): # -> None:
	...

def add_comments(doc, docinfo): # -> list[Any]:
	...

def get_milestones(doctype, name): # -> list[Any]:
	...

def get_attachments(dt, dn): # -> list[Any]:
	...

def get_versions(doc: Document) -> list[dict]:
	...

@frappe.whitelist()
def get_communications(doctype: str, name: str | int, start: str | int = ..., limit: str | int = ...): # -> str | tuple[()] | Generator[Any | _dict[Incomplete | str | Any, Any] | list[Any], Any, None] | list[Any] | list[_dict[Any, Any]] | list[list[Any]] | tuple[tuple[Any, ...]] | None:
	...

def get_comments(doctype: str, name: str, comment_type: str | list[str] = ...) -> list[frappe._dict]:
	...

def get_communication_data(doctype, name, start=..., limit=..., after=..., fields=..., group_by=..., as_dict=...): # -> str | tuple[()] | Generator[Any | _dict[Incomplete | str | Any, Any] | list[Any], Any, None] | list[Any] | list[_dict[Any, Any]] | list[list[Any]] | tuple[tuple[Any, ...]] | None:
	"""Return list of communications for a given document."""
	...

def get_assignments(dt, dn): # -> list[Any]:
	...

def run_onload(doc): # -> None:
	...

def get_view_logs(doc: Document) -> list[dict]:
	"""get and return the latest view logs if available"""
	...

def get_tags(doctype: str, name: str) -> str:
	...

def get_document_email(doctype, name): # -> str | None:
	...

def get_additional_timeline_content(doctype, docname): # -> list[Any]:
	...

def set_link_titles(doc): # -> None:
	...

def get_title_values_for_link_and_dynamic_link_fields(doc, link_fields=...): # -> dict[Any, Any]:
	...

def get_title_values_for_table_and_multiselect_fields(doc, table_fields=...): # -> dict[Any, Any]:
	...

def send_link_titles(link_titles): # -> None:
	"""Append link titles dict in `frappe.local.response`."""
	...

def update_user_info(docinfo, doc=...): # -> None:
	...

@frappe.whitelist()
def get_user_info_for_viewers(users: str): # -> dict[Any, Any]:
	...

