"""
This type stub file was generated by pyright.
"""

import frappe

@frappe.whitelist(methods=["POST", "PUT"])
def savedocs(doc: str, action: str): # -> None:
	"""save / submit / update doclist"""
	...

@frappe.whitelist(methods=["POST", "PUT"])
def cancel(doctype: str | None = ..., name: str | int | None = ..., workflow_state_fieldname: str | None = ..., workflow_state: str | None = ...): # -> None:
	"""cancel a doclist"""
	...

@frappe.whitelist(methods=["POST", "PUT"])
def discard(doctype: str, name: str | int): # -> None:
	"""discard a draft document"""
	...

def send_updated_docs(doc): # -> None:
	...

def set_local_name(doc): # -> None:
	...

submit = ...
