"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

class DesktopIcon(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		app: DF.Autocomplete | None
		bg_color: DF.Literal[gray, blue]
		hidden: DF.Check
		icon_image: DF.Attach | None
		icon_type: DF.Literal[Link, Folder, App]
		idx: DF.Int
		label: DF.Data | None
		link: DF.SmallText | None
		link_to: DF.DynamicLink | None
		link_type: DF.Literal["Workspace Sidebar", External]
		logo_url: DF.Data | None
		parent_icon: DF.Link | None
		restrict_removal: DF.Check
		roles: DF.Table[HasRole]
		sidebar: DF.Link | None
		standard: DF.Check
		...
	def validate(self): # -> None:
		...
	
	def on_trash(self): # -> None:
		...
	
	def check_for_restrict_removal(self): # -> None:
		...
	
	def on_update(self): # -> None:
		...
	
	def after_rename(self, old, new, merge): # -> None:
		...
	
	def export_desktop_icon(self): # -> None:
		...
	
	def delete_desktop_icon_file(self): # -> None:
		...
	
	def after_insert(self): # -> None:
		...
	


def delete_desktop_icon_file(app, label): # -> None:
	...

def get_workspace_names(workspaces): # -> list[Any]:
	...

def check_app_permission(label, app): # -> Literal[True] | None:
	...

def get_desktop_icons(user=..., bootinfo=...): # -> list[Any] | Any:
	"""Return desktop icons for user"""
	...

def clear_desktop_icons_cache(user=...): # -> None:
	...

def create_desktop_icons_from_workspace(): # -> None:
	...

def create_desktop_icons_from_installed_apps(): # -> None:
	...

def create_desktop_icons(): # -> None:
	...

def create_user_icons(user, data): # -> str:
	...

@frappe.whitelist()
def add_workspace_to_desktop(workspace: str): # -> dict[str, dict[Any, Any]]:
	...

