"""
This type stub file was generated by pyright.
"""

from functools import cache
from types import ModuleType
from typing import Any, TYPE_CHECKING
from frappe.model.document import Document

if TYPE_CHECKING:
	...
logger = ...
testing_logger = ...
datetime_like_types = ...
__all__ = ["get_missing_records_doctypes", "get_missing_records_module_overrides", "get_modules", "load_test_records_for", "make_test_objects", "make_test_records", "make_test_records_for_doctype"]
@cache
def get_modules(doctype) -> tuple[str | None, ModuleType | None]:
	"""Get the modules for the specified doctype"""
	...

def get_missing_records_doctypes(doctype, visited=..., _parent=...) -> list[str]:
	"""Get the dependencies for the specified doctype in a depth-first manner"""
	...

def get_missing_records_module_overrides(module) -> [list, list]:
	...

def load_test_records_for(index_doctype) -> dict[str, Any]:
	...

test_record_manager_instance = ...
def print_mandatory_fields(doctype, initial_doctype): # -> None:
	"""Print mandatory fields for the specified doctype"""
	...

PERSISTENT_TEST_LOG_FILE = ...
class TestRecordManager:
	def __init__(self) -> None:
		...
	
	def get(self): # -> dict[Any, Any]:
		...
	
	def get_records(self, index_doctype) -> list[Document]:
		...
	
	def add(self, index_doctype, records: list[Document]): # -> None:
		...
	
	def remove(self, index_doctype): # -> None:
		"""
		Remove all records for the specified doctype from the log.
		"""
		...
	


def make_test_records(doctype, force=..., commit=...): # -> list[tuple[str, int]]:
	"""Generate test records for the given doctype and its dependencies."""
	...

def make_test_records_for_doctype(doctype, force=..., commit=...): # -> list[Data | None]:
	"""Create test records for a specific doctype."""
	...

def make_test_objects(doctype=..., test_records=..., reset=..., commit=...): # -> list[Data | None]:
	"""Generate test objects from provided records, with caching and persistence."""
	...

