"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class DocumentShareKey(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		expires_on: DF.Date | None
		key: DF.Data | None
		reference_docname: DF.DynamicLink | None
		reference_doctype: DF.Link | None
		...
	def before_insert(self): # -> None:
		...
	


def is_expired(expires_on):
	...

