"""
This type stub file was generated by pyright.
"""

"""Creates/Updates types in python controller when schema is updated.

Design goal:
	- Developer should be able to see schema in same file.
	- Type checkers should assist with field names and basic validation in same file.
	- `get_doc` outside of same file without explicit annotation is out of scope.
	- Customizations like change of fieldtype and addition of fields are out of scope.
"""
field_template = ...
start_block = ...
end_block = ...
type_code_block_template = ...
non_nullable_types = ...
class TypeExporter:
	def __init__(self, doc) -> None:
		...
	
	def export_types(self): # -> None:
		...
	


