"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable, Mapping
from typing import Self, TypeVar, overload, override

_KT = TypeVar("_KT")
_VT = TypeVar("_VT")
class _dict(dict[_KT, _VT]):
	"""dict like object that exposes keys as attributes"""
	__slots__ = ...
	__getattr__ = ...
	__setattr__ = ...
	__delattr__ = ...
	__setstate__ = ...
	@override
	def __getstate__(self) -> Self:
		...
	
	@overload
	def update(self, m: Mapping[_KT, _VT], /, **kwargs: _VT) -> Self:
		...
	
	@overload
	def update(self, m: Iterable[tuple[_KT, _VT]], /, **kwargs: _VT) -> Self:
		...
	
	@overload
	def update(self, /, **kwargs: _VT) -> Self:
		...
	
	@override
	def update(self, m: Mapping[_KT, _VT] | Iterable[tuple[_KT, _VT]] | None = ..., /, **kwargs: _VT) -> Self:
		"""update and return self -- the missing dict feature in python"""
		...
	
	@override
	def copy(self) -> _dict[_KT, _VT]:
		...
	


