"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable, Mapping
from typing import Any, Self, TypeVar, overload, override

_KT = TypeVar("_KT")
_VT = TypeVar("_VT")
class _dict(dict[_KT, _VT]):
	"""dict like object that exposes keys as attributes"""
	__slots__ = ...
	# _dict exposes dict keys as attributes (frappe._dict). Model that for the
	# type-checker so `d.<anykey>` get/set/del resolves to Any instead of erroring.
	def __getattr__(self, name: str) -> Any: ...
	def __setattr__(self, name: str, value: Any) -> None: ...
	def __delattr__(self, name: str) -> None: ...
	__setstate__ = ...
	@override
	def __getstate__(self) -> Self:
		...
	
	@overload
	def update(self, m: Mapping[_KT, _VT], /, **kwargs: _VT) -> Self:
		...
	
	@overload
	def update(self, m: Iterable[tuple[_KT, _VT]], /, **kwargs: _VT) -> Self:
		...
	
	@overload
	def update(self, /, **kwargs: _VT) -> Self:
		...
	
	@override
	def update(self, m: Mapping[_KT, _VT] | Iterable[tuple[_KT, _VT]] | None = ..., /, **kwargs: _VT) -> Self:
		"""update and return self -- the missing dict feature in python"""
		...
	
	@override
	def copy(self) -> _dict[_KT, _VT]:
		...
	


