"""
This type stub file was generated by pyright.
"""

import functools

@functools.total_ordering
class _LazyTranslate:
	__slots__ = ...
	def __init__(self, msg: str, lang: str | None = ..., context: str | None = ...) -> None:
		...
	
	@property
	def value(self) -> str:
		...
	
	def __str__(self) -> str:
		...
	
	def __add__(self, other): # -> str:
		...
	
	def __radd__(self, other): # -> str | type[NotImplementedError]:
		...
	
	def __repr__(self) -> str:
		...
	
	def __eq__(self, other) -> bool:
		...
	
	def __lt__(self, other) -> bool:
		...
	


