"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class OAuthClient(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		allowed_roles: DF.TableMultiSelect[OAuthClientRole]
		app_name: DF.Data
		client_id: DF.Data | None
		client_secret: DF.Data | None
		client_uri: DF.Data | None
		contacts: DF.SmallText | None
		default_redirect_uri: DF.Data
		grant_type: DF.Literal["Authorization Code", Implicit]
		logo_uri: DF.Data | None
		policy_uri: DF.Data | None
		redirect_uris: DF.Text | None
		response_type: DF.Literal[Code, Token]
		scopes: DF.Text
		skip_authorization: DF.Check
		software_id: DF.Data | None
		software_version: DF.Data | None
		token_endpoint_auth_method: DF.Literal["Client Secret Basic", "Client Secret Post", None]
		tos_uri: DF.Data | None
		user: DF.Link | None
		...
	def validate(self): # -> None:
		...
	
	def validate_grant_and_response(self): # -> None:
		...
	
	def add_default_role(self): # -> None:
		...
	
	def user_has_allowed_role(self) -> bool:
		"""Returns true if session user is allowed to use this client."""
		...
	
	def is_public_client(self) -> bool:
		...
	
	def client_id_issued_at(self) -> int:
		"""Returns UNIX timestamp (seconds since epoch) of the client creation time."""
		...
	


