"""
This type stub file was generated by pyright.
"""

from frappe.model.document import Document

class HasRole(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		parent: DF.Data
		parentfield: DF.Data
		parenttype: DF.Data
		role: DF.Link | None
		...
	def before_insert(self): # -> None:
		...
	


