"""
This type stub file was generated by pyright.
"""

import re
import frappe
from functools import wraps
from frappe.build import html_to_js_template
from frappe.utils import cstr
from frappe.utils.caching import site_cache

STANDARD_FIELD_CONVERSION_MAP = ...
INCLUDE_DIRECTIVE_PATTERN = ...
def set_default(doc, key): # -> None:
	"""Set is_default property of given doc and unset all others filtered by given key."""
	...

def set_field_property(filters, key, value): # -> None:
	"""utility set a property in all fields of a particular type"""
	...

class InvalidIncludePath(frappe.ValidationError):
	...


def render_include(content): # -> str:
	"""render {% raw %}{% include "app/path/filename" %}{% endraw %} in js file"""
	...

def get_fetch_values(doctype, fieldname, value): # -> _dict[Any, Any]:
	"""Return fetch value dict for the given object.

	:param doctype: Target doctype
	:param fieldname: Link fieldname selected
	:param value: Value selected
	"""
	...

@site_cache()
def is_virtual_doctype(doctype: str): # -> list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | _dict[Any, Any] | list[Any | None] | Any | bool | None:
	...

@site_cache()
def is_single_doctype(doctype: str) -> bool:
	...

def simple_singledispatch(func): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
	"""
	A decorator that implements a simplified version of single dispatch.

	This decorator allows you to define a generic function that can have
	different behaviors based on the type of its first argument. It's similar
	to Python's functools.singledispatch, but with a simpler implementation.

	Args:
	    func (callable): The base function to be decorated.

	Returns:
	    callable: A wrapper function that implements the single dispatch logic.

	The returned wrapper function has a 'register' method that can be used
	to register type-specific implementations:

	@wrapper.register(specific_type)
	def type_specific_func(arg, ...):
	    # Implementation for specific_type

	When the wrapped function is called, it dispatches to the most specific
	implementation based on the type of the first argument. If no matching
	implementation is found, it falls back to the base function.

	Example:
	    @simple_singledispatch
	    def func(arg):
	        print(f"Base implementation for {type(arg)}")

	    @func.register(int)
	    def _(arg):
	        print(f"Implementation for int: {arg}")

	    @func.register(str)
	    def _(arg):
	        print(f"Implementation for str: {arg}")

	    func(10)  # Outputs: Implementation for int: 10
	    func("hello")  # Outputs: Implementation for str: hello
	    func([1, 2, 3])  # Outputs: Base implementation for <class 'list'>
	"""
	...

