"""
This type stub file was generated by pyright.
"""

def mask_field_value(field, val): # -> LiteralString | Literal['XXXXXX', 'XX-XX-XXXX', 'XX:XX', 'XXXXXXXX']:
	"""Mask a field value based on its fieldtype and options.

	Args:
		field: DocField object with fieldtype and options attributes
		val: The value to mask

	Returns:
		Masked value based on field type, or original value if None/empty

	Masking patterns:
		- Phone (Data + Phone option): Shows first 3 chars + "XXXXXX"
		- Email (Data + Email option): Shows "XXXXXX@domain"
		- Date: Shows "XX-XX-XXXX"
		- Time: Shows "XX:XX"
		- Default: Shows "XXXXXXXX"
	"""
	...

def mask_dict_results(result, masked_fields):
	"""Mask fields in dictionary results.

	Args:
		result: List of dictionaries containing query results
		masked_fields: List of DocField objects with masking configuration

	Returns:
		Result with masked field values
	"""
	...

def mask_list_results(result, masked_fields, field_index_map): # -> list[Any]:
	"""Mask fields in list/tuple results.

	Args:
		result: List of tuples containing query results
		masked_fields: List of DocField objects with masking configuration
		field_index_map: Dict mapping field names to their position in result tuples

	Returns:
		List of tuples with masked field values
	"""
	...

