"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.model.document import Document

UNSEEN_NOTES_KEY = ...
class Note(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		content: DF.TextEditor | None
		expire_notification_on: DF.Datetime | None
		notify_on_every_login: DF.Check
		notify_on_login: DF.Check
		public: DF.Check
		seen_by: DF.Table[NoteSeenBy]
		title: DF.Data
		...
	def validate(self): # -> None:
		...
	
	def before_print(self, settings=...): # -> None:
		...
	
	def clear_cache(self): # -> None:
		...
	
	def mark_seen_by(self, user: str) -> None:
		...
	


@frappe.whitelist()
def mark_as_seen(note: str): # -> None:
	...

def get_permission_query_conditions(user): # -> str:
	...

def has_permission(doc, user): # -> bool:
	...

def get_unseen_notes(): # -> Any | list[Any]:
	...

@frappe.whitelist()
def reset_notes(): # -> Any | None:
	...

