"""
This type stub file was generated by pyright.
"""

from functools import lru_cache

"""This file houses all Frappe specific optimizations and hooks that run on startup or during fork.

Warning: This entire file is private as indicated by `_` prefix in filename.
"""
def optimize_all(): # -> None:
	"""Single entry point to enable all optimizations at right time automatically."""
	...

def optimize_gc_parameters(): # -> None:
	...

def optimize_regex_cache(): # -> None:
	...

def register_fault_handler(): # -> None:
	...

def optimize_gc_for_copy_on_write(): # -> None:
	...

_gc_frozen = ...
worker_num = ...
def freeze_gc(): # -> None:
	...

def optimize_for_gil_contention(): # -> None:
	...

def increment_worker_count(): # -> None:
	...

def assign_core(pid: int, physical_cpu_count: int, logical_cpu_count: int, current_affinity: list[int], thread_siblings: list[tuple[int, ...]]) -> int | None:
	...

def pin_web_worker_to_one_core(): # -> None:
	"""Try to assign current process to one core."""
	...

@lru_cache(maxsize=1)
def parse_thread_siblings() -> list[tuple[int, int]] | None:
	...

