"""
This type stub file was generated by pyright.
"""

import frappe
from werkzeug.wrappers import Response

SAFE_HTTP_METHODS = ...
UNSAFE_HTTP_METHODS = ...
MAX_PASSWORD_SIZE = ...
class HTTPRequest:
	def __init__(self) -> None:
		...
	
	@property
	def domain(self): # -> str:
		...
	
	def set_request_ip(self): # -> None:
		...
	
	def set_cookies(self): # -> None:
		...
	
	def set_session(self): # -> None:
		...
	
	def validate_csrf_token(self): # -> None:
		...
	
	def set_lang(self): # -> None:
		...
	
	def is_allowed_referrer(self): # -> bool:
		...
	


class LoginManager:
	__slots__ = ...
	def __init__(self) -> None:
		...
	
	def login(self): # -> Literal[False] | None:
		...
	
	def post_login(self, session_end: str | None = ..., audit_user: str | None = ...): # -> None:
		...
	
	def get_user_info(self): # -> None:
		...
	
	def setup_boot_cache(self): # -> None:
		...
	
	def set_user_info(self, resume=...): # -> None:
		...
	
	def clear_preferred_language(self): # -> None:
		...
	
	def make_session(self, resume: bool = ..., session_end: str | None = ..., audit_user: str | None = ...): # -> None:
		...
	
	def clear_active_sessions(self): # -> None:
		"""Clear other sessions of the current user if `deny_multiple_sessions` is not set"""
		...
	
	def authenticate(self, user: str | None = ..., pwd: str | None = ...): # -> None:
		...
	
	def force_user_to_reset_password(self): # -> bool | None:
		...
	
	def check_password(self, user, pwd):
		"""check password"""
		...
	
	def fail(self, message, user=...):
		...
	
	def run_trigger(self, event=...): # -> None:
		...
	
	def validate_hour(self): # -> None:
		"""check if user is logging in during restricted hours"""
		...
	
	def login_as_guest(self): # -> None:
		"""login as guest"""
		...
	
	def login_as(self, user: str, session_end: str | None = ..., audit_user: str | None = ...): # -> None:
		...
	
	def impersonate(self, user): # -> None:
		...
	
	def logout(self, arg=..., user=...): # -> None:
		...
	
	def clear_cookies(self): # -> None:
		...
	


class CookieManager:
	def __init__(self) -> None:
		...
	
	def init_cookies(self): # -> None:
		...
	
	def set_cookie(self, key, value, expires=..., secure=..., httponly=..., samesite=..., max_age=..., deduplicate=...): # -> None:
		...
	
	def delete_cookie(self, to_delete): # -> None:
		...
	
	def flush_cookies(self, response: Response): # -> None:
		...
	


@frappe.whitelist()
def get_logged_user(): # -> None:
	...

def clear_cookies(): # -> None:
	...

def validate_ip_address(user): # -> Literal[True] | None:
	"""
	Method to check if the user has IP restrictions enabled, and if so is the IP address they are
	connecting from allowlisted.

	Certain methods called from our socketio backend need direct access, and so the IP is not
	checked for those
	"""
	...

def get_login_attempt_tracker(key: str, raise_locked_exception: bool = ...): # -> LoginAttemptTracker:
	"""Get login attempt tracker instance.

	:param user_name: Name of the loggedin user
	:param raise_locked_exception: If set, raises an exception incase of user not allowed to login
	"""
	...

class LoginAttemptTracker:
	"""Track login attemts of a user.

	Lock the account for s number of seconds if there have been n consecutive unsuccessful attempts to log in.
	"""
	def __init__(self, key: str, max_consecutive_login_attempts: int = ..., lock_interval: int = ..., *, user_name: str | None = ...) -> None:
		"""Initialize the tracker.

		:param user_name: Name of the loggedin user
		:param max_consecutive_login_attempts: Maximum allowed consecutive failed login attempts
		:param lock_interval: Locking interval incase of maximum failed attempts
		"""
		...
	
	@property
	def login_failed_count(self): # -> Any | None:
		...
	
	@login_failed_count.setter
	def login_failed_count(self, count): # -> None:
		...
	
	@login_failed_count.deleter
	def login_failed_count(self): # -> None:
		...
	
	@property
	def login_failed_time(self): # -> Any | None:
		"""First failed login attempt time within lock interval.

		For every user we track only First failed login attempt time within lock interval of time.
		"""
		...
	
	@login_failed_time.setter
	def login_failed_time(self, timestamp): # -> None:
		...
	
	@login_failed_time.deleter
	def login_failed_time(self): # -> None:
		...
	
	def add_failure_attempt(self): # -> None:
		"""Log user failure attempts into the system.

		Increase the failure count if new failure is with in current lock interval time period, if not reset the login failure count.
		"""
		...
	
	def add_success_attempt(self): # -> None:
		"""Reset login failures."""
		...
	
	def is_user_allowed(self) -> bool:
		"""Is user allowed to login

		User is not allowed to login if login failures are greater than threshold within in lock interval from first login failure.
		"""
		...
	


def validate_auth(): # -> None:
	"""
	Authenticate and sets user for the request.
	"""
	...

def validate_oauth(authorization_header): # -> None:
	"""
	Authenticate request using OAuth and set session user

	Args:
	        authorization_header (list of str): The 'Authorization' header containing the prefix and token
	"""
	...

def validate_auth_via_api_keys(authorization_header): # -> None:
	"""
	Authenticate request using API keys and set session user

	Args:
	        authorization_header (list of str): The 'Authorization' header containing the prefix and token
	"""
	...

def validate_api_key_secret(api_key, api_secret, frappe_authorization_source=...): # -> None:
	"""frappe_authorization_source to provide api key and secret for a doctype apart from User"""
	...

def validate_auth_via_hooks(): # -> None:
	...

def check_request_ip(): # -> None:
	...

