"""
This type stub file was generated by pyright.
"""

from frappe.utils.caching import redis_cache

"""
bootstrap client session
"""
def get_bootinfo(): # -> _dict[Any, Any]:
	"""build and return boot info"""
	...

def get_icon_style(): # -> str | date | datetime | timedelta:
	...

def get_letter_heads(): # -> dict[Any, Any]:
	...

def load_conf_settings(bootinfo): # -> None:
	...

def load_desktop_data(bootinfo): # -> None:
	...

def load_translations(bootinfo): # -> None:
	...

def get_user_info(): # -> _dict[Any, Any]:
	...

def get_user(bootinfo): # -> None:
	"""get user info"""
	...

def add_home_page(bootinfo, docs): # -> None:
	"""load home page"""
	...

def add_timezone_info(bootinfo): # -> None:
	...

def load_print(bootinfo, doclist): # -> None:
	...

def load_print_css(bootinfo, print_settings): # -> None:
	...

def get_success_action(): # -> list[Any]:
	...

def get_link_preview_doctypes(): # -> list[Any]:
	...

def get_additional_filters_from_hooks(): # -> _dict[Any, Any]:
	...

def add_layouts(bootinfo): # -> None:
	...

def get_desk_settings(): # -> Any:
	...

def get_notification_settings(): # -> Document:
	...

def get_link_title_doctypes(): # -> list[Any]:
	...

def set_time_zone(bootinfo): # -> None:
	...

def load_country_doc(bootinfo): # -> None:
	...

def load_currency_docs(bootinfo): # -> None:
	...

def get_marketplace_apps(): # -> list[Any] | Any | None:
	...

@redis_cache
def get_tree_view_doctypes(): # -> list[Any]:
	...

def add_subscription_conf(): # -> Literal[''] | None:
	...

def get_sentry_dsn(): # -> str | None:
	...

def get_sidebar_items(allowed_workspaces): # -> dict[Any, Any]:
	...

def get_desktop_icon_urls(): # -> dict[Any, Any]:
	...

def add_user_specific_sidebar(sidebar_items): # -> None:
	...

