"""
This type stub file was generated by pyright.
"""

timestamps = ...
app_paths = ...
sites_path = ...
WHITESPACE_PATTERN = ...
HTML_COMMENT_PATTERN = ...
class AssetsNotDownloadedError(Exception):
	...


class AssetsDontExistError(Exception):
	...


def download_file(url, prefix):
	...

def build_missing_files(): # -> None:
	"""Check which files dont exist yet from the assets.json and run build for those files"""
	...

def get_assets_link(frappe_head) -> str:
	...

def fetch_assets(url, frappe_head):
	...

def setup_assets(assets_archive): # -> set[Any]:
	...

def download_frappe_assets(verbose=...) -> bool:
	"""Download and set up Frappe assets if they exist based on the current commit HEAD.
	Return True if correctly setup else return False.
	"""
	...

def symlink(target, link_name, overwrite=...): # -> None:
	"""
	Create a symbolic link named link_name pointing to target.
	If link_name exists then FileExistsError is raised, unless overwrite=True.
	When trying to overwrite a directory, IsADirectoryError is raised.

	Source: https://stackoverflow.com/a/55742015/10309266
	"""
	...

def setup(): # -> None:
	...

def bundle(mode, apps=..., hard_link=..., verbose=..., skip_frappe=..., files=..., save_metafiles=..., using_cached=..., esbuild_target=...): # -> None:
	"""concat / minify js files"""
	...

def watch(apps=...): # -> None:
	"""watch and rebuild if necessary"""
	...

def check_node_executable(): # -> None:
	...

def get_node_env(): # -> dict[str, str]:
	...

def get_safe_max_old_space_size(): # -> int:
	...

def generate_assets_map(): # -> dict[Any, Any]:
	...

def setup_assets_dirs(): # -> None:
	...

def clear_broken_symlinks(): # -> None:
	...

def unstrip(message: str) -> str:
	"""Pads input string on the right side until the last available column in the terminal"""
	...

def make_asset_dirs(hard_link=...): # -> None:
	...

def link_assets_dir(source, target, hard_link=...): # -> None:
	...

def scrub_html_template(content): # -> str:
	"""Return HTML content with removed whitespace and comments."""
	...

def html_to_js_template(path, content): # -> str:
	"""Return HTML template content as Javascript code, by adding it to `frappe.templates`."""
	...

