"""
This type stub file was generated by pyright.
"""

import frappe

"""
Concurrency limiter for expensive whitelisted methods.

Provides a @frappe.concurrent_limit() decorator that limits the number of
simultaneous in-flight executions of a function across all gunicorn workers
using a Redis-backed semaphore (LIST + BLPOP).

Usage::

    @frappe.whitelist(allow_guest=True)
    @frappe.concurrent_limit(limit=3)
    def download_pdf(...):
        ...

"""
_DEFAULT_WAIT_TIMEOUT = ...
def gunicorn_max_concurrency() -> int:
	"""Detect max concurrent requests from the running gunicorn master's cmdline."""
	...

def concurrent_limit(limit: int | None = ..., wait_timeout: int = ...): # -> Callable[..., Callable[..., Any]]:
	"""Decorator that limits simultaneous in-flight executions of the wrapped function.

	:param limit: Maximum number of concurrent executions. Defaults to half of ``workers x threads``
	    as detected from the gunicorn master process.
	:param wait_timeout: Seconds to wait for a free slot before returning 503.
	    Defaults to 10 s.

	The limiter is skipped entirely for background jobs, CLI commands, and
	tests that call functions directly (i.e. outside of an HTTP request).
	"""
	...

@frappe.whitelist()
def get_stats() -> dict:
	...

