"""
This type stub file was generated by pyright.
"""

from typing import Any
from frappe import _dict

def get_site_config(sites_path: str | None = ..., site_path: str | None = ..., *, cached=...) -> _dict[str, Any]:
	"""Return `site_config.json` combined with `sites/common_site_config.json`.
	`site_config` is a set of site wide settings like database name, password, email etc.
	"""
	...

def get_common_site_config(sites_path: str | None = ..., cached=...) -> _dict[str, Any]:
	"""Return common site config as dictionary.

	This is useful for:
	- checking configuration which should only be allowed in common site config
	- When no site context is present and fallback is required.
	"""
	...

_cached_get_site_config = ...
_cached_get_common_site_config = ...
def clear_site_config_cache(): # -> None:
	...

def get_conf(site: str | None = ...) -> _dict[str, Any]:
	...

