"""
This type stub file was generated by pyright.
"""

"""
frappe.coverage
~~~~~~~~~~~~~~~~

Coverage settings for frappe
"""
STANDARD_INCLUSIONS = ...
STANDARD_EXCLUSIONS = ...
TESTED_VIA_CLI = ...
FRAPPE_EXCLUSIONS = ...
class CodeCoverage:
	"""
	Context manager for handling code coverage.

	This class sets up code coverage measurement for a specific app,
	applying the appropriate inclusion and exclusion patterns.
	"""
	def __init__(self, with_coverage, app, outfile=...) -> None:
		...
	
	def __enter__(self): # -> Self:
		...
	
	def __exit__(self, exc_type, exc_value, traceback): # -> None:
		...
	


