"""
This type stub file was generated by pyright.
"""

def set_user_default(key, value, user=..., parenttype=...): # -> None:
	...

def add_user_default(key, value, user=..., parenttype=...): # -> None:
	...

def get_user_default(key, user=...): # -> Any | list[Any] | tuple[Any, ...] | Literal[''] | None:
	...

def get_user_permission_default(key, defaults): # -> Any | Literal['']:
	...

def get_user_default_as_list(key, user=...): # -> list[Any]:
	...

def is_a_user_permission_key(key): # -> Literal[False]:
	...

def not_in_user_permission(key, value, user=...): # -> bool:
	...

def get_user_permissions(user=...): # -> dict[Any, Any] | Any | _dict[Any, Any]:
	...

def get_defaults(user=...): # -> _dict[Any, Any] | Any:
	...

def clear_user_default(key, user=...): # -> None:
	...

def set_global_default(key, value): # -> None:
	...

def add_global_default(key, value): # -> None:
	...

def get_global_default(key): # -> Any | list[Any] | tuple[Any, ...] | None:
	...

def set_default(key, value, parent, parenttype=...): # -> None:
	"""Override or add a default value.
	Adds default value in table `tabDefaultValue`.

	:param key: Default key.
	:param value: Default value.
	:param parent: Usually, **User** to whom the default belongs.
	:param parenttype: [optional] default is `__default`."""
	...

def add_default(key, value, parent, parenttype=...): # -> None:
	...

def clear_default(key=..., value=..., parent=..., name=..., parenttype=...): # -> None:
	"""Clear a default value by any of the given parameters and delete caches.

	:param key: Default key.
	:param value: Default value.
	:param parent: User name, or `__global`, `__default`.
	:param name: Default ID.
	:param parenttype: Clear defaults table for a particular type e.g. **User**.
	"""
	...

def get_defaults_for(parent=...): # -> _dict[Any, Any] | Any:
	"""get all defaults"""
	...

