"""
This type stub file was generated by pyright.
"""

from werkzeug.exceptions import NotFound

class SiteNotSpecifiedError(Exception):
	def __init__(self, *args, **kwargs) -> None:
		...
	


class DatabaseModificationError(Exception):
	"""Error raised when attempting to modify the database in a read-only document context."""
	...


class UrlSchemeNotSupported(Exception):
	...


class ValidationError(Exception):
	http_status_code = ...


class FrappeTypeError(TypeError):
	http_status_code = ...


class AuthenticationError(Exception):
	http_status_code = ...


class SessionExpired(Exception):
	http_status_code = ...


class PermissionError(Exception):
	http_status_code = ...


class DoesNotExistError(ValidationError):
	http_status_code = ...
	def __init__(self, *args, doctype=...) -> None:
		...
	


class PageDoesNotExistError(ValidationError):
	http_status_code = ...


class NameError(Exception):
	http_status_code = ...


class OutgoingEmailError(Exception):
	http_status_code = ...


class SessionStopped(Exception):
	http_status_code = ...


class UnsupportedMediaType(Exception):
	http_status_code = ...


class RequestToken(Exception):
	http_status_code = ...


class Redirect(Exception):
	def __init__(self, http_status_code: int = ...) -> None:
		...
	


class CSRFTokenError(Exception):
	http_status_code = ...


class TooManyRequestsError(Exception):
	http_status_code = ...


class ServiceUnavailableError(Exception):
	http_status_code = ...


class ImproperDBConfigurationError(Exception):
	"""
	Used when frappe detects that database or tables are not properly
	configured
	"""
	def __init__(self, reason, msg=...) -> None:
		...
	


class DuplicateEntryError(NameError):
	...


class DataError(ValidationError):
	...


class UnknownDomainError(Exception):
	...


class MappingMismatchError(ValidationError):
	...


class InvalidStatusError(ValidationError):
	...


class MandatoryError(ValidationError):
	...


class NonNegativeError(ValidationError):
	...


class InvalidSignatureError(ValidationError):
	...


class RateLimitExceededError(ValidationError):
	http_status_code = ...


class CannotChangeConstantError(ValidationError):
	...


class CharacterLengthExceededError(ValidationError):
	...


class UpdateAfterSubmitError(ValidationError):
	...


class LinkValidationError(ValidationError):
	...


class CancelledLinkError(LinkValidationError):
	...


class DocstatusTransitionError(ValidationError):
	...


class TimestampMismatchError(ValidationError):
	...


class EmptyTableError(ValidationError):
	...


class LinkExistsError(ValidationError):
	...


class InvalidEmailAddressError(ValidationError):
	...


class InvalidNameError(ValidationError):
	...


class InvalidPhoneNumberError(ValidationError):
	...


class TemplateNotFoundError(ValidationError):
	...


class UniqueValidationError(ValidationError):
	...


class AppNotInstalledError(ValidationError):
	...


class IncorrectSitePath(NotFound):
	...


class ImplicitCommitError(ValidationError):
	...


class RetryBackgroundJobError(Exception):
	...


class DocumentLockedError(ValidationError):
	...


class CircularLinkingError(ValidationError):
	...


class SecurityException(Exception):
	...


class InvalidColumnName(ValidationError):
	...


class IncompatibleApp(ValidationError):
	...


class InvalidDates(ValidationError):
	...


class DataTooLongException(ValidationError):
	...


class FileAlreadyAttachedException(Exception):
	...


class DocumentAlreadyRestored(ValidationError):
	...


class AttachmentLimitReached(ValidationError):
	...


class QueryTimeoutError(Exception):
	...


class QueryDeadlockError(Exception):
	...


class InReadOnlyMode(ValidationError):
	http_status_code = ...


class SessionBootFailed(ValidationError):
	http_status_code = ...


class QueueOverloaded(ValidationError):
	http_status_code = ...


class PrintFormatError(ValidationError):
	...


class TooManyWritesError(Exception):
	...


class InvalidAuthorizationHeader(CSRFTokenError):
	...


class InvalidAuthorizationPrefix(CSRFTokenError):
	...


class InvalidAuthorizationToken(CSRFTokenError):
	...


class InvalidDatabaseFile(ValidationError):
	...


class ExecutableNotFound(FileNotFoundError):
	...


class InvalidRoundingMethod(FileNotFoundError):
	...


class InvalidRemoteException(Exception):
	...


class LinkExpired(ValidationError):
	http_status_code = ...
	title = ...
	message = ...


class CommandFailedError(Exception):
	def __init__(self, message: str, out: str, err: str) -> None:
		...
	


