"""
This type stub file was generated by pyright.
"""

import frappe
from typing import TYPE_CHECKING

if TYPE_CHECKING:
	...
ALLOWED_MIMETYPES = ...
def handle(): # -> Response | None:
	"""handle request"""
	...

def execute_cmd(cmd, from_async=...): # -> None:
	"""execute a request as python module"""
	...

def run_server_script(server_script): # -> None:
	...

def is_valid_http_method(method): # -> None:
	...

@frappe.whitelist(allow_guest=True, methods=["POST"])
def logout(): # -> None:
	...

@frappe.whitelist(allow_guest=True, methods=["POST"])
def web_logout(): # -> None:
	...

@frappe.whitelist(allow_guest=True, methods=["POST"])
def upload_file(): # -> Any | _NewDocument | None:
	...

def check_write_permission(doctype: str | None = ..., name: str | None = ...): # -> None:
	...

@frappe.whitelist(allow_guest=True)
def download_file(file_url: str): # -> None:
	"""
	Download file using token and REST API. Valid session or
	token is required to download private files.

	Method : GET
	Endpoints : download_file, frappe.core.doctype.file.file.download_file
	URL Params : file_name = /path/to/file relative to site path
	"""
	...

def get_attr(cmd): # -> Any:
	"""get method object from cmd"""
	...

def run_doc_method(method, docs=..., dt=..., dn=..., arg=..., args=...): # -> None:
	"""run a whitelisted controller method"""
	...

runserverobj = ...
