"""
This type stub file was generated by pyright.
"""

from semantic_version import Version

def install_db(root_login=..., root_password=..., db_name=..., source_sql=..., admin_password=..., verbose=..., force=..., site_config=..., db_password=..., db_type=..., db_socket=..., db_host=..., db_port=..., db_user=..., setup=..., rollback_callback=..., mariadb_user_host_login_scope=...): # -> None:
	...

def find_org(org_repo: str) -> tuple[str, str]:
	"""find the org a repo is in

	find_org()
	ref -> https://github.com/frappe/bench/blob/develop/bench/utils/__init__.py#L390

	:param org_repo:
	:type org_repo: str

	:raises InvalidRemoteException: if the org is not found

	:return: organisation and repository
	:rtype: Tuple[str, str]
	"""
	...

def fetch_details_from_tag(_tag: str) -> tuple[str, str, str]:
	"""parse org, repo, tag from string

	fetch_details_from_tag()
	ref -> https://github.com/frappe/bench/blob/develop/bench/utils/__init__.py#L403

	:param _tag: input string
	:type _tag: str

	:return: organisation, repostitory, tag
	:rtype: Tuple[str, str, str]
	"""
	...

def parse_app_name(name: str) -> str:
	"""parse repo name from name

	__setup_details_from_git()
	ref -> https://github.com/frappe/bench/blob/develop/bench/app.py#L114


	:param name: git tag
	:type name: str

	:return: repository name
	:rtype: str
	"""
	...

def install_app(name, verbose=..., set_as_patched=..., force=...): # -> None:
	...

def add_to_installed_apps(app_name, rebuild_website=...): # -> None:
	...

def remove_from_installed_apps(app_name): # -> None:
	...

def remove_app(app_name, dry_run=..., yes=..., no_backup=..., force=...): # -> None:
	"""Remove app and all linked to the app's module with the app from a site."""
	...

def post_install(rebuild_website=...): # -> None:
	...

def set_all_patches_as_completed(app): # -> None:
	...

def init_singles(): # -> None:
	...

def make_conf(db_name=..., db_password=..., site_config=..., db_type=..., db_socket=..., db_host=..., db_port=..., db_user=...): # -> None:
	...

def make_site_config(db_name=..., db_password=..., site_config=..., db_type=..., db_socket=..., db_host=..., db_port=..., db_user=...): # -> None:
	...

def update_site_config(key, value, validate=..., site_config_path=...): # -> None:
	"""Update a value in site_config"""
	...

def get_site_config_path(): # -> str:
	...

def get_conf_params(db_name=..., db_password=...): # -> dict[str, str | Any]:
	...

def clear_site_locks(): # -> None:
	...

def make_site_dirs(): # -> None:
	...

def add_module_defs(app, ignore_if_duplicate=...): # -> None:
	...

def remove_missing_apps(): # -> None:
	...

def convert_archive_content(sql_file_path): # -> None:
	...

def extract_files(site_name, file_path): # -> str:
	...

def is_downgrade(sql_file_path, verbose=...): # -> NotImplementedType | bool:
	"""Check if input db backup will get downgraded on current bench

	This function is only tested with mariadb.
	TODO: Add postgres support
	"""
	...

def get_old_backup_version(sql_file_path: str) -> Version | None:
	"""Return the frappe version used to create the specified database dump.

	This methods supports older versions of Frappe wich used a different format.
	"""
	...

def get_backup_version(sql_file_path: str) -> Version | None:
	"""Return the frappe version used to create the specified database dump."""
	...

def is_partial(sql_file_path: str) -> bool:
	"""
	Function to return whether the database dump is a partial backup or not

	:param sql_file_path: path to the database dump file
	:return: True if the database dump is a partial backup, False otherwise
	"""
	...

def partial_restore(sql_file_path, verbose=...): # -> None:
	...

def validate_database_sql(path: str, _raise: bool = ...) -> None:
	"""Check if file has contents and if `__Auth` table exists

	Args:
	        path (str): Path of the decompressed SQL file
	        _raise (bool, optional): Raise exception if invalid file. Defaults to True.
	"""
	...

def get_db_dump_header(file_path: str, file_bytes: int = ...) -> str:
	"""
	Get the header of a database dump file

	:param file_path: path to the database dump file
	:param file_bytes: number of bytes to read from the file
	:return: The first few bytes of the file as requested
	"""
	...

