"""
This type stub file was generated by pyright.
"""

import threading

BENCH_START_MESSAGE = ...
def atomic(method): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
	...

class SiteMigration:
	"""Migrate all apps to the current version, will:
	- run before migrate hooks
	- run patches
	- sync doctypes (schema)
	- sync dashboards
	- sync jobs
	- sync fixtures
	- sync customizations
	- sync languages
	- sync web pages (from /www)
	- run after migrate hooks
	"""
	def __init__(self, skip_failing: bool = ..., skip_search_index: bool = ..., skip_fixtures: bool = ...) -> None:
		...
	
	def setUp(self): # -> None:
		"""Complete setup required for site migration"""
		...
	
	def tearDown(self): # -> None:
		"""Run operations that should be run post schema updation processes
		This should be executed irrespective of outcome
		"""
		...
	
	@atomic
	def pre_schema_updates(self): # -> None:
		"""Executes `before_migrate` hooks"""
		...
	
	@atomic
	def run_schema_updates(self): # -> None:
		"""Run patches as defined in patches.txt, sync schema changes as defined in the {doctype}.json files"""
		...
	
	@atomic
	def post_schema_updates(self): # -> None:
		"""Execute pending migration tasks post patches execution & schema sync
		This includes:
		* Sync `Scheduled Job Type` and scheduler events defined in hooks
		* Sync fixtures & custom scripts
		* Sync in-Desk Module Dashboards
		* Sync customizations: Custom Fields, Property Setters, Custom Permissions
		* Sync Frappe's internal language master
		* Flush deferred inserts made during maintenance mode.
		* Sync Portal Menu Items
		* Sync Installed Applications Version History
		* Execute `after_migrate` hooks
		"""
		...
	
	def required_services_running(self) -> bool:
		"""Return True if all required services are running. Return False and print
		instructions to stdout when required services are not available.
		"""
		...
	
	def lower_lock_timeout(self): # -> None:
		"""Lower timeout for table metadata locks, default is 1 day, reduce it to 5 minutes.

		This is required to avoid indefinitely waiting for metadata lock.
		"""
		...
	
	def kill_idle_connections(self, idle_limit=...): # -> None:
		"""Assuming migrate has highest priority, kill everything else.

		If someone has connected to mariadb using DB console or ipython console and then acquired
		certain locks we won't be able to migrate."""
		...
	
	def run(self, site: str): # -> None:
		"""Run Migrate operation on site specified. This method initializes
		and destroys connections to the site database.
		"""
		...
	


class DBQueryProgressMonitor(threading.Thread):
	POLL_DURATION = ...
	def __init__(self) -> None:
		...
	
	def run(self): # -> None:
		...
	
	def stop(self): # -> None:
		...
	


