"""
This type stub file was generated by pyright.
"""

click_ctx = ...
if click_ctx:
	...
TEST_WEIGHT_OVERRIDES = ...
class ParallelTestRunner:
	def __init__(self, app, site, build_number=..., total_builds=..., dry_run=..., lightmode=..., failfast=...) -> None:
		...
	
	def setup_and_run(self): # -> None:
		...
	
	def setup_test_site(self): # -> None:
		...
	
	def before_test_setup(self): # -> None:
		...
	
	def setup_test_file_list(self): # -> None:
		...
	
	def run_tests(self): # -> None:
		...
	
	def run_tests_for_file(self, file_info): # -> None:
		...
	
	def get_module(self, path, filename): # -> ModuleType:
		...
	
	def print_result(self): # -> None:
		...
	
	def get_test_file_list(self): # -> list[Any]:
		...
	
	@staticmethod
	def get_test_weight(test): # -> int:
		"""Get approximate count of tests inside a file"""
		...
	


def split_by_weight(work, weights, chunk_count): # -> list[list[Any]]:
	"""Roughly split work by respective weight while keep ordering."""
	...

def get_all_tests(app): # -> list[Any]:
	...

class ParallelTestWithOrchestrator(ParallelTestRunner):
	"""
	This can be used to balance-out test time across multiple instances
	This is dependent on external orchestrator which returns next test to run

	orchestrator endpoints
	- register-instance (<build_id>, <instance_id>, test_spec_list)
	- get-next-test-spec (<build_id>, <instance_id>)
	- test-completed (<build_id>, <instance_id>)
	"""
	def __init__(self, app, site) -> None:
		...
	
	def run_tests(self): # -> None:
		...
	
	def get_test_file_list(self): # -> Generator[Any | None, Any, None]:
		...
	
	def register_instance(self): # -> None:
		...
	
	def get_next_test(self): # -> Any | None:
		...
	
	def print_result(self): # -> None:
		...
	
	def call_orchestrator(self, endpoint, data=...): # -> Any | dict[Any, Any]:
		...
	


