"""
This type stub file was generated by pyright.
"""

std_rights = ...
rights = ...
GUEST_ROLE = ...
ALL_USER_ROLE = ...
SYSTEM_USER_ROLE = ...
ADMIN_ROLE = ...
AUTOMATIC_ROLES = ...
def print_has_permission_check_logs(func): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
	...

@print_has_permission_check_logs
def has_permission(doctype, ptype=..., doc=..., user=..., *, parent_doctype=..., print_logs=..., debug=..., ignore_share_permissions=...) -> bool:
	"""Return True if user has permission `ptype` for given `doctype`.
	If `doc` is passed, also check user, share and owner permissions.

	:param doctype: DocType to check permission for
	:param ptype: Permission Type to check
	:param doc: Check User Permissions for specified document.
	:param user: User to check permission for. Defaults to current user.
	:param print_logs: If True, will display a message using frappe.msgprint
	                which explains why the permission check failed.
	:param parent_doctype:
	        Required when checking permission for a child DocType (unless doc is specified)
	"""
	...

def get_doc_permissions(doc, user=..., ptype=..., debug=...): # -> dict[Any | None, int] | int | Any | dict[Any | str, int]:
	"""Return a dict of evaluated permissions for given `doc` like `{"read":1, "write":1}`"""
	...

def get_role_permissions(doctype_meta, user=..., is_owner=..., debug=...): # -> dict[Any | str, int] | Any:
	"""
	Return dict of evaluated role permissions like:
	        {
	                "read": 1,
	                "write": 0,
	                // if "if_owner" is enabled
	                "if_owner":
	                        {
	                                "read": 1,
	                                "write": 0
	                        }
	        }
	"""
	...

def get_user_permissions(user): # -> dict[Any, Any] | Any | _dict[Any, Any]:
	...

def has_user_permission(doc, user=..., debug=..., *, ptype=..., strict=...):
	"""Return True if User is allowed to view considering User Permissions."""
	...

def has_controller_permissions(doc, ptype, user=..., debug=...) -> bool:
	"""Return controller permissions if denied, True if not defined.

	Controllers can only deny permission, they can not explicitly grant any permission that wasn't
	already present."""
	...

def get_doctypes_with_read(user: str | None = ...): # -> list[str]:
	...

def get_valid_perms(doctype=..., user=...): # -> list[Any]:
	"""Get valid permissions for the current user from DocPerm and Custom DocPerm"""
	...

def get_all_perms(role): # -> list[Any]:
	"""Return valid permissions for a given role."""
	...

def get_roles(user=..., with_standard=...): # -> list[str] | list[Any] | Any | None:
	"""get roles of current user"""
	...

def get_doctype_roles(doctype, access_type=...): # -> list[Any]:
	"""Return a list of roles that are allowed to access the given `doctype`."""
	...

def get_perms_for(roles, perm_doctype=...): # -> list[Any]:
	"""Get perms for given roles"""
	...

def get_doctypes_with_custom_docperms(): # -> list[Any]:
	"""Return all the doctypes with Custom Docperms."""
	...

def add_user_permission(doctype, name, user, ignore_permissions=..., applicable_for=..., is_default=..., hide_descendants=...): # -> None:
	"""Add user permission"""
	...

def remove_user_permission(doctype, name, user): # -> None:
	...

def clear_user_permissions_for_doctype(doctype, user=...): # -> None:
	...

def can_import(doctype, raise_exception=...): # -> bool:
	...

def can_export(doctype, raise_exception=..., is_owner=...): # -> Any | Literal[True]:
	...

def update_permission_property(doctype, role, permlevel, ptype, value=..., validate=..., if_owner=...): # -> Literal[True] | None:
	"""Update a property in Custom Perm"""
	...

def setup_custom_perms(parent): # -> Literal[True] | None:
	"""if custom permssions are not setup for the current doctype, set them up"""
	...

def add_permission(doctype, role, permlevel=..., ptype=...): # -> Data | None:
	"""Add a new permission rule to the given doctype
	for the given Role and Permission Level"""
	...

def copy_perms(parent): # -> None:
	"""Copy all DocPerm in to Custom DocPerm for the given document"""
	...

def reset_perms(doctype): # -> None:
	"""Reset permissions for given doctype."""
	...

def get_linked_doctypes(dt: str) -> list:
	...

def get_doc_name(doc): # -> str | None:
	...

def get_rights(doctype=...): # -> tuple[Literal['select'], Literal['read'], Literal['write'], Literal['create'], Literal['delete'], Literal['submit'], Literal['cancel'], Literal['amend'], Literal['print'], Literal['email'], Literal['report'], Literal['import'], Literal['export'], Literal['share']]:
	...

def allow_everything(doctype=...): # -> dict[Any | str, int]:
	"""Return a dict with access to everything, eg. {"read": 1, "write": 1, ...}."""
	...

def get_allowed_docs_for_doctype(user_permissions, doctype): # -> tuple[list[Any], Any | None] | list[Any]:
	"""Return all the docs from the passed `user_permissions` that are allowed under provided doctype."""
	...

def filter_allowed_docs_for_doctype(user_permissions, doctype, with_default_doc=...): # -> tuple[list[Any], Any | None] | list[Any]:
	"""Return all the docs from the passed `user_permissions` that are
	allowed under provided doctype along with default doc value if `with_default_doc` is set."""
	...

def push_perm_check_log(log, debug=...): # -> None:
	...

def has_child_permission(child_doctype, ptype=..., child_doc=..., user=..., parent_doctype=..., *, debug=..., print_logs=...) -> bool:
	...

def is_system_user(user: str | None = ...) -> bool:
	...

def check_doctype_permission(doctype: str, ptype: str = ...) -> None:
	"""
	Designed specfically to override DoesNotExistError in some scenarios.
	Ignores share permissions.
	"""
	...

def handle_does_not_exist_error(fn): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
	"""
	Decorator to override DoesNotExistError when handling exceptions.
	Requires the first argument to be an Exception.
	"""
	...

def check_app_permission(): # -> bool:
	...

