"""
This type stub file was generated by pyright.
"""

import frappe

class PushNotification:
	def __init__(self, project_name: str) -> None:
		"""
		:param project_name: (str) The name of the project.
		"""
		...
	
	def add_token(self, user_id: str, token: str) -> tuple[bool, str]:
		"""
		Add a token for a user.

		:param user_id: (str) The ID of the user. This should be user's unique identifier.
		:param token: (str) The token to be added.
		:return: tuple[bool, str] First element is the success status, second element is the message.
		"""
		...
	
	def remove_token(self, user_id: str, token: str) -> tuple[bool, str]:
		"""
		Remove a token for a user.

		:param user_id: (str) The ID of the user. This should be user's unique identifier.
		:param token: (str) The token to be removed.
		:return: tuple[bool, str] First element is the success status, second element is the message.
		"""
		...
	
	def add_topic(self, topic_name: str) -> bool:
		"""
		Add a notification topic.

		:param topic_name: (str) The name of the topic.
		:return: bool True if successful, False otherwise.
		"""
		...
	
	def remove_topic(self, topic_name: str) -> bool:
		"""
		Remove a notification topic.

		:param topic_name: (str) The name of the topic.
		:return: bool True if successful, False otherwise.
		"""
		...
	
	def subscribe_topic(self, user_id: str, topic_name: str) -> bool:
		"""
		Subscribe a user to a topic.

		:param user_id: (str) The ID of the user. This should be user's unique identifier.
		:param topic_name: (str) The name of the topic. This topic should be already created.
		:return: bool True if successful, False otherwise.
		"""
		...
	
	def unsubscribe_topic(self, user_id: str, topic_name: str) -> bool:
		"""
		Unsubscribe a user from a topic.

		:param user_id: (str) The ID of the user. This should be user's unique identifier.
		:param topic_name: (str) The name of the topic. This topic should be already created.
		:return: bool True if successful, False otherwise.
		"""
		...
	
	def send_notification_to_user(self, user_id: str, title: str, body: str, link: str | None = ..., icon: str | None = ..., data: dict | None = ..., truncate_body: bool = ..., strip_html: bool = ...) -> bool:
		"""
		Send notification to a user.

		:param user_id: (str) The ID of the user. This should be user's unique identifier.
		:param title: (str) The title of the notification.
		:param body: (str) The body of the notification. At max 1000 characters.
		:param link: (str) The link to be opened when the notification is clicked.
		:param icon: (str) The icon to be shown in the notification.
		:param data: (dict) The data to be sent with the notification. This can be used to provide extra information while dealing with in-app notifications.
		:param truncate_body: (bool) Whether to truncate the body or not. If True, the body will be truncated to 1000 characters.
		:param strip_html: (bool) Whether to strip HTML tags from the body or not.
		:return: bool True if the request queued successfully, False otherwise.
		"""
		...
	
	def send_notification_to_topic(self, topic_name: str, title: str, body: str, link: str | None = ..., icon: str | None = ..., data: dict | None = ..., truncate_body: bool = ..., strip_html: bool = ...) -> bool:
		"""
		Send notification to a notification topic.

		:param topic_name: (str) The name of the topic. This topic should be already created.
		:param title: (str) The title of the notification.
		:param body: (str) The body of the notification. At max 1000 characters.
		:param link: (str) The link to be opened when the notification is clicked.
		:param icon: (str) The icon to be shown in the notification.
		:param data: (dict) The data to be sent with the notification. This can be used to provide extra information while dealing with in-app notifications.
		:param truncate_body: (bool) Whether to truncate the body or not. If True, the body will be truncated to 1000 characters.
		:param strip_html: (bool) Whether to strip HTML tags from the body or not.
		:return: bool True if the request queued successfully, False otherwise.
		"""
		...
	
	def is_enabled(self) -> bool:
		"""
		Check whether the push notification relay is enabled or not.

		:return: bool True if enabled, False otherwise.
		"""
		...
	


@frappe.whitelist(allow_guest=True, methods=["GET"])
def auth_webhook(secret: str): # -> Response:
	...

@frappe.whitelist(methods=["GET"])
def subscribe(fcm_token: str, project_name: str) -> dict:
	...

@frappe.whitelist(methods=["GET"])
def unsubscribe(fcm_token: str, project_name: str) -> dict:
	...

