"""
This type stub file was generated by pyright.
"""

import frappe
from typing import TYPE_CHECKING

if TYPE_CHECKING:
	...
@frappe.whitelist()
def add(doctype: str, name: str | int, user: str | None = ..., read: str | bool | int = ..., write: str | bool | int = ..., submit: str | bool | int = ..., share: str | bool | int = ..., everyone: str | bool | int = ..., notify: str | bool | int = ..., **kwargs): # -> Document:
	"""Expose function without flags to the client-side"""
	...

def add_docshare(doctype, name, user=..., read=..., write=..., submit=..., share=..., everyone=..., flags=..., notify=..., **kwargs): # -> Document:
	"""Share the given document with a user."""
	...

def remove(doctype, name, user, flags=...): # -> None:
	...

@frappe.whitelist()
def set_permission(doctype: str, name: str | int, user: str | None, permission_to: str, value: str | bool | int = ..., everyone: str | bool | int = ...): # -> Document | None:
	"""Expose function without flags to the client-side"""
	...

def set_docshare_permission(doctype, name, user, permission_to, value=..., everyone=..., flags=...): # -> Document | None:
	"""Set share permission."""
	...

@frappe.whitelist()
def get_users(doctype: str, name: str) -> list:
	"""Get list of users with which this document is shared"""
	...

def get_shared(doctype, user=..., rights=..., *, filters=..., limit=...): # -> list[Any]:
	"""Get list of shared document names for given user and DocType.

	:param doctype: DocType of which shared names are queried.
	:param user: User for which shared names are queried.
	:param rights: List of rights for which the document is shared. List of `read`, `write`, `share`"""
	...

def get_shared_doctypes(user=...):
	"""Return list of doctypes in which documents are shared for the given user."""
	...

def get_share_name(doctype, name, user, everyone): # -> list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | _dict[Any, Any] | list[Any | None] | None:
	...

def check_share_permission(doctype, name, permissions=..., custom_perms=...): # -> None:
	"""Check if the user can share with other users and has the permissions they are trying to grant.

	:param doctype: DocType being shared
	:param name: Document name being shared
	:param permissions: Permissions that the user wants to share
	:param custom_perms: List of custom permission types for the doctype
	"""
	...

def notify_assignment(shared_by, doctype, doc_name, everyone, notify=...): # -> None:
	...

