"""
This type stub file was generated by pyright.
"""

import functools
import frappe
from contextlib import contextmanager
from frappe.utils.caching import http_cache

"""
frappe.translate
~~~~~~~~~~~~~~~~

Translation tools for frappe
"""
REPORT_TRANSLATE_PATTERN = ...
CSV_STRIP_WHITESPACE_PATTERN = ...
MERGED_TRANSLATION_KEY = ...
USER_TRANSLATION_KEY = ...
TRANSLATION_VERSION_KEY = ...
def get_language(lang_list: list | None = ...) -> str:
	"""Set `frappe.local.lang` from HTTP headers at beginning of request

	Order of priority for setting language:
	1. Form Dict => _lang
	2. Cookie => preferred_language (Non authorized user)
	3. Request Header => Accept-Language (Non authorized user)
	4. User document => language
	5. System Settings => language
	"""
	...

@functools.lru_cache
def get_parent_language(lang: str) -> str:
	"""If the passed language is a variant, return its parent

	Eg:
	        1. zh-TW -> zh
	        2. sr-BA -> sr
	"""
	...

def get_user_lang(user: str | None = ...) -> str:
	"""Set frappe.local.lang from user preferences on session beginning or resumption"""
	...

def get_lang_code(lang: str) -> str | None:
	...

def set_default_language(lang): # -> None:
	"""Set Global default language"""
	...

def get_lang_dict(): # -> dict[Any, Any]:
	"""Return all languages in dict format, full name is the key e.g. `{"english":"en"}`."""
	...

def get_messages_for_boot(): # -> dict[str, str]:
	"""Return all message translations that are required on boot."""
	...

@frappe.whitelist(allow_guest=True, methods=["GET"])
@http_cache(max_age=31536000)
def get_boot_translations(lang: str | None = ...) -> dict[str, str]:
	"""Return all translations for the current user's language."""
	...

def get_all_translations(lang: str) -> dict[str, str]:
	"""Load and return the entire translations dictionary for a language from apps + user translations.

	:param lang: Language Code, e.g. `hi` or `es-CO`
	"""
	...

def get_translations_from_apps(lang, apps=...): # -> dict[Any, Any]:
	"""Combine all translations from `.csv` files in all `apps`.
	For derivative languages (es-GT), take translations from the
	base language (es) and then update translations from the child (es-GT)"""
	...

def get_translations_from_csv(lang, app): # -> dict[str, str]:
	...

def get_translation_dict_from_file(path, lang, app, throw=...) -> dict[str, str]:
	"""Return translation dict from given CSV file at path"""
	...

def get_user_translations(lang): # -> Any | None:
	...

def clear_cache(): # -> None:
	"""Clear all translation assets from :meth:`frappe.cache`"""
	...

def get_translation_version() -> str:
	"""Return the current translation version from cache."""
	...

def change_translation_version(): # -> None:
	"""Generate a new random translation version to invalidate browser caches."""
	...

def get_messages_for_app(app, deduplicate=...): # -> list[Any]:
	"""Return all messages (list) for a specified `app`."""
	...

def get_messages_from_navbar(): # -> list[tuple[str, Any, str]]:
	"""Return all labels from Navbar Items, as specified in Navbar Settings."""
	...

def get_messages_from_doctype(name): # -> list[tuple[Any | str, Any]]:
	"""Extract all translatable messages for a doctype. Includes labels, Python code,
	Javascript code, html templates"""
	...

def get_messages_from_workflow(doctype=..., app_name=...): # -> list[Any]:
	...

def get_messages_from_custom_fields(app_name): # -> list[Any]:
	...

def get_messages_from_page(name): # -> list[tuple[str, str, str | None, int]]:
	"""Return all translatable strings from a :class:`frappe.core.doctype.Page`."""
	...

def get_messages_from_report(name): # -> list[tuple[str, str, str | None, int]]:
	"""Return all translatable strings from a :class:`frappe.core.doctype.Report`."""
	...

def get_server_messages(app): # -> list[Any]:
	"""Extracts all translatable strings (tagged with :func:`frappe._`) from Python modules
	inside an app"""
	...

def get_messages_from_include_files(app_name=...): # -> list[Any]:
	"""Return messages from js files included at time of boot like desk.min.js for desk and web."""
	...

def get_all_messages_from_js_files(app_name=...): # -> list[Any]:
	"""Extracts all translatable strings from app `.js` files"""
	...

def get_messages_from_file(path: str) -> list[tuple[str, str, str | None, int]]:
	"""Return a list of transatable strings from a code file.

	:param path: path of the code file
	"""
	...

def extract_messages_from_python_code(code: str) -> list[tuple[int, str, str | None]]:
	"""Extracts translatable strings from Python code using babel."""
	...

def extract_messages_from_javascript_code(code: str) -> list[tuple[int, str, str | None]]:
	"""Extracts translatable strings from JavaScript code using babel."""
	...

def read_csv_file(path): # -> list[list[str]]:
	"""Read CSV file and return as list of list

	:param path: File path"""
	...

def write_csv_file(path, app_messages, lang_dict): # -> None:
	"""Write translation CSV file.

	:param path: File path, usually `[app]/translations`.
	:param app_messages: Translatable strings for this app.
	:param lang_dict: Full translated dict.
	"""
	...

def get_untranslated(lang, untranslated_file, get_all=..., app=...): # -> None:
	"""Return all untranslated strings for a language and write in a file.

	:param lang: Language code.
	:param untranslated_file: Output file path.
	:param get_all: Return all strings, translated or not."""
	...

def update_translations(lang, untranslated_file, translated_file, app=...): # -> None:
	"""Update translations from a source and target file for a given language.

	:param lang: Language code (e.g. `en`).
	:param untranslated_file: File path with the messages in English.
	:param translated_file: File path with messages in language to be updated."""
	...

def import_translations(lang, path): # -> None:
	"""Import translations from file in standard format"""
	...

def migrate_translations(source_app, target_app): # -> None:
	"""Migrate target-app-specific translations from source-app to target-app"""
	...

def rebuild_all_translation_files(): # -> None:
	"""Rebuild all translation files: `[app]/translations/[lang].csv`."""
	...

def write_translations_file(app, lang, full_dict=..., app_messages=...): # -> None:
	"""Write a translation file for a given language.

	:param app: `app` for which translations are to be written.
	:param lang: Language code.
	:param full_dict: Full translated language dict (optional).
	:param app_messages: Source strings (optional).
	"""
	...

def send_translations(translation_dict): # -> None:
	"""Append translated dict in `frappe.local.response`"""
	...

def deduplicate_messages(messages): # -> list[Any]:
	...

@frappe.whitelist()
def update_translations_for_source(source: str | None = ..., translation_dict: str | None = ...): # -> list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | None:
	...

@frappe.whitelist(allow_guest=True)
def get_all_languages(with_language_name: bool = ...) -> list:
	"""Return all enabled language codes ar, ch etc."""
	...

def get_preferred_language_cookie(): # -> str | None:
	...

def get_translated_doctypes(): # -> list[Any]:
	...

@contextmanager
def print_language(language: str): # -> Generator[None, Any, None]:
	"""Ensure correct globals for printing in a specific language.

	Usage:

	```
	with print_language("de"):
	    html = frappe.get_print(...)
	```
	"""
	...

get_full_dict = ...
load_lang = ...
