"""
This type stub file was generated by pyright.
"""

import frappe

PARENT_FOR_DEFAULTS = ...
def get_default(key): # -> _dict[Any, Any] | Any | list[Any] | None:
	...

def set_default(key, value): # -> None:
	...

def clear_default(key): # -> None:
	...

class ExpiredLoginException(Exception):
	...


def toggle_two_factor_auth(state, roles=...): # -> None:
	"""Enable or disable 2FA in site_config and roles"""
	...

def two_factor_is_enabled(user=...): # -> int | bool:
	"""Return True if 2FA is enabled."""
	...

def should_run_2fa(user): # -> int | bool:
	"""Check if 2fa should run."""
	...

def get_cached_user_pass(): # -> tuple[Any | None, Any | None]:
	"""Get user and password if set."""
	...

def authenticate_for_2factor(user): # -> None:
	"""Authenticate two factor for enabled user before login."""
	...

def cache_2fa_data(user, token, otp_secret, tmp_id): # -> None:
	"""Cache and set expiry for data."""
	...

def two_factor_is_enabled_for_(user): # -> bool:
	"""Check if 2factor is enabled for user."""
	...

def get_otpsecret_for_(user): # -> str | None:
	"""Set OTP Secret for user even if not set."""
	...

def get_verification_method(): # -> Any | None:
	...

def confirm_otp_token(login_manager, otp=..., tmp_id=...): # -> bool | None:
	"""Confirm otp matches."""
	...

def get_verification_obj(user, token, otp_secret): # -> dict[str, Any] | None:
	...

def process_2fa_for_sms(user, token, otp_secret): # -> dict[str, Any]:
	"""Process sms method for 2fa."""
	...

def process_2fa_for_otp_app(user, otp_secret, otp_issuer): # -> dict[str, Any]:
	"""Process OTP App method for 2fa."""
	...

def process_2fa_for_email(user, token, otp_secret, otp_issuer, method=...): # -> dict[str, Any]:
	"""Process Email method for 2fa."""
	...

def get_email_subject_for_2fa(kwargs_dict): # -> str | Any | None:
	"""Get email subject for 2fa."""
	...

def get_email_body_for_2fa(kwargs_dict): # -> str | Any | None:
	"""Get email body for 2fa."""
	...

def get_email_subject_for_qr_code(kwargs_dict): # -> str | Any | None:
	"""Get QRCode email subject."""
	...

def get_email_body_for_qr_code(kwargs_dict): # -> str | Any | None:
	"""Get QRCode email body."""
	...

def get_link_for_qrcode(user, totp_uri): # -> str:
	"""Get link to temporary page showing QRCode."""
	...

def send_token_via_sms(otpsecret, token=..., phone_no=...): # -> Any | bool:
	"""Send token as sms to user."""
	...

def get_rendered_otp_message(otp: str) -> str:
	...

def send_token_via_email(user, token, otp_secret, otp_issuer, subject=..., message=...): # -> bool:
	"""Send token to user as email."""
	...

def get_qr_svg_code(totp_uri): # -> bytes:
	"""Get SVG code to display Qrcode for OTP."""
	...

def create_barcode_folder(): # -> list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | _dict[Any, Any] | list[Any | None] | Data | None:
	"""Get Barcodes folder."""
	...

def delete_qrimage(user, check_expiry=...): # -> None:
	"""Delete Qrimage when user logs in."""
	...

def delete_all_barcodes_for_users(): # -> None:
	"""Task to delete all barcodes for user."""
	...

def should_remove_barcode_image(barcode): # -> bool:
	"""Check if it's time to delete barcode image from server."""
	...

def disable(): # -> None:
	...

@frappe.whitelist()
def reset_otp_secret(user: str): # -> None:
	...

