"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.email.receive import EmailServer, InboundMail
from frappe.model.document import Document

class SentEmailInInbox(Exception):
	...


def cache_email_account(cache_name): # -> Callable[..., _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]]:
	...

class EmailAccount(Document):
	_DOCTYPE_NAME = ...
	if TYPE_CHECKING:
		add_reply_to_header: DF.Check
		add_signature: DF.Check
		add_x_original_from: DF.Check
		always_bcc: DF.Data | None
		always_use_account_email_id_as_sender: DF.Check
		always_use_account_name_as_sender_name: DF.Check
		api_key: DF.Data | None
		api_secret: DF.Password | None
		append_emails_to_sent_folder: DF.Check
		append_to: DF.Link | None
		ascii_encode_password: DF.Check
		attachment_limit: DF.Int
		auth_method: DF.Literal[Basic, OAuth]
		auto_reply_message: DF.TextEditor | None
		awaiting_password: DF.Check
		backend_app_flow: DF.Check
		brand_logo: DF.AttachImage | None
		connected_app: DF.Link | None
		connected_user: DF.Link | None
		create_contact: DF.Check
		default_incoming: DF.Check
		default_outgoing: DF.Check
		domain: DF.Link | None
		dsn_notify_type: DF.Literal[SUCCESS, FAILURE, DELAY, "SUCCESS,FAILURE", "SUCCESS,FAILURE,DELAY", NEVER]
		email_account_name: DF.Data | None
		email_id: DF.Data
		email_server: DF.Data | None
		email_sync_option: DF.Literal[ALL, UNSEEN]
		enable_auto_reply: DF.Check
		enable_automatic_linking: DF.Check
		enable_incoming: DF.Check
		enable_outgoing: DF.Check
		footer: DF.TextEditor | None
		frappe_mail_site: DF.Data | None
		imap_folder: DF.Table[IMAPFolder]
		incoming_port: DF.Data | None
		initial_sync_count: DF.Literal[100, 250, 500]
		last_received_at: DF.Datetime | None
		login_id: DF.Data | None
		login_id_is_different: DF.Check
		no_failed: DF.Int
		no_smtp_authentication: DF.Check
		notify_if_unreplied: DF.Check
		password: DF.Password | None
		reply_to_addresses: DF.Table[ReplyToAddress]
		send_notification_to: DF.SmallText | None
		send_unsubscribe_message: DF.Check
		sent_folder_name: DF.Data | None
		service: DF.Literal["", "Frappe Mail", GMail, Sendgrid, SparkPost, "Yahoo Mail", Outlook.com, Yandex.Mail]
		signature: DF.TextEditor | None
		smtp_port: DF.Data | None
		smtp_server: DF.Data | None
		track_email_status: DF.Check
		uidnext: DF.Int
		uidvalidity: DF.Data | None
		unreplied_for_mins: DF.Int
		use_imap: DF.Check
		use_ssl: DF.Check
		use_ssl_for_outgoing: DF.Check
		use_starttls: DF.Check
		use_tls: DF.Check
		validate_ssl_certificate: DF.Check
		...
	DOCTYPE = ...
	def autoname(self): # -> None:
		"""Set name as `email_account_name` or make title from Email Address."""
		...
	
	def validate(self): # -> None:
		"""Validate Email Address and check POP3/IMAP and SMTP connections is enabled."""
		...
	
	@frappe.whitelist()
	def validate_frappe_mail_settings(self): # -> None:
		...
	
	def validate_imap_folders_exist(self, server: EmailServer) -> None:
		"""Validate that each configured IMAP folder exists on the server by attempting to SELECT it directly."""
		...
	
	def validate_smtp_conn(self): # -> None:
		...
	
	def validate_reply_to_addresses(self) -> None:
		...
	
	def validate_dsn(self, smtp_session) -> None:
		"""Validate if the configured SMTP server supports DSN (Delivery Status Notification)."""
		...
	
	def before_save(self): # -> None:
		...
	
	def on_update(self): # -> None:
		"""Check there is only one default of each type."""
		...
	
	def clear_cache(self): # -> None:
		...
	
	def there_must_be_only_one_default(self): # -> None:
		"""If current Email Account is default, un-default all other accounts."""
		...
	
	@frappe.whitelist()
	def get_domain_values(self, domain: str): # -> list[Any] | list[_dict[Any, Any]] | list[list[Any | None]] | dict[Any, Any] | _dict[Any, Any] | list[Any | None] | None:
		...
	
	def get_incoming_server(self, in_receive=..., email_sync_rule=...): # -> EmailServer:
		"""Return logged in POP3/IMAP connection object."""
		...
	
	def check_email_server_connection(self, email_server, in_receive): # -> None:
		...
	
	@property
	def default_sender(self): # -> str:
		...
	
	def is_exists_in_db(self): # -> EmailAccount:
		"""Some of the Email Accounts we create from configs and those doesn't exists in DB.
		This is is to check the specific email account exists in DB or not.
		"""
		...
	
	@classmethod
	def from_record(cls, record): # -> Document:
		...
	
	@classmethod
	def find(cls, name): # -> Document:
		...
	
	@classmethod
	def find_one_by_filters(cls, **kwargs) -> EmailAccount:
		...
	
	@classmethod
	def find_from_config(cls): # -> Document | None:
		...
	
	@classmethod
	def create_dummy(cls): # -> Document:
		...
	
	@classmethod
	@cache_email_account("outgoing_email_account")
	def find_outgoing(cls, match_by_email=..., match_by_doctype=..., _raise_error=...): # -> dict[str | Any, EmailAccount] | dict[Any, EmailAccount] | dict[str, EmailAccount] | None:
		"""Find the outgoing Email account to use.

		:param match_by_email: Find account using emailID
		:param match_by_doctype: Find account by matching `Append To` doctype
		:param _raise_error: This is used by raise_error_on_no_output decorator to raise error.
		"""
		...
	
	@classmethod
	def find_default_outgoing(cls): # -> EmailAccount:
		"""Find default outgoing account."""
		...
	
	@classmethod
	def find_incoming(cls, match_by_email=..., match_by_doctype=...): # -> EmailAccount | None:
		"""Find the incoming Email account to use.
		:param match_by_email: Find account using emailID
		:param match_by_doctype: Find account by matching `Append To` doctype
		"""
		...
	
	@classmethod
	def find_default_incoming(cls): # -> EmailAccount:
		...
	
	@classmethod
	def get_account_details_from_site_config(cls): # -> dict[Any, Any]:
		...
	
	def get_access_token(self) -> str | None:
		...
	
	def sendmail_config(self): # -> dict[str, Any]:
		...
	
	def get_smtp_server(self): # -> SMTPServer:
		"""Get SMTPServer (wrapper around actual smtplib object) for this account.

		Implementation Detail: Since SMTPServer is same for each email connection, the same *instance*
		is returned every time this function is called from same EmailAccount object.
		This enables reusabilty of connection for better performance."""
		...
	
	def get_frappe_mail_client(self): # -> FrappeMail | None:
		...
	
	def remove_unpicklable_values(self, state): # -> None:
		...
	
	def handle_incoming_connect_error(self, description): # -> None:
		...
	
	def set_failed_attempts_count(self, value): # -> None:
		...
	
	def get_failed_attempts_count(self): # -> int:
		...
	
	def receive(self): # -> None:
		"""Called by scheduler to receive emails from this EMail account using POP3/IMAP."""
		...
	
	def get_inbound_mails(self) -> list[InboundMail]:
		"""retrive and return inbound mails."""
		...
	
	def handle_bad_emails(self, uid, raw, reason): # -> None:
		"""Save the email in Unhandled Email doctype.

		The excessive encoding and decoding is done to handle the case where the
		email contains invalid characters. This should fail when parsing, not
		when storing the email in the database.
		"""
		...
	
	def send_auto_reply(self, communication, email): # -> None:
		"""Send auto reply if set."""
		...
	
	def get_unreplied_notification_emails(self): # -> list[str]:
		"""Return list of emails listed"""
		...
	
	def on_trash(self): # -> None:
		"""Clear communications where email account is linked"""
		...
	
	def after_rename(self, old, new, merge=...): # -> None:
		...
	
	def build_email_sync_rule(self): # -> str:
		...
	
	def check_automatic_linking_email_account(self): # -> None:
		...
	
	def append_email_to_sent_folder(self, message): # -> None:
		...
	
	def get_oauth_token(self): # -> None:
		...
	


@frappe.whitelist()
def get_append_to(doctype: str | None = ..., txt: str | None = ..., searchfield: str | None = ..., start: int | None = ..., page_len: int | None = ..., filters: list | dict | str | None = ...): # -> list[list[Any]]:
	...

def notify_unreplied(): # -> None:
	"""Sends email notifications if there are unreplied Communications
	and `notify_if_unreplied` is set as true."""
	...

def pull(now=...): # -> None:
	"""Will be called via scheduler, pull emails from all enabled Email accounts."""
	...

@frappe.whitelist()
def pull_emails(email_account: str) -> None:
	"""Pull emails from given email account."""
	...

def pull_from_email_account(email_account): # -> None:
	"""Runs within a worker process"""
	...

def get_max_email_uid(email_account): # -> int:
	"""get maximum uid of emails"""
	...

def setup_user_email_inbox(email_account, awaiting_password, email_id, enable_outgoing, used_oauth): # -> None:
	"""setup email inbox for user"""
	...

def remove_user_email_inbox(email_account): # -> None:
	"""remove user email inbox settings if email account is deleted"""
	...

@frappe.whitelist()
def set_email_password(email_account: str, password: str): # -> bool:
	...

def get_automatic_email_link(): # -> Any | None:
	...

def on_doctype_update() -> None:
	...

