"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.rate_limiter import rate_limit

no_cache = ...
def get_context(context):
	...

@frappe.whitelist(allow_guest=True)
def login_via_token(login_token: str): # -> None:
	...

def get_login_with_email_link_ratelimit() -> int:
	...

@frappe.whitelist(allow_guest=True, methods=["POST"])
@rate_limit(limit=get_login_with_email_link_ratelimit, seconds=60 * 60)
def send_login_link(email: str): # -> None:
	...

@frappe.whitelist(allow_guest=True, methods=["GET"])
@rate_limit(limit=get_login_with_email_link_ratelimit, seconds=60 * 60)
def login_via_key(key: str): # -> None:
	...

def sanitize_redirect(redirect: str | None) -> str | None:
	"""Only allow redirect on same domain.

	Allowed redirects:
	- Same host e.g. https://frappe.localhost/path
	- Just path e.g. /app gets converted to https://frappe.localhost/app
	"""
	...

