"""
This type stub file was generated by pyright.
"""

import frappe
from typing import TYPE_CHECKING, TypedDict
from frappe.core.doctype.docfield.docfield import DocField
from frappe.model.document import Document
from frappe.model.meta import Meta
from frappe.printing.doctype.print_format.print_format import PrintFormat
from frappe.printing.doctype.print_settings.print_settings import PrintSettings

if TYPE_CHECKING:
	...
no_cache = ...
standard_format = ...
class PrintContext(TypedDict):
	body: str
	print_style: str
	comment: str
	title: str
	lang: str
	layout_direction: str
	doctype: str
	name: str
	key: str
	...


def get_context(context) -> PrintContext:
	"""Build context for print"""
	...

def get_print_format_doc(print_format_name: str, meta: Meta) -> PrintFormat | None:
	"""Return print format document."""
	...

def get_rendered_template(doc: Document, print_format: PrintFormat | None = ..., meta: Meta = ..., no_letterhead: bool | None = ..., letterhead: str | None = ..., trigger_print: bool = ..., settings: dict | None = ...) -> str:
	...

def set_link_titles(doc: Document) -> None:
	...

def set_title_values_for_link_and_dynamic_link_fields(meta: Meta, doc: Document, parent_doc: Document | None = ...) -> None:
	...

def set_title_values_for_table_and_multiselect_fields(meta: Meta, doc: Document) -> None:
	...

def convert_markdown(doc: Document) -> None:
	"""Convert text field values to markdown if necessary."""
	...

@frappe.whitelist()
def get_html_and_style(doc: str, name: str | None = ..., print_format: str | None = ..., no_letterhead: bool | None = ..., letterhead: str | None = ..., trigger_print: bool = ..., style: str | None = ..., settings: str | None = ...) -> dict[str, str | None]:
	"""Return `html` and `style` of print format, used in PDF etc."""
	...

@frappe.whitelist()
def get_rendered_raw_commands(doc: str, name: str | None = ..., print_format: str | None = ...) -> dict:
	"""Return Rendered Raw Commands of print format, used to send directly to printer."""
	...

def validate_print_permission(doc: Document) -> None:
	...

def validate_key(key: str, doc: Document) -> None:
	...

def get_letter_head(doc: Document, no_letterhead: bool, letterhead: str | None = ...) -> dict:
	...

def get_print_format(doctype: str, print_format: PrintFormat) -> str:
	...

def make_layout(doc: Document, meta: Meta, format_data=...) -> list:
	"""Builds a hierarchical layout object from the fields list to be rendered
	by `standard.html`

	:param doc: Document to be rendered.
	:param meta: Document meta object (doctype).
	:param format_data: Fields sequence and properties defined by Print Format Builder."""
	...

def is_visible(df: DocField, doc: Document) -> bool:
	"""Return True if docfield is visible in print layout and does not have print_hide set."""
	...

def has_value(df: DocField, doc: Document) -> bool:
	"""Return True if given docfield (`df`) has some value in the given document (`doc`)."""
	...

def get_print_style(style: str | None = ..., print_format: PrintFormat | None = ..., for_legacy: bool = ...) -> str:
	...

def get_font(print_settings: PrintSettings, print_format: PrintFormat | None = ..., for_legacy=...) -> str:
	...

def get_visible_columns(data: list, table_meta: Meta, df: DocField) -> list[DocField]:
	"""Return list of visible columns based on print_hide and if all columns have value."""
	...

def column_has_value(data: list, fieldname: str, col_df: DocField) -> bool:
	"""Check if at least one cell in column has non-zero and non-blank value"""
	...

trigger_print_script = ...
