"""
This type stub file was generated by pyright.
"""

from frappe.utils.caching import redis_cache

no_cache = ...
base_template_path = ...
def get_context(context): # -> dict[str, list[dict[str, str]]]:
	"""generate the sitemap XML"""
	...

@redis_cache(ttl=6 * 60 * 60)
def get_public_pages_from_doctypes(): # -> dict[Any, Any]:
	"""Return pages from doctypes that are publicly accessible."""
	...

