"""
This type stub file was generated by pyright.
"""

import frappe
from typing import Any

def get_base_url(): # -> Any | Literal['https://frappecloud.com'] | None:
	...

def get_site_login_url(): # -> str:
	...

def get_site_name(): # -> Any | None:
	...

def get_headers(): # -> dict[str, Any]:
	...

@frappe.whitelist()
def current_site_info(): # -> Any | dict[Any, Any] | None:
	...

@frappe.whitelist()
def api(method: str, data: str | dict[str, Any] | None = ...): # -> Any | None:
	...

@frappe.whitelist()
def is_fc_site() -> bool:
	...

@frappe.whitelist()
def send_verification_code(): # -> Any | None:
	...

@frappe.whitelist()
def verify_verification_code(verification_code: str, route: str): # -> dict[str, Any] | None:
	...

