"""
This type stub file was generated by pyright.
"""

import frappe

def get(name): # -> _dict[Any, Any]:
	"""
	Return the :term:`doclist` of the `Page` specified by `name`
	"""
	...

@frappe.whitelist(allow_guest=True)
def getpage(name: str): # -> None:
	"""
	Load the page from `frappe.form` and send it via `frappe.response`
	"""
	...

