"""
This type stub file was generated by pyright.
"""

import frappe
from frappe.desk.desk_views import DeskViews

def handle_not_exist(fn): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any | list[Any]]:
	...

class Workspace(DeskViews):
	def __init__(self, page, minimal=...) -> None:
		...
	
	def is_permitted(self): # -> Literal[True] | None:
		"""Return true if `Has Role` is not set or the user is allowed."""
		...
	
	def get_cached(self, cache_key, fallback_fn): # -> Any:
		...
	
	def get_can_read_items(self): # -> list[Any] | Any:
		...
	
	def get_allowed_modules(self): # -> Any | list[Any]:
		...
	
	def get_onboarding_doc(self, onboarding): # -> Document | None:
		...
	
	def build_workspace(self): # -> None:
		...
	
	def is_custom_block_permitted(self, custom_block_name): # -> bool:
		...
	
	@handle_not_exist
	def get_links(self): # -> list[Any]:
		...
	
	@handle_not_exist
	def get_charts(self): # -> list[Any]:
		...
	
	@handle_not_exist
	def get_shortcuts(self): # -> list[Any]:
		...
	
	@handle_not_exist
	def get_quick_lists(self): # -> list[Any]:
		...
	
	@handle_not_exist
	def get_number_cards(self): # -> list[Any]:
		...
	
	@handle_not_exist
	def get_custom_blocks(self): # -> list[Any]:
		...
	


@frappe.whitelist()
@frappe.read_only()
def get_desktop_page(page: str): # -> dict[str, dict[str, list[Any]]] | dict[Any, Any]:
	"""Apply permissions, customizations and return the configuration for a page on desk.

	Args:
	        page (json): page data

	Return:
	        dict: dictionary of cards, charts and shortcuts to be displayed on website
	"""
	...

@frappe.whitelist()
def get_workspaces(): # -> dict[str, Any]:
	"""Get list of sidebar items for desk"""
	...

def get_table_with_counts(): # -> dict[Any, Any] | Any | None:
	...

def get_custom_reports_and_doctypes(module): # -> list[_dict[str, str | list[dict[str, Any]]]]:
	...

def get_custom_doctype_list(module): # -> list[dict[str, Any]]:
	...

def get_custom_report_list(module): # -> list[dict[str, Any]]:
	"""Return list on new style reports for modules."""
	...

def save_new_widget(doc, page, blocks, new_widgets): # -> Literal[True]:
	...

def clean_up(original_page, blocks): # -> None:
	...

def new_widget(config, doctype, parentfield): # -> list[Any]:
	...

def prepare_widget(config, doctype, parentfield): # -> list[Any]:
	"""Create widget child table entries with parent details.

	Args:
	        config (dict): Dictionary containing widget config
	        doctype (string): Doctype name of the child table
	        parentfield (string): Parent field for the child table

	Return:
	        TYPE: List of Document objects
	"""
	...

@frappe.whitelist()
def update_onboarding_step(name: str | int, field: str, value: int | str): # -> None:
	"""Update status of onboaridng step

	Args:
	        name (string): Name of the doc
	        field (string): field to be updated
	        value: Value to be updated

	"""
	...

@frappe.whitelist()
def get_installed_apps():
	...

@frappe.whitelist()
@frappe.read_only()
def get_onboarding_data(module: str): # -> list[Any] | None:
	"""Get onboarding data for a page

	Args:
	        page (string): page name

	Return:
	        dict: onboarding data
	"""
	...

def get_onboarding_step_maps(onboarding): # -> list[Any]:
	...

