"""
This type stub file was generated by pyright.
"""

import frappe
from typing import Literal

@frappe.whitelist()
@frappe.read_only()
def get_notifications(): # -> dict[str, dict[Any, Any]]:
	...

def get_notifications_for_doctypes(config, notification_count): # -> dict[Any, Any]:
	"""Notifications for DocTypes"""
	...

def get_notifications_for_targets(config, notification_percent): # -> dict[Any, Any]:
	"""Notifications for doc targets"""
	...

def clear_notifications(user=...): # -> None:
	...

def clear_notification_config(user): # -> None:
	...

def delete_notification_count_for(doctype): # -> None:
	...

def clear_doctype_notifications(doc, method=..., *args, **kwargs): # -> None:
	...

@frappe.whitelist()
def get_notification_info(): # -> dict[str, dict[Any, Any]]:
	...

def get_notification_config(): # -> Any | None:
	...

def get_filters_for(doctype): # -> Any | None:
	"""get open filters for doctype"""
	...

@frappe.whitelist()
@frappe.read_only()
def get_open_count(doctype: str, name: str | int, items: str | list[str] | None = ...): # -> dict[str, list[Any]] | dict[str, dict[str, list[Any]]]:
	"""Get count for internal and external links for given transactions

	:param doctype: Reference DocType
	:param name: Reference Name
	:param items: Optional list of transactions (json/dict)"""
	...

def get_internal_links(doc, link, link_doctype): # -> dict[str, Any]:
	...

def get_external_links(doctype, name, links): # -> dict[str, Any]:
	...

def get_doc_count(doctype, filters) -> int | Literal["?"]:
	...

def get_dynamic_link_filters(doctype, links, fieldname): # -> dict[Any, Any] | None:
	"""
	- Updating filters based on dynamic_links specified in the dashboard data.
	- Eg: "dynamic_links": {"fieldname": ["dynamic_fieldvalue", "dynamic_fieldname"]},
	"""
	...

def notify_mentions(ref_doctype, ref_name, content): # -> None:
	...

def extract_mentions(txt): # -> list[Any]:
	"""Find all instances of @mentions in the html."""
	...

