"""
This type stub file was generated by pyright.
"""

import frappe
from functools import lru_cache
from typing import Any

"""build query for doclistview and return results"""
DISALLOWED_PARAMS = ...
@frappe.whitelist()
@frappe.read_only()
def get(): # -> dict[str, Any] | list[Any]:
	...

@frappe.whitelist()
@frappe.read_only()
def get_list(): # -> list[Any]:
	...

@frappe.whitelist()
@frappe.read_only()
def get_count() -> int | None:
	...

def execute(doctype, *args, **kwargs): # -> list[Any]:
	...

def get_form_params(): # -> _dict[Any, Any]:
	"""parse GET request parameters."""
	...

def validate_args(data):
	...

def validate_fields(data): # -> None:
	...

def validate_filters(data, filters): # -> None:
	...

def setup_group_by(data): # -> None:
	"""Add columns for aggregated values e.g. count(name)"""
	...

def raise_invalid_field(fieldname): # -> None:
	...

def is_standard(fieldname): # -> bool:
	...

@lru_cache(maxsize=1024)
def extract_fieldnames(field): # -> list[Any] | list[str]:
	...

def get_meta_and_docfield(fieldname, data): # -> tuple[_Meta, Any | None]:
	...

def update_wildcard_field_param(data): # -> bool:
	...

def clean_params(data): # -> None:
	...

def parse_json(data): # -> None:
	...

def get_parenttype_and_fieldname(field, data): # -> tuple[Any, Any]:
	...

def compress(data, args=...): # -> dict[str, Any]:
	"""separate keys and values"""
	...

@frappe.whitelist(methods=["POST", "PUT"])
def save_report(name: str | int, doctype: str, report_settings: str): # -> Data | None:
	"""Save reports of type Report Builder from Report View"""
	...

@frappe.whitelist(methods=["POST", "DELETE"])
def delete_report(name: str | int): # -> None:
	"""Delete reports of type Report Builder from Report View"""
	...

@frappe.whitelist()
@frappe.read_only()
def export_query(): # -> tuple[Any, Any | Literal['csv', 'xlsx'], bytes | Any] | None:
	"""export from report builder"""
	...

def run_report_view_export_job(user_email, form_params, csv_params): # -> None:
	...

def append_totals_row(data): # -> list[Any]:
	...

def get_field_info(fields, parent_doctype): # -> list[Any]:
	"""
	Get field's
		- fieldname
		- label
		- fieldtype
		- translatable
		- options (if any)

	:param fields: List of field names (can include child table fields and aggregate functions).
	:param parent_doctype: The main doctype from which the report is generated.
	"""
	...

def handle_duration_fieldtype_values(parent_doctype, data, fields):
	...

def parse_field(field: str | dict) -> tuple[str | None, str]:
	"""
	Parse a field into doctype and fieldname.

	:param field: The field string to parse.
	:returns: A tuple of (doctype, fieldname). Doctype is None if not specified.

	:raises ValueError: If the field contains aggregate functions.
	"""
	...

@frappe.whitelist(methods=["POST", "DELETE"])
def delete_items(): # -> None:
	"""delete selected items"""
	...

def delete_bulk(doctype, items): # -> None:
	...

@frappe.whitelist()
@frappe.read_only()
def get_sidebar_stats(stats: str | list[str], doctype: str, filters: str | list | dict[str, Any] | None = ...): # -> dict[str, Any | dict[Any, Any]]:
	...

@frappe.whitelist()
@frappe.read_only()
def get_stats(stats: str, doctype: str, filters: str | None = ...): # -> dict[Any, Any]:
	"""get tag info"""
	...

@frappe.whitelist()
def get_filter_dashboard_data(stats: str, doctype: str, filters: str | None = ...): # -> str:
	"""get tags info"""
	...

def scrub_user_tags(tagcount): # -> list[list[Any]]:
	"""rebuild tag list for tags"""
	...

def get_match_cond(doctype, as_condition=...): # -> str | list[Any]:
	...

def build_match_conditions(doctype, user=..., as_condition=...): # -> str | list[Any]:
	...

def get_filters_cond(doctype, filters, conditions, ignore_permissions=..., with_match_conditions=...): # -> str:
	...

